table 'Eoss Scheme Name'
	lineageTag: 1345a522-a61e-45ff-84d3-4ee0b6a7eeff

	column Transactiontype
		dataType: string
		lineageTag: d3c91fd9-46b7-4d0b-a7ae-bd4621a34c0a
		summarizeBy: none
		sourceColumn: Transactiontype

		annotation SummarizationSetBy = Automatic

	column ItemCodewoBatch
		dataType: int64
		formatString: 0
		lineageTag: e48c020b-2738-4d3a-8ab9-faf966de81ea
		summarizeBy: sum
		sourceColumn: ItemCodewoBatch

		annotation SummarizationSetBy = Automatic

	column TransactionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b2248d45-5402-4695-a987-c3138f8d71d6
		summarizeBy: none
		sourceColumn: TransactionDate

		variation Variation
			isDefault
			relationship: 1be63985-f55d-4e84-8d2e-303ee4571eaa
			defaultHierarchy: LocalDateTable_3bc579a9-9694-4f2c-8184-5ebc98c92711.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TransactionNo
		dataType: string
		lineageTag: 04a4469b-a46e-4e25-8bcf-c217612cea75
		summarizeBy: none
		sourceColumn: TransactionNo

		annotation SummarizationSetBy = Automatic

	column EossSchemeName
		dataType: string
		lineageTag: e6b9ac28-ef46-4095-8470-e4bb36b5f8c8
		summarizeBy: none
		sourceColumn: EossSchemeName

		annotation SummarizationSetBy = Automatic

	column TransactionQuantity
		dataType: int64
		formatString: 0
		lineageTag: 55f172cb-30dd-4fe2-a6eb-fac4ab36069a
		summarizeBy: sum
		sourceColumn: TransactionQuantity

		annotation SummarizationSetBy = Automatic

	partition 'Eoss Scheme Name' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI Report\StockTurnReport\DF\Eoss Scheme Name.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",4),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transactiontype", type text}, {"ItemCodewoBatch", Int64.Type}, {"TransactionDate", type date}, {"TransactionNo", type text}, {"EossSchemeName", type text}, {"TransactionQuantity", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

