createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table 'INWARD & OUTWARD'
			lineageTag: 13b4d141-810a-4d98-969d-76dac3a1c19d

			column 'Transaction type'
				dataType: string
				lineageTag: c81a171c-ded5-4da1-8d74-23cb4d3e4187
				summarizeBy: none
				sourceColumn: Transaction type

				annotation SummarizationSetBy = Automatic

			column 'Transaction Date'
				dataType: dateTime
				formatString: Long Date
				lineageTag: cbe561b7-43de-40fc-ab1a-b5cbc3dfd73f
				summarizeBy: none
				sourceColumn: Transaction Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column 'Transaction No'
				dataType: string
				lineageTag: 94c92df6-04c8-4a1e-865b-d678ec350fa7
				summarizeBy: none
				sourceColumn: Transaction No

				annotation SummarizationSetBy = Automatic

			column 'Transaction Location Id'
				dataType: string
				lineageTag: 1931191a-7f82-410a-b95d-f95c20e0e15c
				summarizeBy: none
				sourceColumn: Transaction Location Id

				annotation SummarizationSetBy = Automatic

			column 'Transaction Location Name'
				dataType: string
				lineageTag: 75400682-6a5e-4c25-b615-b8daf156c7a1
				summarizeBy: none
				sourceColumn: Transaction Location Name

				annotation SummarizationSetBy = Automatic

			column 'Party Name'
				dataType: string
				lineageTag: ee62e067-60ef-497d-ab8f-5b5d8d90d55d
				summarizeBy: none
				sourceColumn: Party Name

				annotation SummarizationSetBy = Automatic

			column 'Party City'
				dataType: string
				lineageTag: d3534014-c38a-435e-b8f4-35ac43f327f6
				summarizeBy: none
				sourceColumn: Party City

				annotation SummarizationSetBy = Automatic

			column 'Brand Name'
				dataType: string
				lineageTag: 52f06829-1f7f-459d-9dd9-8c4435be00c7
				summarizeBy: none
				sourceColumn: Brand Name

				annotation SummarizationSetBy = Automatic

			column 'Section Name'
				dataType: string
				lineageTag: 65e2b18f-2de5-4df4-9853-7c5d7a755a04
				summarizeBy: none
				sourceColumn: Section Name

				annotation SummarizationSetBy = Automatic

			column 'Article Name'
				dataType: string
				lineageTag: 56c3ac59-785a-489c-a2da-d88f7dadbaa3
				summarizeBy: none
				sourceColumn: Article Name

				annotation SummarizationSetBy = Automatic

			column 'Style Name'
				dataType: string
				lineageTag: b3cb895b-efa6-4732-a926-f80b0cd91326
				summarizeBy: none
				sourceColumn: Style Name

				annotation SummarizationSetBy = Automatic

			column 'Article No'
				dataType: string
				lineageTag: 80d7f6af-b923-44cf-86f6-bae68aec71e6
				summarizeBy: none
				sourceColumn: Article No

				annotation SummarizationSetBy = Automatic

			column Weather
				dataType: string
				lineageTag: ada59d11-592b-465d-87b4-468c9df994d6
				summarizeBy: none
				sourceColumn: Weather

				annotation SummarizationSetBy = Automatic

			column 'Item Class'
				dataType: string
				lineageTag: bff3d0f7-8cb8-4410-8fba-01c46518424d
				summarizeBy: none
				sourceColumn: Item Class

				annotation SummarizationSetBy = Automatic

			column Gender
				dataType: string
				lineageTag: 8462c962-a41c-4dc7-bc93-07624a1ca6d9
				summarizeBy: none
				sourceColumn: Gender

				annotation SummarizationSetBy = Automatic

			column Category
				dataType: string
				lineageTag: 1a5801c0-d660-4cd4-9db6-b4f2eff24718
				summarizeBy: none
				sourceColumn: Category

				annotation SummarizationSetBy = Automatic

			column 'HSN Code'
				dataType: int64
				formatString: 0
				lineageTag: e51256e6-77c9-4184-87de-e44ab779dbc0
				summarizeBy: count
				sourceColumn: HSN Code

				annotation SummarizationSetBy = Automatic

			column 'Colour Name'
				dataType: string
				lineageTag: 43c28f2f-d615-4524-8eef-b35cd49342ac
				summarizeBy: none
				sourceColumn: Colour Name

				annotation SummarizationSetBy = Automatic

			column 'SKU RSP'
				dataType: int64
				formatString: 0
				lineageTag: 0b9fe3ae-8fb4-423d-ae4e-51ccb3305a8d
				summarizeBy: sum
				sourceColumn: SKU RSP

				annotation SummarizationSetBy = Automatic

			column 'Transaction RSP'
				dataType: int64
				formatString: 0
				lineageTag: abc891ce-428d-4581-9160-277325164f33
				summarizeBy: sum
				sourceColumn: Transaction RSP

				annotation SummarizationSetBy = Automatic

			column 'Bin Name'
				dataType: string
				lineageTag: 693eb2c9-4972-4089-a930-54d9009842c1
				summarizeBy: none
				sourceColumn: Bin Name

				annotation SummarizationSetBy = Automatic

			column 'Transaction Quantity'
				dataType: int64
				formatString: 0
				lineageTag: dc510f24-cc70-477f-ac98-0ca3a47d723d
				summarizeBy: sum
				sourceColumn: Transaction Quantity

				annotation SummarizationSetBy = Automatic

			column 'Transaction Taxable Value'
				dataType: double
				lineageTag: 7f762c0e-889a-497c-99c6-5fd0e0ff7f5c
				summarizeBy: sum
				sourceColumn: Transaction Taxable Value

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Transaction Total GST Amt'
				dataType: int64
				formatString: 0
				lineageTag: 6c94e47f-ce5c-41c0-a166-3934055bc551
				summarizeBy: sum
				sourceColumn: Transaction Total GST Amt

				annotation SummarizationSetBy = Automatic

			column 'Transaction Value at MRP'
				dataType: int64
				formatString: 0
				lineageTag: 01a03e32-186a-4e65-9450-79beaf387d08
				summarizeBy: sum
				sourceColumn: Transaction Value at MRP

				annotation SummarizationSetBy = Automatic

			column 'Transaction Value with GST'
				dataType: double
				lineageTag: b9cc4e2d-5223-4c2b-b079-3657f143b311
				summarizeBy: sum
				sourceColumn: Transaction Value with GST

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column UPC
				dataType: string
				lineageTag: c46c6488-17b7-4e2b-9f43-12e7746ead73
				summarizeBy: none
				sourceColumn: UPC

				annotation SummarizationSetBy = Automatic

			column Uid
				dataType: string
				lineageTag: b3f406fc-8d81-4f74-a74e-65df51161951
				summarizeBy: none
				sourceColumn: Uid

				annotation SummarizationSetBy = Automatic

			column sum_product = ```
					
					 var _Branch =    SWITCH(TRUE(),
					                        'INWARD & OUTWARD'[Islatestdate] = TRUE() 
					                        && 
					                        'INWARD & OUTWARD'[Transaction type] = "Group Purchase"
					                                , 'INWARD & OUTWARD'[Transaction Date] * 'INWARD & OUTWARD'[Transaction Quantity],
					                        [Closing] = 0  
					                        && 
					                        'INWARD & OUTWARD'[Transaction type] = "Group Purchase"
					                                ,'INWARD & OUTWARD'[Transaction Date] * 'INWARD & OUTWARD'      [Transaction Quantity]
					                        ,0)
					 var _LASA =    SWITCH(TRUE(),
					                        'INWARD & OUTWARD'[Islatestdate] = TRUE() 
					                        && 
					                        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"} 
					                        &&
					                        'INWARD & OUTWARD'[ISfresh] = TRUE()
					                                , 'INWARD & OUTWARD'[Transaction Date] * 'INWARD & OUTWARD'[Transaction Quantity],
					                        [Closing] = 0  
					                        && 
					                        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"} 
					                        &&
					                        'INWARD & OUTWARD'[ISfresh] = TRUE()
					                                ,'INWARD & OUTWARD'[Transaction Date] * 'INWARD & OUTWARD'      [Transaction Quantity]
					                        ,0)
					RETURN
					          IF('INWARD & OUTWARD'[Transaction Location Id] in {"LA", "SA"}, _LASA, _Branch)
					```
				lineageTag: b133c1a0-aa27-4957-acac-e12414a3abba
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column MaxSaleDate = ```
					
					VAR CurrLoc = 'INWARD & OUTWARD'[Transaction Location Id]
					VAR CurrArticle = 'INWARD & OUTWARD'[Article No]
					var CurrUPC = 'INWARD & OUTWARD'[UPC]
					RETURN
					    CALCULATE(
					        MAX('INWARD & OUTWARD'[Transaction Date]),
					        FILTER(
					            'INWARD & OUTWARD',
					            'INWARD & OUTWARD'[Transaction Location Id] = CurrLoc
					            && 'INWARD & OUTWARD'[UPC] = CurrUPC
					            // && 'INWARD & OUTWARD'[Article No] = CurrArticle
					        )
					    )
					
					```
				formatString: General Date
				lineageTag: 3d146770-105e-4868-9c84-9aa4e0e764f9
				summarizeBy: none

				variation Variation
					isDefault
					relationship: 7a7a44a5-b5b4-4835-98cb-0beba1c0398d
					defaultHierarchy: LocalDateTable_7edc6a93-bd7e-45f9-aef3-05d82ebd2a2f.'Date Hierarchy'

				annotation SummarizationSetBy = Automatic

			column 'Size Name'
				dataType: string
				lineageTag: 8e506ca7-fe2b-40b6-a92b-33654fb0e3ea
				summarizeBy: none
				sourceColumn: Size Name

				annotation SummarizationSetBy = Automatic

			column Season2
				dataType: string
				lineageTag: e9367de6-9b37-4167-b843-6b610ee40718
				summarizeBy: none
				sourceColumn: Season2

				annotation SummarizationSetBy = Automatic

			column 'Season Name'
				dataType: string
				lineageTag: e6b45b5d-a50b-45bc-a6d6-eaf6457e3928
				summarizeBy: none
				sourceColumn: Season Name

				annotation SummarizationSetBy = Automatic

			column runnintotal =
					
					
					var _Branch = IF('INWARD & OUTWARD'[Transaction type] = "Group Purchase",
					                    CALCULATE(SUM('INWARD & OUTWARD'[Transaction Quantity]),
					                        FILTER(ALLSELECTED('INWARD & OUTWARD'),
					                            'INWARD & OUTWARD'[Uid] = EARLIEST('INWARD & OUTWARD'[Uid]) &&
					                            'INWARD & OUTWARD'[Transaction Location Id] = EARLIEST('INWARD & OUTWARD'[Transaction Location Id]) &&
					                            'INWARD & OUTWARD'[Transaction Date] >= EARLIEST('INWARD & OUTWARD'[Transaction Date]) &&
					                            'INWARD & OUTWARD'[Transaction type] = "Group Purchase")))
					
					
					var _LASA = IF('INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"} &&
					                            'INWARD & OUTWARD'[ISfresh] = TRUE(),
					                    CALCULATE(SUM('INWARD & OUTWARD'[Transaction Quantity]),
					                        FILTER(ALLSELECTED('INWARD & OUTWARD'),
					                            'INWARD & OUTWARD'[Uid] = EARLIEST('INWARD & OUTWARD'[Uid]) &&
					                            'INWARD & OUTWARD'[Transaction Location Id] = EARLIEST('INWARD & OUTWARD'[Transaction Location Id]) &&
					                            'INWARD & OUTWARD'[Transaction Date] >= EARLIEST('INWARD & OUTWARD'[Transaction Date]) &&
					                            'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"} &&
					                            'INWARD & OUTWARD'[ISfresh] = TRUE())))
					
					
					
					return
					       IF('INWARD & OUTWARD'[Transaction Location Id] in {"LA", "SA"}, _LASA, _Branch)
				formatString: 0
				lineageTag: e357ded3-3af2-4d15-b080-9f7c3674993c
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

			column closing = ```
					CALCULATE(SUM(OBS_sheet[CBS Qty]), 
					                                FILTER(OBS_sheet,
					                                OBS_sheet[Location Id] = EARLIEST('INWARD & OUTWARD'[Transaction Location Id])
					                                &&  OBS_sheet[UPC] = EARLIEST('INWARD & OUTWARD'[UPC])))
					```
				formatString: 0
				lineageTag: 2f7e838f-f8fc-433d-b75b-61b8b7a5e510
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

			column diff = ```
					
					    [Closing] - 'INWARD & OUTWARD'[runnintotal]
					// MIN('INWARD & OUTWARD'[runnintotal], [Closing])
					```
				formatString: 0
				lineageTag: 9f2aa581-80c8-4e3e-9cd8-7bc0ec6226fd
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

			column Islatestdate = ```
					
					
					var _latestpointBranch = IF('INWARD & OUTWARD'[Transaction type] = "Group Purchase",
					                    CALCULATE(MIN('INWARD & OUTWARD'[diff]),
					                        FILTER(ALL('INWARD & OUTWARD'),
					                            'INWARD & OUTWARD'[Uid] = EARLIEST('INWARD & OUTWARD'[Uid]) &&
					                            'INWARD & OUTWARD'[Transaction Location Id] = EARLIEST('INWARD & OUTWARD'[Transaction Location Id]) &&
					                            'INWARD & OUTWARD'[diff] > EARLIEST('INWARD & OUTWARD'[diff]) &&
					                            'INWARD & OUTWARD'[Transaction type] = "Group Purchase")))
					
					var _latestpointLASA = IF('INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"} &&
					                            'INWARD & OUTWARD'[ISfresh] = TRUE(),
					                    CALCULATE(MIN('INWARD & OUTWARD'[diff]),
					                        FILTER(ALL('INWARD & OUTWARD'),
					                            'INWARD & OUTWARD'[Uid] = EARLIEST('INWARD & OUTWARD'[Uid]) &&
					                            'INWARD & OUTWARD'[Transaction Location Id] = EARLIEST('INWARD & OUTWARD'[Transaction Location Id]) &&
					                            'INWARD & OUTWARD'[diff] > EARLIEST('INWARD & OUTWARD'[diff]) &&
					                            'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"} &&
					                            'INWARD & OUTWARD'[ISfresh] = TRUE())))
					
					
					var _confirmation = IF('INWARD & OUTWARD'[Transaction Location Id] in {"LA", "SA"}, _latestpointLASA, _latestpointBranch)
					
					RETURN 
					
					SWITCH(TRUE(),
					    [Closing] = 0, FALSE(),
					     _confirmation >= 1, TRUE(),
					      ISBLANK(_confirmation) , TRUE())
					
					
					
					// SWITCH(TRUE(),
					//     [Closing] = 0, FALSE(),
					//      _latestpoint >= 1, TRUE(),
					//       ISBLANK(_latestpoint) , TRUE())
					```
				formatString: """TRUE"";""TRUE"";""FALSE"""
				lineageTag: 1a73504e-ce62-442d-a477-48290eb29748
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column ISfresh = ```
					
					CONTAINSSTRING('INWARD & OUTWARD'[Transaction No], "GPG") ||
					CONTAINSSTRING('INWARD & OUTWARD'[Transaction No], "CRT") ||
					CONTAINSSTRING('INWARD & OUTWARD'[Transaction No], "PGG") ||
					CONTAINSSTRING('INWARD & OUTWARD'[Transaction No], "PG")
					
					```
				formatString: """TRUE"";""TRUE"";""FALSE"""
				lineageTag: 7137e998-4b31-412a-9fd6-07a5edb1058f
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			partition 'INWARD & OUTWARD' = m
				mode: import
				source = ```
						let
						    Source = Csv.Document(File.Contents("C:\Users\BAPS\Downloads\INWARD & OUTWARD-PB.csv"),[Delimiter=",", Columns=30, Encoding=1252, QuoteStyle=QuoteStyle.None]),
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction type", type text}, {"Transaction Date", type date}, {"Transaction No", type text}, {"Transaction Location Id", type text}, {"Transaction Location Name", type text}, {"Party Name", type text}, {"Party City", type text},  {"Brand Name", type text}, {"Section Name", type text}, {"Article Name", type text}, {"Style Name", type text}, {"Article No", type text}, {"Weather", type text}, {"Item Class", type text}, {"Gender", type text}, {"Category", type text}, {"HSN Code", Int64.Type}, {"Colour Name", type text}, {"SKU RSP", Int64.Type}, {"Transaction RSP", Int64.Type}, {"Bin Name", type text}, {"Transaction Quantity", Int64.Type}, {"Transaction Taxable Value", type number}, {"Transaction Total GST Amt", Int64.Type}, {"Transaction Value at MRP", Int64.Type}, {"Transaction Value with GST", type number}}),
						    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each not Text.Contains([Transaction type], "Total")),
						    #"Trimmed Text" = Table.TransformColumns(#"Filtered Rows",{{"Transaction Location Id", Text.Trim, type text}}),
						    #"Changed Type2" = Table.TransformColumnTypes(#"Trimmed Text",{{"Item Code w/o Batch", type text}}),
						    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Item Code w/o Batch", "UPC"}}),
						    #"Trimmed Text1" = Table.TransformColumns(#"Renamed Columns",{{"UPC", Text.Trim, type text}}),
						    #"Inserted Merged Column" = Table.AddColumn(#"Trimmed Text1", "Uid", each Text.Combine({[UPC], Text.From([SKU RSP], "en-US")}, ""), type text),
						    #"Filtered Rows1" = Table.SelectRows(#"Inserted Merged Column", each ([Transaction Location Id] <> "HP" and [Transaction Location Id] <> "LS")),
						    #"Added Custom" = Table.AddColumn(#"Filtered Rows1", "Filter_uwwanted_rows", each if 
						   ([Transaction Location Id] = "SA" or [Transaction Location Id] = "LA")
						   and
						   (
						       Text.Contains([Transaction No], "GPG") or
						       Text.Contains([Transaction No], "CRT") or
						       Text.Contains([Transaction No], "PGG") or
						       Text.Contains([Transaction No], "PG") or 
						       Text.Contains([Transaction type], "Group Wholesale") or     Text.Contains([Transaction type], "Party Wholesale")
						   )
						then true else false),
						    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Isbranch", each if 
						   ([Transaction Location Id] <> "SA" and [Transaction Location Id] <> "LA")
						then true else false),
						    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "FinalSelection", each [Filter_uwwanted_rows] = true or [Isbranch] = true),
						    #"Filtered Rows2" = Table.SelectRows(#"Added Custom2", each ([FinalSelection] = true)),
						    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows2",{"Filter_uwwanted_rows", "Isbranch", "FinalSelection"})
						in
						    #"Removed Columns"
						```

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table DateTableTemplate_3bfbd36a-a61a-4bb3-87eb-ae97c05974bf
			isHidden
			isPrivate
			lineageTag: a1fb9e09-d97b-4a29-9781-b2374d15689f

			column Date
				dataType: dateTime
				isHidden
				lineageTag: e4e2a895-a4aa-4cd0-8c83-abd86d0d9d2f
				dataCategory: PaddedDateTableDates
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = User

			column Year = YEAR([Date])
				dataType: int64
				isHidden
				lineageTag: 6c65ef34-3157-463c-908f-4a9b5ec72528
				dataCategory: Years
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Year

			column MonthNo = MONTH([Date])
				dataType: int64
				isHidden
				lineageTag: 95f9d3e5-6c33-41b3-a9a3-42e90b3619d9
				dataCategory: MonthOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = MonthNumber

			column Month = FORMAT([Date], "MMMM")
				dataType: string
				isHidden
				lineageTag: 90fe14ba-6bd0-4240-aff3-5694ced37a0f
				dataCategory: Months
				summarizeBy: none
				sortByColumn: MonthNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Month

			column QuarterNo = INT(([MonthNo] + 2) / 3)
				dataType: int64
				isHidden
				lineageTag: 09d09790-1d79-4e2e-8da2-fd87a1d668e8
				dataCategory: QuarterOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = QuarterNumber

			column Quarter = "Qtr " & [QuarterNo]
				dataType: string
				isHidden
				lineageTag: 8b3856c9-2794-4d17-98c2-613d6ec3d95a
				dataCategory: Quarters
				summarizeBy: none
				sortByColumn: QuarterNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Quarter

			column Day = DAY([Date])
				dataType: int64
				isHidden
				lineageTag: 4413cd4d-7711-4dfe-8e05-245cadceb251
				dataCategory: DayOfMonth
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Day

			hierarchy 'Date Hierarchy'
				lineageTag: da20a96d-41a3-49c1-ac98-df04dd034552

				level Year
					lineageTag: 32840a9c-0a22-4a9f-97b1-8c98d5732412
					column: Year

				level Quarter
					lineageTag: 38a0c0a2-9e20-475e-8de8-de1fca5e8fa0
					column: Quarter

				level Month
					lineageTag: 7a7df774-b5e8-43a3-a57e-2d8640e0c5bc
					column: Month

				level Day
					lineageTag: 490d18de-4f59-49ed-a308-b9e88b25425c
					column: Day

				annotation TemplateId = DateHierarchy

			partition DateTableTemplate_3bfbd36a-a61a-4bb3-87eb-ae97c05974bf = calculated
				mode: import
				source = Calendar(Date(2015,1,1), Date(2015,1,1))

			annotation __PBI_TemplateDateTable = true

			annotation DefaultItem = DateHierarchy

		table OBS_sheet
			lineageTag: 8bf5c9d4-c811-499c-b1fa-6f310cd5c934

			column 'Location Id'
				dataType: string
				lineageTag: b6a80a9c-d3df-4663-a256-c953e5b19ae7
				summarizeBy: none
				sourceColumn: Location Id

				annotation SummarizationSetBy = Automatic

			column 'Location Alias'
				dataType: string
				lineageTag: 2236d2c6-5930-4636-a1d7-ea521835609d
				summarizeBy: none
				sourceColumn: Location Alias

				annotation SummarizationSetBy = Automatic

			column 'Location Name'
				dataType: string
				lineageTag: 26d98e53-d960-4e6d-ac79-420182925d9c
				summarizeBy: none
				sourceColumn: Location Name

				annotation SummarizationSetBy = Automatic

			column 'Item Code'
				dataType: string
				lineageTag: 81925779-f33a-4a2f-9703-812a022519f6
				summarizeBy: none
				sourceColumn: Item Code

				annotation SummarizationSetBy = Automatic

			column UPC
				dataType: string
				lineageTag: cbb190dd-5589-4cb8-b540-57ca903272fe
				summarizeBy: none
				sourceColumn: UPC

				annotation SummarizationSetBy = Automatic

			column 'Article No'
				dataType: string
				lineageTag: 9f690adc-59df-4856-bd8e-3e9fb5e3828b
				summarizeBy: none
				sourceColumn: Article No

				annotation SummarizationSetBy = Automatic

			column 'Section Name'
				dataType: string
				lineageTag: 484fb157-c83c-47d1-ba3e-95f7ebc631a8
				summarizeBy: none
				sourceColumn: Section Name

				annotation SummarizationSetBy = Automatic

			column 'Sub Section Name'
				dataType: string
				lineageTag: 4ebf63ce-6e5f-4519-9ef9-0cb9ef66879e
				summarizeBy: none
				sourceColumn: Sub Section Name

				annotation SummarizationSetBy = Automatic

			column 'Article Name'
				dataType: string
				lineageTag: d125f32e-48a9-41f8-b0aa-815c470bea10
				summarizeBy: none
				sourceColumn: Article Name

				annotation SummarizationSetBy = Automatic

			column Gender
				dataType: string
				lineageTag: effed7e0-6da5-4b21-adfe-00119852323a
				summarizeBy: none
				sourceColumn: Gender

				annotation SummarizationSetBy = Automatic

			column 'Brand Name'
				dataType: string
				lineageTag: 699c787b-45e6-43f1-b461-21df63a51bbb
				summarizeBy: none
				sourceColumn: Brand Name

				annotation SummarizationSetBy = Automatic

			column 'Size Name'
				dataType: string
				lineageTag: abf67924-eeb8-4481-8b4b-05fec041f802
				summarizeBy: none
				sourceColumn: Size Name

				annotation SummarizationSetBy = Automatic

			column 'SKU RSP'
				dataType: int64
				formatString: 0
				lineageTag: c7bb7d30-19ae-4c95-985d-64afe0ffcb99
				summarizeBy: sum
				sourceColumn: SKU RSP

				annotation SummarizationSetBy = Automatic

			column 'Wholesale Price'
				dataType: int64
				formatString: 0
				lineageTag: 02734256-44cb-4086-bd81-05bf769f93f4
				summarizeBy: sum
				sourceColumn: Wholesale Price

				annotation SummarizationSetBy = Automatic

			column 'OBS Qty'
				dataType: int64
				formatString: 0
				lineageTag: efbe1fe8-e790-43f6-910e-cb95203ad73d
				summarizeBy: sum
				sourceColumn: OBS Qty

				annotation SummarizationSetBy = Automatic

			column 'OBS Value at MRP'
				dataType: int64
				formatString: 0
				lineageTag: 02e13273-dc8a-44bd-a432-e327a74558b8
				summarizeBy: sum
				sourceColumn: OBS Value at MRP

				annotation SummarizationSetBy = Automatic

			column 'CBS Qty'
				dataType: int64
				formatString: 0
				lineageTag: 3db2d01d-9457-4581-bbce-55e7697ab246
				summarizeBy: sum
				sourceColumn: CBS Qty

				annotation SummarizationSetBy = Automatic

			column 'CBS Value at MRP'
				dataType: int64
				formatString: 0
				lineageTag: c6aa42fe-cf18-42fe-9ada-6ce49ac1fc1a
				summarizeBy: sum
				sourceColumn: CBS Value at MRP

				annotation SummarizationSetBy = Automatic

			column 'CBS Value at WSP'
				dataType: int64
				formatString: 0
				lineageTag: 61588dba-a513-49a7-a137-ed233ea0bf34
				summarizeBy: sum
				sourceColumn: CBS Value at WSP

				annotation SummarizationSetBy = Automatic

			column 'Net SLS Qty'
				dataType: int64
				formatString: 0
				lineageTag: 34c76ce1-ce00-4846-bbe7-b67eb57646a3
				summarizeBy: sum
				sourceColumn: Net SLS Qty

				annotation SummarizationSetBy = Automatic

			column Uid
				dataType: string
				lineageTag: 01120227-dd14-4604-a2a6-91143d5fa831
				summarizeBy: none
				sourceColumn: Uid

				annotation SummarizationSetBy = Automatic

			column OpeningDate = DATE(2025,4,1)
				formatString: Long Date
				lineageTag: 69958f6e-1611-43f7-b835-2bdd7ad4f8b7
				summarizeBy: none

				changedProperty = DataType

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column ClosingDate = TODAY()
				formatString: Long Date
				lineageTag: 384222a4-9bee-4900-b28f-59925a49a2bf
				summarizeBy: none

				changedProperty = DataType

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column MRPValue = OBS_sheet[SKU RSP] * OBS_sheet[CBS Qty]
				formatString: 0
				lineageTag: af0010ba-df79-44e7-9087-569e614e7508
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

			column Season2
				dataType: string
				lineageTag: 6e9229da-29b4-4838-932a-a70f09e39826
				summarizeBy: none
				sourceColumn: Season2

				annotation SummarizationSetBy = Automatic

			column 'Season Name'
				dataType: string
				lineageTag: ae7313ca-a2a3-4ab4-b035-ea62269efcdf
				summarizeBy: none
				sourceColumn: Season Name

				annotation SummarizationSetBy = Automatic

			column Column1
				dataType: string
				lineageTag: 3384c55d-83cf-49ae-bf38-b318100ac519
				summarizeBy: none
				sourceColumn: Column1

				annotation SummarizationSetBy = Automatic

			column _1
				dataType: string
				lineageTag: bf7542d4-6866-4b03-bc49-46118d8ff0e4
				summarizeBy: none
				sourceColumn: _1

				annotation SummarizationSetBy = Automatic

			column _2
				dataType: string
				lineageTag: c39f8895-0ec0-4aa4-bf4f-2ef872b9b99d
				summarizeBy: none
				sourceColumn: _2

				annotation SummarizationSetBy = Automatic

			column _3
				dataType: string
				lineageTag: ab44567f-9310-4958-b83b-3f2a8f07cf74
				summarizeBy: none
				sourceColumn: _3

				annotation SummarizationSetBy = Automatic

			column _4
				dataType: string
				lineageTag: 72d57e53-6859-4946-8f77-fe98f203a632
				summarizeBy: none
				sourceColumn: _4

				annotation SummarizationSetBy = Automatic

			column _5
				dataType: string
				lineageTag: 0b1e37f3-f46e-4d3b-8010-6fc664149fbb
				summarizeBy: none
				sourceColumn: _5

				annotation SummarizationSetBy = Automatic

			column _6
				dataType: string
				lineageTag: 198e2126-a0d2-42ae-ba3a-6919f220e271
				summarizeBy: none
				sourceColumn: _6

				annotation SummarizationSetBy = Automatic

			column _7
				dataType: string
				lineageTag: 9689459a-95f5-4a19-b28d-cc83c2cc573d
				summarizeBy: none
				sourceColumn: _7

				annotation SummarizationSetBy = Automatic

			partition OBS_sheet = m
				mode: import
				source =
						let
						    Source = Csv.Document(File.Contents("C:\Users\BAPS\Downloads\OBS_sheet-PB.csv"),[Delimiter=",", Columns=30, Encoding=1252, QuoteStyle=QuoteStyle.None]),
						    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
						    #"Filtered Rows" = Table.SelectRows(#"Promoted Headers", each not Text.Contains([Location Id], "total")),
						    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"Location Id", type text}, {"Location Alias", type text}, {"Location Name", type text}, {"Item Code", type text}, {"Item Code w/o Batch", type text}, {"Article No", type text}, {"Section Name", type text}, {"Sub Section Name", type text}, {"Article Name", type text}, {"Gender", type text}, {"Brand Name", type text}, {"Size Name", type text}, {"SKU RSP", Int64.Type}, {"Wholesale Price", Int64.Type}, {"OBS Qty", Int64.Type}, {"OBS Value at MRP", Int64.Type}, {"CBS Qty", Int64.Type}, {"CBS Value at MRP", Int64.Type}, {"CBS Value at WSP", Int64.Type}, {"Net SLS Qty", Int64.Type}}),
						    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"Item Code w/o Batch", Text.Trim, type text}, {"Location Id", Text.Trim, type text}}),
						    #"Renamed Columns" = Table.RenameColumns(#"Trimmed Text",{{"Item Code w/o Batch", "UPC"}}),
						    #"Trimmed Text1" = Table.TransformColumns(#"Renamed Columns",{{"UPC", Text.Trim, type text}}),
						    #"Inserted Merged Column" = Table.AddColumn(#"Trimmed Text1", "Uid", each Text.Combine({[UPC], Text.From([SKU RSP], "en-US")}, ""), type text)
						in
						    #"Inserted Merged Column"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table LocationMaster
			lineageTag: bd293602-d2a7-4e92-8d19-c34bae033791

			column LocationID
				dataType: string
				lineageTag: aa8fc282-0feb-49e8-8806-6e9f6ed22b7d
				summarizeBy: none
				sourceColumn: LocationID

				annotation SummarizationSetBy = Automatic

			column Code
				dataType: string
				lineageTag: 8f8a41e8-5bb7-4df4-a82b-00c31489f24f
				summarizeBy: none
				sourceColumn: Code

				annotation SummarizationSetBy = Automatic

			column LocationName
				dataType: string
				lineageTag: e60772ac-d029-4100-98fd-c11281180033
				summarizeBy: none
				sourceColumn: LocationName

				annotation SummarizationSetBy = Automatic

			partition LocationMaster = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bZHdbsIwDIVfxeoVSBRBN7Hdum3ahjptZKdswHiMvf/yB5rGbiy354t9bF+vxX5XbApztL0rm8antJUtsHKoSUqDdNJnhAl75OK28fg+4PUgU9l1PhWnrEA9aPpAxoRUAZGeJSGs20GDxOgLksDX925XHcAs5LQl9akE7MkBuXabKryECthL/ewJShBs725ek3nH/5iHI2q7MKwisE4PDuGBufRj2QRvq5iv4U8Hs1yw65B/zf3m6bFmuzw6ZR5qZKWJzrCKem70HvilbcwTv7TZV5QTXoUrELemTzsjpeYpKoThMwY1+9HJL6uZ2c6MTmdGgpzCPKBJVFQG63/mAKQ7Je5M6r5twD7fjCQ0SOGxh4dahaOP43Qx/95jxMnPk8h8+yHfflxqxdDNs7OsJ+dN3X4A", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [LocationID = _t, Code = _t, LocationName = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"LocationID", type text}, {"Code", type text}, {"LocationName", type text}})
						in
						    #"Changed Type"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Calendar
			lineageTag: 21246b47-7ae3-47fd-bc8c-7d21f26ee74d

			column Date
				formatString: d mmmm\, yyyy
				lineageTag: 49258298-e943-46a2-a734-83ac7b539f5e
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				variation Variation
					isDefault
					relationship: bd144136-b34e-434c-ba6d-714df39cd95d
					defaultHierarchy: LocalDateTable_b94575be-bcbb-4510-a5ed-a6c6575effc8.'Date Hierarchy'

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isDateTimeCustom":true}

			column DateKey
				formatString: 0
				lineageTag: b6aee564-d98e-4e69-a500-41ee5141b7e5
				summarizeBy: count
				isNameInferred
				sourceColumn: [DateKey]

				annotation SummarizationSetBy = Automatic

			column 'Sequential Day Number'
				formatString: 0
				lineageTag: 2abfa913-bab5-40c9-a39c-82ad8aadebda
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Sequential Day Number]

				annotation SummarizationSetBy = Automatic

			column 'Year Month'
				lineageTag: be2d0b68-92e9-43fc-9981-e28d12d5a71e
				summarizeBy: none
				isNameInferred
				sourceColumn: [Year Month]

				annotation SummarizationSetBy = Automatic

			column 'Year Month Number'
				formatString: 0
				lineageTag: f6b89cf4-e56d-4ac2-93b6-c983273893ad
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Year Month Number]

				annotation SummarizationSetBy = Automatic

			column 'Fiscal Year'
				lineageTag: 1aee3bcd-9202-4060-aee0-2f7c2eb239d3
				summarizeBy: none
				isNameInferred
				sourceColumn: [Fiscal Year]

				annotation SummarizationSetBy = Automatic

			column 'Fiscal Year Number'
				formatString: 0
				lineageTag: 8a8aa996-d043-4f5d-b0e7-7f996c839bbe
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Fiscal Year Number]

				annotation SummarizationSetBy = Automatic

			column 'Fiscal Year Quarter'
				lineageTag: 769c2ca6-f835-464c-9999-ebd8b8f06a07
				summarizeBy: none
				isNameInferred
				sourceColumn: [Fiscal Year Quarter]

				annotation SummarizationSetBy = Automatic

			column 'Fiscal Year Quarter Number'
				formatString: 0
				lineageTag: 5d70aef1-097c-4d68-bd5a-0af22fcf8d79
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Fiscal Year Quarter Number]

				annotation SummarizationSetBy = Automatic

			column 'Fiscal Quarter'
				lineageTag: 341273eb-5dd8-46ec-bf48-d9b8bf428cfd
				summarizeBy: none
				isNameInferred
				sourceColumn: [Fiscal Quarter]

				annotation SummarizationSetBy = Automatic

			column Month
				lineageTag: 2b7f3875-22ff-4eb7-a900-003e976e2ff6
				summarizeBy: none
				isNameInferred
				sourceColumn: [Month]

				annotation SummarizationSetBy = Automatic

			column 'Fiscal Month Number'
				formatString: 0
				lineageTag: 5c06d83c-2fce-44b5-813f-896fc8c0b8ef
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Fiscal Month Number]

				annotation SummarizationSetBy = Automatic

			column 'Fiscal Month in Quarter Number'
				lineageTag: cdfbaae3-2db7-4047-923b-5d279c48c366
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Fiscal Month in Quarter Number]

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Day of Week'
				lineageTag: 25baa253-522d-4d97-b550-53c7bcc79d7f
				summarizeBy: none
				isNameInferred
				sourceColumn: [Day of Week]

				annotation SummarizationSetBy = Automatic

			column 'Day of Week Number'
				formatString: 0
				lineageTag: 4dbbaaea-77f0-4ef6-8305-c52e43ddb71f
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Day of Week Number]

				annotation SummarizationSetBy = Automatic

			column 'Day of Month Number'
				formatString: 0
				lineageTag: d90b8da6-0971-4202-baa2-3ab4ed6a73a2
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Day of Month Number]

				annotation SummarizationSetBy = Automatic

			column 'Day of Fiscal Year Number'
				formatString: 0
				lineageTag: 30fe1ab4-7d34-489a-a78d-5cabf1cb443a
				summarizeBy: sum
				isNameInferred
				sourceColumn: [Day of Fiscal Year Number]

				annotation SummarizationSetBy = Automatic

			column 'Working Day'
				lineageTag: 6857ead0-dd9c-4ce6-a974-79af7166a6c5
				summarizeBy: none
				isNameInferred
				sourceColumn: [Working Day]

				annotation SummarizationSetBy = Automatic

			partition Calendar = calculated
				mode: import
				source =
						
						// VAR _MinDate = MIN(TradePurchaseTable[INV DATE])
						VAR _MinDate = MIN('INWARD & OUTWARD'[Transaction Date])
						VAR _MaxDate = MAX('INWARD & OUTWARD'[Transaction Date]) -- MAX(RetailSale[Voucher Date])
						VAR FirstFiscalMonth = 4  -- First month of the fiscal year
						VAR FirstDayOfWeek = 0    -- 0 = Sunday, 1 = Monday, ...
						VAR FirstCreateDate = _MinDate
						VAR LastPaymentDate = _MaxDate
						VAR FirstFiscalYear =     -- Customizes the first fiscal year to use
						    YEAR ( FirstCreateDate )
						    + 1 * ( MONTH ( FirstCreateDate ) >= FirstFiscalMonth && FirstFiscalMonth > 1)
						VAR LastFiscalYear =      -- Customizes the last fiscal year to use
						    YEAR ( LastPaymentDate )
						    + 1 * ( MONTH ( LastPaymentDate ) >= FirstFiscalMonth && FirstFiscalMonth > 1)
						RETURN
						GENERATE (
						    VAR FirstDay =
						        DATE (
						            FirstFiscalYear - 1 * (FirstFiscalMonth > 1),
						            FirstFiscalMonth,
						            1
						        )
						    VAR LastDay =
						        DATE (
						            LastFiscalYear + 1 * (FirstFiscalMonth = 1),
						            FirstFiscalMonth, 1
						        ) - 1
						    RETURN
						        CALENDAR ( FirstDay, LastDay ),
						    VAR CurrentDate = [Date]
						    VAR Yr = YEAR ( CurrentDate )        -- Year Number
						    VAR Mn = MONTH ( CurrentDate )       -- Month Number (1-12)
						    VAR Mdn = DAY ( CurrentDate )        -- Day of Month
						    VAR DateKey = Yr*10000+Mn*100+Mdn
						    VAR Wd =                             -- Weekday Number (0 = Sunday, 1 = Monday, ...)
						        WEEKDAY ( CurrentDate + 7 - FirstDayOfWeek, 1 )
						    VAR WorkingDay =                     -- Working Day (1 = working, 0 = non-working)
						        ( WEEKDAY ( CurrentDate, 1 ) IN { 2, 3, 4, 5, 6 } )
						    VAR Fyr =                            -- Fiscal Year Number
						        Yr + 1 * ( FirstFiscalMonth > 1 && Mn >= FirstFiscalMonth )
						    VAR Fmn =                            -- Fiscal Month Number (1-12)
						        Mn - FirstFiscalMonth + 1 + 12 * (Mn < FirstFiscalMonth)
						    VAR Fqrn =                           -- Fiscal Quarter (string)
						        ROUNDUP ( Fmn / 3, 0 )
						    VAR Fmqn =
						        MOD ( FMn - 1, 3 ) + 1
						    VAR Fqr =                            -- Fiscal Quarter (string)
						        FORMAT ( Fqrn, "\Q0" )
						    VAR FirstDayOfYear =
						        DATE ( Fyr - 1 * (FirstFiscalMonth > 1), FirstFiscalMonth, 1 )
						    VAR Fydn =
						        SUMX (
						            CALENDAR ( FirstDayOfYear, CurrentDate ),
						            1 * ( MONTH ( [Date] ) <> 2 || DAY ( [Date] ) <> 29 )
						        )
						    RETURN ROW (
						        "DateKey", INT ( DateKey ),
						        "Sequential Day Number", INT ( [Date] ),
						        "Year Month", FORMAT ( CurrentDate, "mmm yyyy" ),
						        "Year Month Number", Yr * 12 + Mn - 1,
						        "Fiscal Year", "FY " & Fyr - 1&"-"&right(Fyr,2),
						        "Fiscal Year Number", Fyr,
						        "Fiscal Year Quarter", "F" & Fqr & "-" & Fyr,
						        "Fiscal Year Quarter Number", CONVERT ( Fyr * 4 + FQrn - 1, INTEGER ),
						        "Fiscal Quarter", "F" & Fqr,
						        "Month", FORMAT ( CurrentDate, "mmm" ),
						        "Fiscal Month Number", Fmn,
						        "Fiscal Month in Quarter Number", Fqrn, -- Fmqn,
						        "Day of Week", FORMAT ( CurrentDate, "ddd" ),
						        "Day of Week Number", Wd,
						        "Day of Month Number", Mdn,
						        "Day of Fiscal Year Number", Fydn,
						        "Working Day", IF ( WorkingDay, "Working Day", "Non-Working Day" )
						    )
						)

			annotation PBI_Id = 2e06bebaf88f46979513f4af84ee0427

		table LocalDateTable_b94575be-bcbb-4510-a5ed-a6c6575effc8
			isHidden
			showAsVariationsOnly
			lineageTag: ac84d783-c549-40c0-94e6-c1e7eee5d100

			column Date
				dataType: dateTime
				isHidden
				lineageTag: 11b07779-4296-4da2-a786-b6ff5a9f9694
				dataCategory: PaddedDateTableDates
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = User

			column Year = YEAR([Date])
				dataType: int64
				isHidden
				lineageTag: f6264487-d545-4fb3-b8ea-459d7f4c86fe
				dataCategory: Years
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Year

			column MonthNo = MONTH([Date])
				dataType: int64
				isHidden
				lineageTag: 2f961f66-3bc3-416e-bdfb-ffa09cc69208
				dataCategory: MonthOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = MonthNumber

			column Month = FORMAT([Date], "MMMM")
				dataType: string
				isHidden
				lineageTag: fb8619b0-61e0-4c52-8b45-5544faa6981e
				dataCategory: Months
				summarizeBy: none
				sortByColumn: MonthNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Month

			column QuarterNo = INT(([MonthNo] + 2) / 3)
				dataType: int64
				isHidden
				lineageTag: f9787014-4bff-4898-ac1b-d1ca10dc9974
				dataCategory: QuarterOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = QuarterNumber

			column Quarter = "Qtr " & [QuarterNo]
				dataType: string
				isHidden
				lineageTag: 37a74cb9-ad2e-4acd-be23-8813432488a7
				dataCategory: Quarters
				summarizeBy: none
				sortByColumn: QuarterNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Quarter

			column Day = DAY([Date])
				dataType: int64
				isHidden
				lineageTag: 370b6745-bd0d-43b1-bf29-9bf25be82f72
				dataCategory: DayOfMonth
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Day

			hierarchy 'Date Hierarchy'
				lineageTag: a366a356-b867-43b5-a752-00bc3794f5c2

				level Year
					lineageTag: 75499460-7c62-44b0-b8bb-e29c14eaaf89
					column: Year

				level Quarter
					lineageTag: 592d8c80-acf7-4cc2-9737-124177f0d7aa
					column: Quarter

				level Month
					lineageTag: 0babca90-a8b1-471d-bad0-07ad5dacc5f7
					column: Month

				level Day
					lineageTag: 03cf900c-789c-40be-af89-3764c1ac40a8
					column: Day

				annotation TemplateId = DateHierarchy

			partition LocalDateTable_b94575be-bcbb-4510-a5ed-a6c6575effc8 = calculated
				mode: import
				source = Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))

			annotation __PBI_LocalDateTable = true

		table ArticleMaster
			lineageTag: 65f379ee-ccbe-4901-903d-565769e02054

			column 'Article No'
				dataType: string
				lineageTag: 4154b4f6-e06a-47f4-9134-eb2c13160e20
				summarizeBy: none
				sourceColumn: Article No

				annotation SummarizationSetBy = Automatic

			column 'Section Name'
				dataType: string
				lineageTag: 3306869f-2e96-4444-af1c-7588e48b7031
				summarizeBy: none
				sourceColumn: Section Name

				annotation SummarizationSetBy = Automatic

			column 'Article Name'
				dataType: string
				lineageTag: a56cf069-7fa6-473b-8b8a-29ef99672296
				summarizeBy: none
				sourceColumn: Article Name

				annotation SummarizationSetBy = Automatic

			column Gender
				dataType: string
				lineageTag: d70b66a1-5b88-4031-8479-fcd25996d0ed
				summarizeBy: none
				sourceColumn: Gender

				annotation SummarizationSetBy = Automatic

			column 'Brand Name'
				dataType: string
				lineageTag: cf0c2a53-84b5-41c8-8ae8-77ef3bab27e3
				summarizeBy: none
				sourceColumn: Brand Name

				annotation SummarizationSetBy = Automatic

			column 'SKU RSP'
				dataType: int64
				formatString: 0
				lineageTag: fedffcfc-7ca5-4c1a-8f0d-4c317985d3af
				summarizeBy: sum
				sourceColumn: SKU RSP

				annotation SummarizationSetBy = Automatic

			column Uid
				dataType: string
				lineageTag: 1d358e1e-15e3-4eb4-9a82-4a4040c1e9c2
				summarizeBy: none
				sourceColumn: Uid

				annotation SummarizationSetBy = Automatic

			column UPC
				dataType: string
				lineageTag: 83b425a5-d8d8-4ca6-b439-842f7467affb
				summarizeBy: none
				sourceColumn: UPC

				annotation SummarizationSetBy = Automatic

			column 'Size Name'
				dataType: string
				lineageTag: 770a25cf-4641-4ec2-88da-0801199634ef
				summarizeBy: none
				sourceColumn: Size Name

				annotation SummarizationSetBy = Automatic

			column 'Article with Name' = ArticleMaster[Article No] & UNICHAR(10) & ArticleMaster[Article Name]
				lineageTag: 942f4e08-9755-44fc-ba1d-01b53b37c01d
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column sizewithlabel = "Size : " & ArticleMaster[Size Name]
				lineageTag: dc03bd14-eac5-4fd4-b4c2-8a9812d17051
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column 'Season Name'
				dataType: string
				lineageTag: 9ca67211-7d09-437d-9e4a-9de769320099
				summarizeBy: none
				sourceColumn: Season Name

				annotation SummarizationSetBy = Automatic

			column Season2
				dataType: string
				lineageTag: c5d19931-2712-4749-93e9-30d033804a14
				summarizeBy: none
				sourceColumn: Season2

				annotation SummarizationSetBy = Automatic

			column sizesetid = ```
					
					    ArticleMaster[Size Name] & "-" &
					    ArticleMaster[Brand Name] & "-" &
					    ArticleMaster[Section Name] & "-" &
					    ArticleMaster[Gender]
					
					```
				lineageTag: f0f59696-6d59-4c50-b3eb-fe5c686a99f8
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column sizeSet = RELATED('Size Set'[Status])
				lineageTag: 86cb2c18-8fae-4de2-8b1e-5f5de914e5a0
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			partition ArticleMaster = m
				mode: import
				source =
						let
						    Source = Table.Combine({UniqueARticleOBS, UniqueARticleInOut}),
						    #"Inserted Merged Column" = Table.AddColumn(Source, "Uid", each Text.Combine({[UPC], Text.From([SKU RSP], "en-US")}, ""), type text),
						    #"Removed Duplicates" = Table.Distinct(#"Inserted Merged Column"),
						    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each [Brand Name] = "Columbia" or [Brand Name] = "NIKE" or [Brand Name] = "PRO CARE" or [Brand Name] = "SKECHERS" or [Brand Name] = "SWISS MILITARY" or [Brand Name] = "TIMEX" or [Brand Name] = "ADIDAS" or [Brand Name] = "JUST CORSECA" or [Brand Name] = "ASICS" or [Brand Name] = "LACE UP" or [Brand Name] = "PUMA" or [Brand Name] = "CROCS" or [Brand Name] = "LOW TOP" or [Brand Name] = "SLIP INS" or [Brand Name] = "HIGH TOP"),
						    #"Removed Duplicates1" = Table.Distinct(#"Filtered Rows", {"Uid"}),
						    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Duplicates1",{{"Section Name", Text.Proper, type text}, {"Gender", Text.Proper, type text}, {"Brand Name", Text.Proper, type text}, {"Article Name", Text.Proper, type text}}),
						    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","NA","N/A",Replacer.ReplaceText,{"Season Name"}),
						    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","NA","N/A",Replacer.ReplaceText,{"Season2"})
						in
						    #"Replaced Value1"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table All_Measures
			lineageTag: 1aa2f049-b6eb-4837-83a9-cb657817157c

			measure Age = ```
					
					var _opening = IF([Openingconfirmation] = 0 ,[Opening],0)
					var _closing = [Closing]
					var ifclosingzero = IF([Closing] = 0, [Purchase], CALCULATE([Purchase], 'INWARD & OUTWARD'[Islatestdate] = TRUE()))
					var _purchasenOpening = ifclosingzero + _opening
					var _purchaseproduct = [PurchaseforWA]
					var _sale = [Sale]
					
					
					var _lasttransactiondate = IF(_closing = 0 && _sale <> 0,
					                                    [MaxSaleDate], TODAY())
					
					
					var _daydiff  = IF(HASONEVALUE('Calendar'[Date]), BLANK(),
					                        IF(_purchaseproduct + _opening <> BLANK(),
					                            _lasttransactiondate - ROUND(DIVIDE(_purchaseproduct, _purchasenOpening), 0)))
					
					
					var _age = IF(_closing = 0 && _sale = 0 , BLANK(), INT(_daydiff))
					
					RETURN    
					IF(HASONEVALUE(LocationMaster[Code]), _age)
					
					```
				displayFolder: StockTurnCalcuation
				lineageTag: d391bec7-30e4-4e4c-bf33-06f34a210ef6

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure Opening = SUM(OBS_sheet[OBS Qty])
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: 6bfe6fee-e418-4302-962b-5d45cc54fb07

			measure Purchase = ```
					
					VAR _LocTable = VALUES( LocationMaster[Code] )  -- visible locations in the current filter context
					RETURN
					SUMX(
					    _LocTable,
					    VAR _loc = LocationMaster[Code]
					
					    VAR _LASAPurchase =
					        CALCULATE(
					            SUM('INWARD & OUTWARD'[Transaction Quantity]),
					            'INWARD & OUTWARD'[Transaction type] IN { "Group Purchase", "Party Credit Note", "Party Purchase" },
					            'INWARD & OUTWARD'[ISfresh] = TRUE(),
					            LocationMaster[Code] = _loc
					        )
					
					    VAR _BranchPurchase =
					        CALCULATE(
					            SUM('INWARD & OUTWARD'[Transaction Quantity]),
					            'INWARD & OUTWARD'[Transaction type] = "Group Purchase",
					            LocationMaster[Code] = _loc
					        )
					
					    VAR _ThisLocationPurchase = IF( _loc IN { "LA", "SA" }, _LASAPurchase, _BranchPurchase )
					
					    RETURN _ThisLocationPurchase
					)
					
					```
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: f4da384c-bd1b-444f-866c-6cb340cead2d

			measure Ageslicer = ```
					
					
					VAR _ignoreblank =
					    CALCULATE(
					        [Age],
					        REMOVEFILTERS('Calendar')
					    )
					VAR _param = AgeParameter[AgeParameter Value]
					
					var _min = MIN(AgeParameter[AgeParameter])
					var _max = MAX(AgeParameter[AgeParameter])
					RETURN
					    SWITCH(
					        TRUE(),
					        // _param = 0, 1,   --Remark- if slicer = 0, keep everything (no filter)
					        // ISBLANK(_ignoreblank), 0,  --Remkar- blank % should be excluded when slicer > 0
					        // (_ignoreblank) > _param, 1,
					        _ignoreblank >= _min && _ignoreblank <= _max, 1, 
					        0
					
					)
					```
				formatString: 0
				displayFolder: Slicers
				lineageTag: 3ef979a1-a40b-491b-9e6e-f5fbb6a1819d

			measure Sale = ```
					
					
					-- LA, SA Rule 
					        --Tranction type = "Party Wholesale"
					
					-- Bramch Rule- Tranction type = {"Party Wholesale", "Retail Sales"}
					
					
					var _LASASale = CALCULATE(SUM('INWARD & OUTWARD'[Transaction Quantity]),
					                    TransactionType[type] in {"Party Wholesale"})  
					
					
					var _BranchSale = CALCULATE(SUM('INWARD & OUTWARD'[Transaction Quantity]),
					                    TransactionType[type] in {"Party Wholesale", "Retail Sales"})  
					
					RETURN
					    IF(SELECTEDVALUE(LocationMaster[Code]) in {"LA", "SA"}, _LASASale, _BranchSale)
					```
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: b9d6c8cc-ab97-47a8-b62b-871af300337b

			measure Outward = ```
					
					
					-- Rule for LA, SA - Transaction Type = "Group Wholesale", "Group Wholesale"
					-- Rule For Branch - Transaction Type = {"Group Wholesale", "Delivery Challan(WSL", "Group Debitnote"}
					
					var _LASAOutward =    CALCULATE(SUM('INWARD & OUTWARD'[Transaction Quantity]), 
					                            'INWARD & OUTWARD'[Transaction type] = "Group Wholesale")
					
					
					var _BranchOutward =    CALCULATE(SUM('INWARD & OUTWARD'[Transaction Quantity]), 
					                            'INWARD & OUTWARD'[Transaction type] in {"Group Wholesale", "Delivery Challan(WSL", "Group Debitnote"})
					
					RETURN
					        IF(SELECTEDVALUE(LocationMaster[Code]) in {"LA", "SA"}, _LASAOutward, _BranchOutward)
					```
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: feb67be7-618e-4116-81cf-8584d1f6de98

			measure Closing = CALCULATE(SUM(OBS_sheet[CBS Qty]), USERELATIONSHIP('Calendar'[Date], OBS_sheet[ClosingDate]))
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: 33b7d70d-7e91-4e58-a791-8a2565828fa3

			measure PurchaseforWA = ```
					
					 var _Branchpurchaseproductifclosingzero =   CALCULATE(SUM('INWARD & OUTWARD'[sum_product]), 
					                            'INWARD & OUTWARD'[Transaction type] = "Group Purchase")
					
					 var _LASApurchaseproductifclosingzero =   CALCULATE(SUM('INWARD & OUTWARD'[sum_product]), 
					                        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"},
					                        'INWARD & OUTWARD'[ISfresh] = TRUE())
					
					 var _Branchpurchaseproductifclosingnotzero =   CALCULATE(SUM('INWARD & OUTWARD'[sum_product]), 
					                                                        'INWARD & OUTWARD'[Islatestdate] = TRUE(),
					                                                        'INWARD & OUTWARD'[Transaction type] = "Group Purchase")
					
					 var _LASApurchaseproductifclosingnotzero =   CALCULATE(SUM('INWARD & OUTWARD'[sum_product]), 
					                                                        'INWARD & OUTWARD'[Islatestdate] = TRUE(),
					                        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"},
					                        'INWARD & OUTWARD'[ISfresh] = TRUE())
					
					
					var _purchaseproductifclosingzero = IF(SELECTEDVALUE(LocationMaster[Code]) in {"LA", "SA"}, 
					                                                    _LASApurchaseproductifclosingzero, 
					                                                    _Branchpurchaseproductifclosingzero)
					
					
					var _purchaseproductifclosingnotzero = IF(SELECTEDVALUE(LocationMaster[Code]) in {"LA", "SA"}, 
					                                                    _LASApurchaseproductifclosingnotzero, 
					                                                    _Branchpurchaseproductifclosingnotzero)
					
					
					
					
					 var _openingproduct = [Opening] * DATE(2025, 4, 1)
					
					 RETURN
					    // _purchaseproduct + _openingproduct
					    IF([Closing] = 0,_purchaseproductifclosingzero,_purchaseproductifclosingnotzero)
					    + 
					    // IF([Openingconfirmation] = 0 && [Opening] <> 0, _openingproduct, 0)
					    IF([Openingconfirmation] = 0 , _openingproduct, 0)
					```
				displayFolder: StockTurnCalcuation
				lineageTag: 2b472d7e-27cd-4f39-8f30-3b6d9674929d

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure ExpectedSale = ```
					
					
					var _opening = IF([Openingconfirmation] = 0 ,[Opening],0)
					var _closing = [Closing]
					var ifclosingzero = IF([Closing] = 0, [Purchase], CALCULATE([Purchase], 'INWARD & OUTWARD'[Islatestdate] = TRUE()))
					var _purchasenOpening =ifclosingzero + _opening
					var _purchaseproduct = [PurchaseforWA]
					var _sale = [Sale]
					
					
					var _lasttransactiondate = IF(_closing = 0 && _sale <> 0,
					                                    CALCULATE([MaxSaleDate], REMOVEFILTERS(TransactionType)), TODAY())
					
					var _daydiff  = IF(HASONEVALUE('Calendar'[Date]), BLANK(),
					                        IF(_purchaseproduct + _opening <> BLANK(),
					                            _lasttransactiondate - ROUND(DIVIDE(_purchaseproduct, _purchasenOpening), 0)))
					// var _lastpurchasedate = ROUND(DIVIDE(_purchaseproduct, _purchasenOpening), 0)
					// var _purchaseafternewdate = CALCULATE([Purchase], 'Calendar'[Date] >= _lastpurchasedate)
					
					VAR _minDate = 
					    CALCULATE(MIN('INWARD & OUTWARD'[Transaction Date]),
					        FILTER('INWARD & OUTWARD',
					        'INWARD & OUTWARD'[Islatestdate] = TRUE() &&
					        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Purchase"} &&
					        'INWARD & OUTWARD'[ISfresh] = TRUE()
					    ))
					
					VAR _purchaseafternewdate =
					                    IF(HASONEVALUE('Calendar'[Date]), BLANK(),
					                        CALCULATE(
					                            [Purchase],
					                            'Calendar'[Date] >= _minDate
					                        ))
					
					
					// var _ifclosingzero = IF(_closing = 0, _purchasenOpening, _closing)
					var _ifclosingzero = IF(_closing = 0, [Purchase] + [Opening], _purchaseafternewdate + _opening)
					var _runrate = DIVIDE(_ifclosingzero, MIN('ShelfLifeParameter'[Shelf Life]))
					
					var _SaleVelocity = IF(HASONEVALUE('Calendar'[Date]), BLANK(), _runrate * _daydiff)
					
					
					RETURN
					IF(HASONEVALUE(LocationMaster[Code]), _SaleVelocity)
					// _ifclosingzero
					```
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: a692f226-f11b-466d-b92c-46c80efb2421

			measure MovementTrend = ```
					
					var _opening = IF([Openingconfirmation] = 0 ,[Opening],0)
					
					var _purchaseproduct = [PurchaseforWA]
					// var _sale =[salewithwa]
					
					VAR _minDate = 
					    CALCULATE(MIN('INWARD & OUTWARD'[Transaction Date]),
					        FILTER('INWARD & OUTWARD',
					        'INWARD & OUTWARD'[Islatestdate] = TRUE() &&
					        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Purchase"} &&
					        'INWARD & OUTWARD'[ISfresh] = TRUE()
					    ))
					
					VAR _sale =
					                    IF(HASONEVALUE('Calendar'[Date]), BLANK(),
					                        CALCULATE(
					                            [Sale],
					                            'Calendar'[Date] >= _minDate
					                        ))
					
					
					
					var _SaleVelocity = [ExpectedSale]
					
					var _movement =  IF(_purchaseproduct + _opening <> BLANK(), 
					                                            DIVIDE(_sale, _SaleVelocity))
					
					
					RETURN
					
					    _movement
					```
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: StockTurnCalcuation
				lineageTag: 0b7edd7c-af9b-4621-a0f2-7e3c8a406743

			measure Status = ```
					
					// var _opening = IF([Openingconfirmation] = 0 ,[Opening],0)
					var _closing = [Closing]
					// var _purchasenOpening = CALCULATE([Purchase], 'INWARD & OUTWARD'[Islatestdate] = TRUE()) + _opening
					// var _purchaseproduct = [PurchaseforWA]
					// var _sale = [salewithwa]
					
					VAR _minDate = 
					    CALCULATE(MIN('INWARD & OUTWARD'[Transaction Date]),
					        FILTER('INWARD & OUTWARD',
					        'INWARD & OUTWARD'[Islatestdate] = TRUE() &&
					        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Purchase"} &&
					        'INWARD & OUTWARD'[ISfresh] = TRUE()
					    ))
					
					VAR _sale =
					                    IF(HASONEVALUE('Calendar'[Date]), BLANK(),
					                        CALCULATE(
					                            [Sale],
					                            'Calendar'[Date] >= _minDate
					                        ))
					
					
					var _SaleVelocity = [ExpectedSale]
					
					// 0%	0-20%	Super Slow
					// 21%	21-40%	Slow
					// 41%	41-60%	Medium
					// 61%	61-80%	Fast
					// 81%	81%-100%	Super Fast
					
					// var _status = IF(_purchaseproduct + _opening <> BLANK(), 
					//             SWITCH(TRUE(),
					//                     DIVIDE(_sale, _SaleVelocity) > 0.8, "Super Fast",
					//                     DIVIDE(_sale, _SaleVelocity) > 0.6, "Fast",
					//                     DIVIDE(_sale, _SaleVelocity) > 0.4, "Medium",
					//                     DIVIDE(_sale, _SaleVelocity) > 0.2, "Slow",
					//                     DIVIDE(_sale, _SaleVelocity) > 0, "Super Slow",
					//                     DIVIDE(_sale, _SaleVelocity) = 0 
					//                     && 
					//                     not HASONEVALUE('Calendar'[Date])
					//                     && _closing <> 0, "Dead"
					//                     ))
					
					RETURN
					// _status 
					    IF(HASONEVALUE(LocationMaster[Code]),
					            SWITCH(TRUE(),
					                    DIVIDE(_sale, _SaleVelocity) > 0.8, "Super Fast",
					                    DIVIDE(_sale, _SaleVelocity) > 0.6, "Fast",
					                    DIVIDE(_sale, _SaleVelocity) > 0.4, "Medium",
					                    DIVIDE(_sale, _SaleVelocity) > 0.2, "Slow",
					                    DIVIDE(_sale, _SaleVelocity) > 0, "Super Slow",
					                    DIVIDE(_sale, _SaleVelocity) = 0 
					                    && 
					                    not HASONEVALUE('Calendar'[Date])
					                    && _closing <> 0, "Dead"
					                    ))
					```
				displayFolder: StockTurnCalcuation
				lineageTag: 392aeb62-4756-4f56-829f-0c6020c3c24c

			measure Salethrough = ```
					
					var _opening = [Opening]
					var _closing = [Closing]
					var _purchasenOpening = [Purchase] + _opening
					var _purchaseproduct = [PurchaseforWA]
					var _sale = [Sale]
					
					
					var _salethrough = IF(HASONEVALUE('Calendar'[Date]), BLANK(),
					                        IF(_purchaseproduct + _opening <> BLANK(),
					                            DIVIDE(_sale,  _purchasenOpening)))
					
					
					RETURN
					_salethrough
					
					```
				formatString: 0.00%;-0.00%;0.00%
				displayFolder: StockTurnCalcuation
				lineageTag: 364bc75a-cc24-4607-8252-39d7820f265f

			measure MaxSaleDate = ```
					
					CALCULATE(MAX('INWARD & OUTWARD'[MaxSaleDate]),
					                    'INWARD & OUTWARD'[Transaction type] in {"Party Wholesale", "Retail Sales"})  
					```
				formatString: General Date
				displayFolder: StockTurnCalcuation
				lineageTag: 3b2a2b85-9df2-4c21-9505-3886dc92b3be

			measure Salevelocity_slicer =
					
					
					var _ignoreblank = CALCULATE(
					    [ExpectedSale],
					    REMOVEFILTERS('Calendar')
					)
					
					var _min = MIN(SaleVelocityparameter[SaleVelocityparameter])
					var _max = MAX(SaleVelocityparameter[SaleVelocityparameter])
					
					RETURN
					
					IF(
					    // _ignoreblank > SaleVelocityparameter[SaleVelocityparameter Value],
					    _ignoreblank >= _min && _ignoreblank <= _max,
					    1
					)
				formatString: 0
				displayFolder: Slicers
				lineageTag: a1a518e4-5d16-4621-82e1-3b6d47795b3f

			measure SaleThorughslicer = ```
					
					
					VAR _ignoreblank =
					    CALCULATE(
					        [Salethrough],
					        REMOVEFILTERS('Calendar')
					    )
					VAR _param = SaleThroughParameter[SaleThroughParameter Value]
					var _min = MIN(SaleThroughParameter[SaleThroughParameter])
					var _max = MAX(SaleThroughParameter[SaleThroughParameter])
					RETURN
					    SWITCH(
					        TRUE(),
					        // _param = 0, 1,   --Remark- if slicer = 0, keep everything (no filter)
					        // ISBLANK(_ignoreblank), 0,  --Remkar- blank % should be excluded when slicer > 0
					        // (_ignoreblank * 100) > _param, 1,
					        (_ignoreblank * 100) >= _min && (_ignoreblank * 100) <= _max, 1,
					        0
					    )
					
					
					```
				formatString: 0
				displayFolder: Slicers
				lineageTag: f165bc42-768f-4d0a-8eaf-e7f79ec55066

			measure movementslicer = ```
					
					
					VAR _ignoreblank =
					    CALCULATE(
					        [MovementTrend],
					        REMOVEFILTERS('Calendar')
					    )
					VAR _param = MovementParameter[MovementParameter Value]
					var _min = MIN(MovementParameter[MovementParameter])
					var _max = MAX(MovementParameter[MovementParameter])
					RETURN
					    SWITCH(
					        TRUE(),
					        // _param = 0, 1,   --Remark- if slicer = 0, keep everything (no filter)
					        // ISBLANK(_ignoreblank), 0,  --Remkar- blank % should be excluded when slicer > 0
					        // (_ignoreblank * 100) > _param, 1,
					        (_ignoreblank * 100) >= _min && (_ignoreblank * 100) <= _max,1,
					        0
					    )
					
					
					```
				formatString: 0
				displayFolder: Slicers
				lineageTag: ecfeafc3-0349-4fa1-8581-799450105a98

			measure closingwithGT% =
					
					var _closing = CALCULATE([Closing], REMOVEFILTERS(LocationMaster[Code]), not LocationMaster[Code]  in {"LA","SA","HP","LS"})
					RETURN
					 [Closing] & " (" & FORMAT(DIVIDE([Closing], _closing), "0%") & ")"
				displayFolder: StockTurnCalcuation
				lineageTag: ff52f7d1-0710-4248-924a-6a629a0b3b7f

			measure 'Mrp Value' = CALCULATE(SUM(OBS_sheet[MRPValue]), USERELATIONSHIP('Calendar'[Date], OBS_sheet[ClosingDate]))
				formatString: #,0
				displayFolder: StockTurnCalcuation
				lineageTag: 3f26ff20-aff0-4ca4-9a8e-5bee5d47f307

			measure closingwithpercent =
					
					var _closing = CALCULATE([Closing], REMOVEFILTERS(ArticleMaster[sizewithlabel]))
					RETURN
					    "Qty : " & [Closing] & " (" & FORMAT(DIVIDE([Closing], _closing), "0%") &")"
				displayFolder: StockTurnCalcuation
				lineageTag: ca638a26-344e-4f89-8ec1-1977685617aa

			measure TitlewithtotalInventory = ```
					
					         "On Hand Inventory " &  FORMAT([Closing], "#,##,##0") & " of MRP Value " & " " & FORMAT([Mrp Value] , "#,##,##0")
					```
				displayFolder: StockTurnCalcuation
				lineageTag: 60ac4c53-00aa-4f32-ab89-f194db62c86e

			measure latestOBS = ```
					
					var Min_OBS = format(MIN(OBS_sheet[OpeningDate]),"dd-mm-yyyy")
					var Max_OBS = format(max('INWARD & OUTWARD'[Transaction Date]),"dd-mm-yyyy")
					
					
					RETURN
					
					"OBS : " &  Min_OBS & " "& "to" & " " & Max_OBS 
					
					```
				displayFolder: StockTurnCalcuation
				lineageTag: 76892944-8ed0-4fbf-bb0b-98c41543d54d

			measure LatestInOut = ```
					
					var Min_Inout = format(MIN('INWARD & OUTWARD'[Transaction Date]),"dd-mm-yyyy")
					var Max_Inout = format(Max('INWARD & OUTWARD'[Transaction Date]),"dd-mm-yyyy")
					
					RETURN
					 " Inward Outward : " & Min_Inout & " " & "to" & " " & Max_Inout
					 
					```
				displayFolder: StockTurnCalcuation
				lineageTag: 4625889b-786b-407f-a656-d761c297e634

			measure Openingconfirmation = ```
					
					
					var _Branch = CALCULATE(COUNT('INWARD & OUTWARD'[diff]), 
					                                                'INWARD & OUTWARD'[diff] >= 0,
					                                                'INWARD & OUTWARD'[Transaction type] = "Group Purchase")
					
					var _LASA = CALCULATE(COUNT('INWARD & OUTWARD'[diff]), 
					                                'INWARD & OUTWARD'[diff] >= 0,
					                                'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"},
					                                'INWARD & OUTWARD'[ISfresh] = TRUE())
					
					RETURN
					    IF(SELECTEDVALUE(LocationMaster[Code]) in {"LA", "SA"}, _LASA, _Branch)
					```
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: f9cb85a1-9251-4a17-9a6c-7835543e6ebd

			measure salewithwa =
					
					
					var _opening = IF([Openingconfirmation] = 0 ,[Opening],0)
					// var _closing = [Closing]
					var ifclosingzero = IF([Closing] = 0, [Purchase], CALCULATE([Purchase], 'INWARD & OUTWARD'[Islatestdate] = TRUE()))
					var _purchasenOpening = ifclosingzero + _opening
					var _purchaseproduct = [PurchaseforWA]
					var _sale = CALCULATE([Sale], FILTER('INWARD & OUTWARD', 'INWARD & OUTWARD'[Transaction Date] >= DIVIDE(_purchaseproduct, _purchasenOpening)))
					
					RETURN
					    _sale
				formatString: 0
				displayFolder: StockTurnCalcuation
				lineageTag: 597347ea-190e-429f-bed0-33e1722779d8

			measure statusslicer = ```
					
					  VAR _ignoreblank =
					    CALCULATE(
					        [Status],
					        REMOVEFILTERS('Calendar')
					    )
					VAR _param = VALUES('Status filter'[Status])
					
					
					RETURN
					    SWITCH(
					        TRUE(),
					_ignoreblank = BLANK() && COUNT('Status filter'[Status]) = 6 , 1,        
					_ignoreblank in _param , 1,
					        0
					)
					
					```
				formatString: 0
				displayFolder: Slicers
				lineageTag: a21cf509-7324-4024-b4fa-05b85e3008c0

			measure Size_values = ```
					
					  SWITCH(TRUE(),
					         SELECTEDVALUE(SizeMaster[Size Name]) = "Age", [Age],
					         SELECTEDVALUE(SizeMaster[Size Name]) = "MRP Value", [Mrp Value],
					         SELECTEDVALUE(SizeMaster[Size Name]) = "Status", IF([Closing] <> 0 && SELECTEDVALUE(LocationMaster[Code]) in 
					                                            {"HP", "LS"}, "NA", [status]),
					        SELECTEDVALUE(SizeMaster[Size Name]) = "Size Set", [CutsizeOrFullsize],
					        CALCULATE([Closing], USERELATIONSHIP(SizeMaster[Size Name], ArticleMaster[Size Name])))
					```
				formatString: #,0
				lineageTag: e33fcf48-1f23-49b6-a4d7-40bdbb1072f8

				annotation PBI_FormatHint = {"isDecimal":true}

			measure salethroughcolor = ```
					
					    SWITCH(TRUE(),
					                    [Salethrough] > 0.8, "#148030", -- Green
					                    [Salethrough] > 0.6, "#48BC66", -- Green
					                    [Salethrough] > 0.4, "#90903A", --Yellow
					                    [Salethrough] > 0.2, "#D93642", -- Red
					                    [Salethrough] > 0, "#A70511", -- Red
					                    [Salethrough] = 0, "#F28088" -- Red
					                    )
					```
				lineageTag: 3423d4b9-efc5-4960-b37c-813bb78bde8a

			measure Firstin_Date = ```
					
					
					var _FirstPurchasedateBranch = CALCULATE(MIN('INWARD & OUTWARD'[Transaction Date]),
					                                                         'INWARD & OUTWARD'[Transaction type] = "Group Purchase")
					
					var _FirstPurchasedateLASA = CALCULATE(MIN('INWARD & OUTWARD'[Transaction Date]),
					                        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"},
					                        'INWARD & OUTWARD'[ISfresh] = TRUE())
					
					var  _FirstPurchasedate =  IF(SELECTEDVALUE(LocationMaster[Code]) in {"LA", "SA"},
					                                            _FirstPurchasedateLASA, _FirstPurchasedateBranch)
					
					VAR _Firstinvdate = IF(_FirstPurchasedate = BLANK() && [Opening] <> 0, 
					                                        DATE(2025,4,1) , _FirstPurchasedate)                                                     
					RETURN
					IF(HASONEVALUE(LocationMaster[Code]),
					    _Firstinvdate)
					```
				formatString: General Date
				lineageTag: e2ab1a1e-da97-4599-a511-d7dd102b34ac

			measure Lastin_Date = ```
					
					
					var _LastPurchasedateBranch = CALCULATE(max('INWARD & OUTWARD'[Transaction Date]),
					                                                         'INWARD & OUTWARD'[Transaction type] = "Group Purchase")
					
					var _LastPurchasedateSALA = CALCULATE(max('INWARD & OUTWARD'[Transaction Date]),
					                        'INWARD & OUTWARD'[Transaction type] in {"Group Purchase", "Party Credit Note", "Party Purchase"},
					                        'INWARD & OUTWARD'[ISfresh] = TRUE())
					
					var  _LastPurchasedate =  IF(SELECTEDVALUE(LocationMaster[Code]) in {"LA", "SA"},
					                                            _LastPurchasedateSALA, _LastPurchasedateBranch)
					                                                         
					
					VAR _Lastinvdate = IF(_LastPurchasedate = BLANK() && [Opening] <> 0, 
					                                        DATE(2025,4,1) , _LastPurchasedate)                                                     
					RETURN
					IF(HASONEVALUE(LocationMaster[Code]),
					    _Lastinvdate)
					```
				formatString: General Date
				lineageTag: ccf3628d-8f9a-44c7-8543-eb34fe7ee0f3

			measure 'Sale Avg' =
					
					var _shelfdays = SELECTEDVALUE(ShelfLifeParameter[Shelf Life])
					var _setdate = TODAY() - _shelfdays
					var _refrencedate = IF(_setdate < [Firstin_Date], [Firstin_Date], _setdate)
					var _Sale = CALCULATE([Sale], 'Calendar'[Date] >= _refrencedate)
					var _daysofcalculation = DATEDIFF(_refrencedate,TODAY(), DAY)
					var _saleavg = DIVIDE(_Sale, _daysofcalculation) * _shelfdays
					RETURN
					
					   _saleavg
					    // CALCULATE([Sale], 'Calendar'[Date] >= _refrencedate)
				formatString: 0.00
				lineageTag: ccfeb5d5-ff79-41af-aeb2-10e04cdfec6a

			measure selectedcode = SELECTEDVALUE(LocationMaster[Code]) & " || " & SELECTEDVALUE(LocationMaster[LocationName])
				lineageTag: df0fc337-9e21-4b54-be96-d6f96ed5cdbe

			measure suggestionRefill = ```
					
					   IF([Closing] < [Sale Avg], ROUND([Sale Avg] - [Closing], 0))
					```
				lineageTag: df64fee0-0fa4-407d-97a4-5d5edccefdd8

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure suggestionResuffle = ```
					
					   IF([Closing] > [Sale Avg], ROUND([Closing] - [Sale Avg], 0))
					```
				lineageTag: 62dcfffa-2663-4477-8b88-d7d6a5eaea6e

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure suggestionrecal = [Closing]
				formatString: 0
				lineageTag: 9d7506bb-0376-4e16-8af9-33f6d7742f28

			measure statusConditional = ```
					
					    CALCULATE([Status], ArticleMaster[Article No] = SELECTEDVALUE(ArticleMaster[Article No]))
					```
				lineageTag: 931e164e-7b0d-4119-b802-34d12964377c

			measure RefilFromSuggetion = ```
					
					
					// var _allLocation = 
					//         CONCATENATEX(
					//             FILTER(
					//                 ALL(LocationMaster[Code]),
					//                 not [Status] IN {"Fast", "Super Fast", "Medium", BLANK()} && [Closing] > 0
					//             ),
					//             LocationMaster[Code] & ": " & [Status] & ": " & [Closing],
					//             ", "
					//         )
					
					var _superslow = 
					        CONCATENATEX(
					            FILTER(
					                ALL(LocationMaster[Code]),
					                [Status] = "Super Slow" && [Closing] > 0 &&
					                LocationMaster[Code] <> SELECTEDVALUE(LocationMaster[Code])
					            ),
					            LocationMaster[Code] & ": " & [Status] & " from  " & [Age] & " days",
					            UNICHAR(10)
					        )
					
					var _slow = 
					        CONCATENATEX(
					            FILTER(
					                ALL(LocationMaster[Code]),
					                [Status] = "Slow" && [Closing] > 0 &&
					                LocationMaster[Code] <> SELECTEDVALUE(LocationMaster[Code])
					            ),
					            LocationMaster[Code] & ": " & [Status] & " from " & [Age] & " days",
					            UNICHAR(10)
					        )
					
					
					
					var _dead = 
					        CONCATENATEX(
					            FILTER(
					                ALL(LocationMaster[Code]),
					                [Status] = "Dead" && [Closing] > 0 &&
					                LocationMaster[Code] <> SELECTEDVALUE(LocationMaster[Code])
					            ),
					            LocationMaster[Code] & ": " & [Status] & " from " & [Age] & " days",
					            UNICHAR(10)
					        )
					
					var _medium = 
					        CONCATENATEX(
					            FILTER(
					                ALL(LocationMaster[Code]),
					                [Status] = "Medium" && [Closing] > 0 &&
					                LocationMaster[Code] <> SELECTEDVALUE(LocationMaster[Code])
					            ),
					            LocationMaster[Code] & ": " & [Status] & " from " & [Age] & " days",
					            UNICHAR(10)
					        )
					
					RETURN 
					IF(ISINSCOPE(LocationMaster[Code]),
					   SWITCH(TRUE(),
					            [Status] = "Super Fast", COALESCE(_superslow, _slow, _medium, _dead),
					            [Status] = "Fast", COALESCE(_slow, _medium, _dead),
					            [Status] = "Medium" , COALESCE(_medium, _dead)
					            ))
					   
					
					
					```
				lineageTag: a2e5b2b7-6f9d-4836-bf47-94bbc1522c09
				dataCategory: Uncategorized

			measure ReshuffletoSuggetion = ```
					
					
					// var _allLocation = 
					//         CONCATENATEX(
					//             FILTER(
					//                 ALL(LocationMaster[Code]),
					//                 not [Status] IN {"Fast", "Super Fast", "Medium", BLANK()} && [Closing] > 0
					//             ),
					//             LocationMaster[Code] & ": " & [Status] & ": " & [Closing],
					//             ", "
					//         )
					
					var _superfast = 
					        CONCATENATEX(
					            FILTER(
					                ALL(LocationMaster[Code]),
					                [Status] = "Super Fast"  &&
					                LocationMaster[Code] <> SELECTEDVALUE(LocationMaster[Code])
					            ),
					            LocationMaster[Code] & ": " & [Status] 
					            & " with Salethrough " & FORMAT([Salethrough], "0.00%"),
					            UNICHAR(10)
					        )
					
					var _fast = 
					        CONCATENATEX(
					            FILTER(
					                ALL(LocationMaster[Code]),
					                [Status] = "Fast"  &&
					                LocationMaster[Code] <> SELECTEDVALUE(LocationMaster[Code])
					            ),
					            LocationMaster[Code] & ": " & [Status] 
					            & " with Salethrough " & FORMAT([Salethrough], "0.00%"),
					            UNICHAR(10)
					        )
					
					
					
					
					var _medium = 
					        CONCATENATEX(
					            FILTER(
					                ALL(LocationMaster[Code]),
					                [Status] = "Medium"  &&
					                LocationMaster[Code] <> SELECTEDVALUE(LocationMaster[Code])
					            ),
					            LocationMaster[Code] & ": " & [Status] 
					            & " with Salethrough " & FORMAT([Salethrough], "0.00%"),
					            UNICHAR(10)
					        )
					
					RETURN 
					IF(ISINSCOPE(LocationMaster[Code]),
					   SWITCH(TRUE(),
					            [Status] = "Super slow" || [Status] = "Dead" , COALESCE(_superfast, _fast, _medium),
					            [Status] = "Slow", COALESCE(_fast,_superfast, _medium)
					            ))
					   
					
					
					```
				lineageTag: 0b4efef9-660e-45ca-a0cd-53def7e1ddc5

			measure test = ```
					
					CONCATENATEX(
					    FILTER(
					        ALL(SizeMaster[Size Name]),
					        [Closing] > 0
					    ),
					    SizeMaster[Size Name] & ": " & IF([Closing] > 0, "Avl"),
					    ", ",
					    SizeMaster[Size Name],
					    ASC
					)
					
					```
				lineageTag: e8a895b5-cf84-4709-95b1-b2cadec2137c

			measure CutsizeOrFullsize = ```
					
					
					var _sizesetcount = CALCULATE(COUNT('Size Set'[Size]), 
					                                    'Size Set'[Brand] = SELECTEDVALUE(ArticleMaster[Brand Name]),
					                                    'Size Set'[Gender] = SELECTEDVALUE(ArticleMaster[Gender]),
					                                    'Size Set'[Section Name] = SELECTEDVALUE(ArticleMaster[Section Name]),
					                                    'Size Set'[Status] = "Avl")
					
					var _countgreaterzero = CALCULATE(
					                                COUNTROWS(
					                                    FILTER(
					                                        SUMMARIZE(
					                                            'Size Set',
					                                            'Size Set'[Size]
					                                        ),
					                                        [Closing]  > 0
					                                    )
					                                ), 'Size Set'[Status] = "Avl" )
					RETURN 
					// _sizesetcount
					IF([Closing] > 0, 
					IF(_sizesetcount > _countgreaterzero, "Cut Size", "Full Size"))
					```
				lineageTag: 801e5058-3d90-4d14-bbe8-5d07c7c1ea96

			measure SizeSetSlicer = ```
					
					  VAR _ignoreblank = [CutsizeOrFullsize]
					    // CALCULATE(
					    //     [CutsizeOrFullsize],
					    //     REMOVEFILTERS(LocationMaster[Code])
					    // )
					VAR _param = VALUES(SizeSetFilter[Size-Set])
					
					
					RETURN
					    SWITCH(
					        TRUE(),
					_ignoreblank = BLANK() && COUNT(SizeSetFilter[Size-Set]) = 2 , 1,        
					_ignoreblank in _param , 1,
					        0
					)
					
					```
				formatString: 0
				lineageTag: 0a94c91d-8195-4090-adf5-58af0460c8bf

			partition All_Measures = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
						    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
						in
						    #"Removed Columns"

			annotation PBI_ResultType = Table

		table ShelfLifeParameter
			lineageTag: 31e77d62-defe-4172-bc44-2658ca29624c

			measure 'Shelf Life Value' = SELECTEDVALUE('ShelfLifeParameter'[Shelf Life], 90)
				formatString: 0
				lineageTag: 80acbd6f-913e-4c65-b573-a8c0d22d00ce

			column 'Shelf Life'
				formatString: 0
				lineageTag: 7279a8d9-072f-4881-a8b1-a0b0cd47a704
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata = {"version":0}

				annotation SummarizationSetBy = User

			partition ShelfLifeParameter = calculated
				mode: import
				source = GENERATESERIES(1, 100, 1)

			annotation PBI_Id = 7120ba1b2054426b83fa56bbd2b64aff

		table TransactionType
			lineageTag: d6f59e96-bb8e-4f87-9d67-a296b40e5219

			column type
				dataType: string
				lineageTag: 95b0492e-ed88-4ba0-9c8b-94bcdd839f4d
				summarizeBy: none
				sourceColumn: type
				sortByColumn: id

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column id
				dataType: int64
				formatString: 0
				lineageTag: 377dfc67-24c2-4731-b1cb-96a26f9d2198
				summarizeBy: none
				sourceColumn: id

				annotation SummarizationSetBy = Automatic

			column Group
				dataType: string
				lineageTag: 3706a10a-dfbc-492e-919a-d73671dfc891
				summarizeBy: none
				sourceColumn: Group
				sortByColumn: idGroup

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column idGroup
				dataType: int64
				formatString: 0
				lineageTag: 6bb941da-95fb-4f3d-bac2-e54037f3560d
				summarizeBy: none
				sourceColumn: idGroup

				annotation SummarizationSetBy = Automatic

			partition TransactionType = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZFNb8IwDIb/SpXTDhzW8VE4TkXaZQi0TuNQccjAaiJlCUpSpv77xQ2k7sYOluzHr5zXcV2zNSh5AdtlpeBKcf2wr17ZhBUhtq3/5vYUshk7TGr2Yk17zkoLJ+m18RAayxB38Jzo1/CZ+OLfqbvWHgV3KHpKM0dw0O6FUeC4ii/9nbjj1ndjQ6sQd/CC6KnP/DHpKS6InHjL86QmdEnE1PEsRBXTaS95A8+lypC5Hv7qb8+gpW7wIVyWVNgtlXHXGj9uKFd9GydlH6DMUfoORbfnRzCOegfnQ4W7pxT5c9NvicauaeQbc4Ev0CjM8Q60jveqPPctLpXj5YdqOnjzIty0EUiLmzXCwkUPPw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"type" = _t, id = _t, Group = _t, idGroup = _t]),
						    #"Changed Type1" = Table.TransformColumnTypes(Source,{{"id", Int64.Type}, {"idGroup", Int64.Type}})
						in
						    #"Changed Type1"

			annotation PBI_ResultType = Table

			annotation PBI_NavigationStepName = Navigation

		table LocalDateTable_7edc6a93-bd7e-45f9-aef3-05d82ebd2a2f
			isHidden
			showAsVariationsOnly
			lineageTag: c3ff906b-d6bf-4dbb-b096-4aa8d12f5cff

			column Date
				dataType: dateTime
				isHidden
				lineageTag: 355e6ae2-c7a5-48ed-9ce6-125580a0c9d2
				dataCategory: PaddedDateTableDates
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = User

			column Year = YEAR([Date])
				dataType: int64
				isHidden
				lineageTag: b7f2e741-ee5c-471b-a4a1-9dc8021a88ed
				dataCategory: Years
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Year

			column MonthNo = MONTH([Date])
				dataType: int64
				isHidden
				lineageTag: 6ae11b0d-fdcc-4bb9-a75b-edf575c057a0
				dataCategory: MonthOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = MonthNumber

			column Month = FORMAT([Date], "MMMM")
				dataType: string
				isHidden
				lineageTag: f3e6cf05-2123-4d93-9599-ab9b445cc336
				dataCategory: Months
				summarizeBy: none
				sortByColumn: MonthNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Month

			column QuarterNo = INT(([MonthNo] + 2) / 3)
				dataType: int64
				isHidden
				lineageTag: fa136e68-1bd1-4a58-81e0-65721b454848
				dataCategory: QuarterOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = QuarterNumber

			column Quarter = "Qtr " & [QuarterNo]
				dataType: string
				isHidden
				lineageTag: cc30edbb-a59c-4b58-8afe-24457248ab06
				dataCategory: Quarters
				summarizeBy: none
				sortByColumn: QuarterNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Quarter

			column Day = DAY([Date])
				dataType: int64
				isHidden
				lineageTag: 3a3bc55a-62d9-48e7-a010-78474d90dba1
				dataCategory: DayOfMonth
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Day

			hierarchy 'Date Hierarchy'
				lineageTag: db3f494d-dc4d-4307-9a84-fa94ccf95c49

				level Year
					lineageTag: 35aa74b5-03e7-4e13-9619-b701a31080ca
					column: Year

				level Quarter
					lineageTag: 3ef134f3-11b5-4e2b-a275-2735380ca99a
					column: Quarter

				level Month
					lineageTag: 47c16a48-131f-4704-b779-5f9577bc40b9
					column: Month

				level Day
					lineageTag: b08caf19-9a33-41d9-9a64-71d21eeeac62
					column: Day

				annotation TemplateId = DateHierarchy

			partition LocalDateTable_7edc6a93-bd7e-45f9-aef3-05d82ebd2a2f = calculated
				mode: import
				source = Calendar(Date(Year(MIN('INWARD & OUTWARD'[MaxSaleDate])), 1, 1), Date(Year(MAX('INWARD & OUTWARD'[MaxSaleDate])), 12, 31))

			annotation __PBI_LocalDateTable = true

		table AgeParameter
			lineageTag: 52cf83ab-8afd-48e8-b5f6-d29c47364fdc

			measure 'AgeParameter Value' = SELECTEDVALUE('AgeParameter'[AgeParameter], 0)
				formatString: 0
				lineageTag: d48366db-0183-4286-b11f-46fd637dc22c

			column AgeParameter
				formatString: 0
				lineageTag: 9793dd58-13a7-4a85-bc31-c52a5c10a562
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata = {"version":0}

				annotation SummarizationSetBy = User

			partition AgeParameter = calculated
				mode: import
				source = GENERATESERIES(0, 1000, 1)

			annotation PBI_Id = c541fadd5988431ebb5ba8db1a0b75d9

		table SaleVelocityparameter
			lineageTag: c67c95df-6bbf-45a4-8cb2-9f5bf8532bda

			measure 'SaleVelocityparameter Value' = SELECTEDVALUE('SaleVelocityparameter'[SaleVelocityparameter], 0)
				formatString: 0
				lineageTag: 62f80512-4cc1-4bae-b554-6fb6aeb0fe49

			column SaleVelocityparameter
				formatString: 0
				lineageTag: 8924e580-cfeb-4f0b-9041-e6f0f40891f8
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata = {"version":0}

				annotation SummarizationSetBy = User

			partition SaleVelocityparameter = calculated
				mode: import
				source = GENERATESERIES(-5000, 5000, 1)

			annotation PBI_Id = ca14ca41a4d647629d27db628871519e

		table SaleThroughParameter
			lineageTag: baf67f1e-e7c5-4d4a-885d-09552633cf59

			measure 'SaleThroughParameter Value' = SELECTEDVALUE('SaleThroughParameter'[SaleThroughParameter], 0)
				formatString: 0
				lineageTag: b86f2bd2-6e56-40ff-98fa-10344052de9b

			column SaleThroughParameter
				formatString: 0
				lineageTag: 7135f520-1def-4b1b-91a3-4e2db64aa08c
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata = {"version":0}

				annotation SummarizationSetBy = User

			partition SaleThroughParameter = calculated
				mode: import
				source = GENERATESERIES(-5000, 5000, 1)

			annotation PBI_Id = a053486329ab44519ec9fb56b59acf99

		table MovementParameter
			lineageTag: eb237e02-d749-44e6-b38b-5b1602f4c644

			measure 'MovementParameter Value' = SELECTEDVALUE('MovementParameter'[MovementParameter], 0)
				formatString: 0
				lineageTag: 85998e95-ca85-46bb-ab7b-cf0f40ea74d7

			column MovementParameter
				formatString: 0
				lineageTag: 8622b5c5-f6e0-49ec-8aee-1846ec9a112f
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata = {"version":0}

				annotation SummarizationSetBy = User

			partition MovementParameter = calculated
				mode: import
				source = GENERATESERIES(-5000, 5000, 1)

			annotation PBI_Id = 9a6ecbe735b348a9982aece91e4171fe

		table RowController
			lineageTag: 4265763b-a735-4328-a6b0-3419df63aac8

			column RowController
				lineageTag: 2fed9365-81c4-4995-b879-18edcb8281cb
				summarizeBy: none
				sourceColumn: [Value1]
				sortByColumn: 'RowController Order'

				relatedColumnDetails
					groupByColumn: 'RowController Fields'

				annotation SummarizationSetBy = Automatic

			column 'RowController Fields'
				isHidden
				lineageTag: 029bcafe-cda8-4a77-ab00-fcee81f1974a
				summarizeBy: none
				sourceColumn: [Value2]
				sortByColumn: 'RowController Order'

				extendedProperty ParameterMetadata = {"version":3,"kind":2}

				annotation SummarizationSetBy = Automatic

			column 'RowController Order'
				isHidden
				formatString: 0
				lineageTag: 4f5cca0d-69ec-42e1-bc6c-5abbd6ad1461
				summarizeBy: sum
				sourceColumn: [Value3]

				annotation SummarizationSetBy = Automatic

			partition RowController = calculated
				mode: import
				source =
						{
						    ("Article No", NAMEOF('ArticleMaster'[Article No]), 0),
						    ("Article Name", NAMEOF(ArticleMaster[Article Name]), 1),
						    ("Article & Name", NAMEOF(ArticleMaster[Article with Name]), 2),
						    ("Section Name", NAMEOF('ArticleMaster'[Section Name]), 3),
						    ("Brand Name", NAMEOF('ArticleMaster'[Brand Name]), 4),
						    ("Gender", NAMEOF('ArticleMaster'[Gender]), 5),
						    ("SKU RSP", NAMEOF('ArticleMaster'[SKU RSP]), 6)
						}

			annotation PBI_Id = 47804ab0822c49cba7938e68b9f020c9

		table 'Status filter'
			lineageTag: 340830ec-b7a6-4dd5-9707-df54d2727383

			column Status
				dataType: string
				lineageTag: 55dcab3a-4573-4619-8c33-5a16977ded62
				summarizeBy: none
				sourceColumn: Status

				annotation SummarizationSetBy = Automatic

			partition 'Status filter' = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCi4tSC1ScEssLlGK1YlWgjN8U1MyS3PBzOCc/HIIA6wWznVJTUxRio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Status = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Status", type text}})
						in
						    #"Changed Type"

			annotation PBI_ResultType = Table

		table SizeMaster
			lineageTag: 14f8ff1e-71d3-4083-94b2-6466a4ff87ac

			column 'Size Name'
				dataType: string
				lineageTag: 1091c5af-6f77-4f14-8c66-bd180fc41f74
				summarizeBy: none
				sourceColumn: Size Name
				sortByColumn: 'Size ID'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Size ID'
				dataType: int64
				formatString: 0
				lineageTag: 1b2a1c38-8815-4ca1-8aab-bb69c1bde6ee
				summarizeBy: count
				sourceColumn: Size ID

				changedProperty = DataType

				annotation SummarizationSetBy = Automatic

			partition SizeMaster = m
				mode: import
				source =
						let
						    Source = ArticleMaster,
						    #"Removed Other Columns" = Table.SelectColumns(Source,{"Size Name"}),
						    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
						    #"Appended Query" = Table.Combine({#"Removed Duplicates", Sizemerger}),
						    #"Added Custom" = Table.AddColumn(#"Appended Query", "Custom", each let
						    OrderList = {
						        "1","2","3","4","5","5.5","6","6.5","7","7.5","8","8.5","9","9.5","10","10.5","11","12","13",
						        "30","32","34","36","38","44","10H","18 OZ","1SIZE","1Y","24 OZ","28-30","2XL","2XL-T","30-30",
						        "30-32","32-30","32-32","32-34","34-30","3Y","40 OZ","4-5.5","4MM","4Y","5Y","6-7.5","6Y",
						        "8-9.5","L","L/G","L/XL","LARGE","L-T","M","M/L","M10","M10W12","M11","M12","M5W7","M6W8",
						        "M7","M7W9","M8","M8W10","M9","M9W11","MEDIUM","MISC","M-T","OS","OSFM","S","S/M","SMALL",
						        "S-T","W10","W5","W6","W7","W8","W9","XL","XL-T","XS","XXL","YTH","Opening","Purchase","Sale","Closing","Age","Trend","Status","Salethrough","MRP Value","Size Set"
						    },
						    NormOrder = List.Transform(OrderList, each Text.Upper(Text.Trim(_))),
						    Pos = List.PositionOf(NormOrder, Text.Upper(Text.Trim(Text.From([Size Name]))))
						in
						    if Pos = -1 then null else Pos + 1),
						    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Custom", "Size ID"}})
						in
						    #"Renamed Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Sizemerger
			lineageTag: 22a49cf2-c339-4eda-b5ef-eae08d99573f

			column 'Size Name'
				dataType: string
				lineageTag: 5428cb22-a129-4d9c-a4b3-3aa9866b6975
				summarizeBy: none
				sourceColumn: Size Name

				annotation SummarizationSetBy = Automatic

			partition Sizemerger = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8i9IzcvMS1eK1YlWCigtSs5ILE4Fc4ITcyAM55z8YpgKx3SIWEhRal4KRFlJYklpMVxHSUZRfml6BpjvGxSgEJaYUwo1L7MqVSE4tUQpNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Size Name" = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Size Name", type text}})
						in
						    #"Changed Type"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table 'Size Set'
			lineageTag: 696204b9-5caf-4512-8b3a-5a903724e0cd

			column Brand
				dataType: string
				lineageTag: 10d0785d-3c10-4b00-80fc-c4a4b2ad11ab
				summarizeBy: none
				sourceColumn: Brand

				annotation SummarizationSetBy = Automatic

			column Gender
				dataType: string
				lineageTag: 58a16909-100d-49fc-9e05-fca4804f0a32
				summarizeBy: none
				sourceColumn: Gender

				annotation SummarizationSetBy = Automatic

			column 'Size Type'
				dataType: string
				lineageTag: 16e7f04d-027e-4f17-829a-22f7f04de83a
				summarizeBy: none
				sourceColumn: Size Type

				annotation SummarizationSetBy = Automatic

			column Size
				dataType: string
				lineageTag: 0b0b1083-af17-40b4-993b-d2cc5fc99222
				summarizeBy: none
				sourceColumn: Size

				annotation SummarizationSetBy = Automatic

			column Status
				dataType: string
				lineageTag: 7c3e35a0-60d7-4501-a28a-3b74ee7f8fb6
				summarizeBy: none
				sourceColumn: Status

				annotation SummarizationSetBy = Automatic

			column 'Section Name'
				dataType: string
				lineageTag: 93ae60de-7150-4641-bf4f-8e1bc110c2c9
				summarizeBy: none
				sourceColumn: Section Name

				annotation SummarizationSetBy = Automatic

			column sizesetid = ```
					
					    'Size Set'[Size] & "-" &
					    'Size Set'[Brand] & "-" &
					    'Size Set'[Section Name] & "-" &
					    'Size Set'[Gender]
					```
				lineageTag: 3e75890a-f75c-47c2-8b4d-49421c2a5326
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			partition 'Size Set' = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nZhNSwJRGIX/Ssw6Iq38WM7GTSnBbAJxMehAg4qiVtCvbxINyfOce+8srBbPE57re96rTqfZpF5W2W02Lle/v4r6u7opqkPzZ795TPLmx2izOXxV5S6b3Rp80Dzyz1U0P0zkO/epQidV6LrEo2p9ZfTunlKV/lHhp6WcQQtnGHCu4xfnKPl2W+6qlafHf/89Cn9Jw98S+e5RoGevzselVbzNqwSbQAk+szIgdbGs5u/Vbp/QaqtAs60D7bYONdxL0HIv6aZfOLK6baTw4cn2trJaHaAsgjV0FayiR9sqUAfrhAsRvQoCTvAM4ldCQAqfQ8JqyPf1PGUvMA9zzQKMNAs0zcboJIaAPcCCHBXG9ZQwr19q5mE2WAiMRXQ7nOBDx/fCGYHgCY14/ViXCYVAHPqAPNQBeWoDC7oMzOsuIC/nAmk9FIjrlxdxGAfk/SxEt8DwNm98B4zgM6fcCYt6USZdCizQrcAGXQts4L1gFLgYjAE3Axt6TzIPa5IFWHks0JJkIzQh8feDMwLJE24Ip4TSt2mIch79oCgFPplbp9fC6Wvn9InyuV7s/8WXURB/SMP1QSFuv1m5xnsSv3iXHBvXKjqyVXRsq+joVtHxz++HYrMzr4MzD61AXkdmHvKe2xAdmAVIzEJgEURnZkGHPt34sZER14ER13ER12ERF1FnPw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Brand = _t, Gender = _t, #"Size Type" = _t, Size = _t, Status = _t, #"Section Name" = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Brand", type text}, {"Gender", type text}, {"Size Type", type text}, {"Size", type text}, {"Status", type text}})
						in
						    #"Changed Type"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table SizeSetFilter
			lineageTag: 1c72b77e-2a85-4f3d-b007-1d7eccdd0079

			column Size-Set
				dataType: string
				lineageTag: 22e91ca1-7078-4987-818f-370e2569f35b
				summarizeBy: none
				sourceColumn: Size-Set

				annotation SummarizationSetBy = Automatic

			partition SizeSetFilter = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci4tUQjOrEpVitWJVnIrzcmB8mIB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Size-Set" = _t]),
						    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Size-Set", type text}})
						in
						    #"Changed Type"

			annotation PBI_ResultType = Table

		relationship AutoDetected_e020e9f8-ed4e-4a27-b1f8-ca0ff356b7b2
			fromColumn: OBS_sheet.'Location Id'
			toColumn: LocationMaster.LocationID

		relationship b275c255-1011-3286-027e-b876d89f2467
			fromColumn: 'INWARD & OUTWARD'.'Transaction Location Id'
			toColumn: LocationMaster.LocationID

		relationship bd144136-b34e-434c-ba6d-714df39cd95d
			joinOnDateBehavior: datePartOnly
			fromColumn: Calendar.Date
			toColumn: LocalDateTable_b94575be-bcbb-4510-a5ed-a6c6575effc8.Date

		relationship 10ca914c-8db0-57c9-8a2c-21dd58fb014f
			fromColumn: 'INWARD & OUTWARD'.'Transaction Date'
			toColumn: Calendar.Date

		relationship e83afbe8-dce0-822b-fee9-53b4c985b390
			fromColumn: 'INWARD & OUTWARD'.Uid
			toColumn: ArticleMaster.Uid

		relationship bee3ec39-66f2-de18-61f8-2ac247014154
			fromColumn: OBS_sheet.Uid
			toColumn: ArticleMaster.Uid

		relationship 293156ad-9f45-fba3-fca9-a283b9183905
			fromColumn: 'INWARD & OUTWARD'.'Transaction type'
			toColumn: TransactionType.type

		relationship 701d5596-2f10-a984-3334-9c4224ce5aed
			fromColumn: OBS_sheet.OpeningDate
			toColumn: Calendar.Date

		relationship e8784305-d8fe-b746-df84-89e6af6460e8
			isActive: false
			fromColumn: OBS_sheet.ClosingDate
			toColumn: Calendar.Date

		relationship 7a7a44a5-b5b4-4835-98cb-0beba1c0398d
			joinOnDateBehavior: datePartOnly
			fromColumn: 'INWARD & OUTWARD'.MaxSaleDate
			toColumn: LocalDateTable_7edc6a93-bd7e-45f9-aef3-05d82ebd2a2f.Date

		relationship af454fb7-e0c3-c529-827a-5e499217bc72
			isActive: false
			fromColumn: ArticleMaster.'Size Name'
			toColumn: SizeMaster.'Size Name'

		relationship 98b290a0-e96d-8378-0bc5-372199dcfedb
			fromColumn: ArticleMaster.sizesetid
			toColumn: 'Size Set'.sizesetid

		cultureInfo en-US

			linguisticMetadata = {"Version":"4.1.0","Language":"en-US","Entities":{"inward__outward":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"}},"State":"Generated","Terms":[{"inward & outward":{"State":"Generated"}}]},"inward__outward.transaction_type":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction type"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"transaction type":{"State":"Generated"}},{"transaction category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction style":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction form":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction grouping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"inward__outward.transaction_date":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Date"}},"State":"Generated","Terms":[{"transaction date":{"State":"Generated"}},{"date":{"State":"Generated","Weight":0.7}},{"transaction moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"inward__outward.transaction_no":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction No"}},"State":"Generated","Terms":[{"transaction no":{"State":"Generated"}},{"transaction number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"inward__outward.transaction_location_id":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Location Id"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"transaction location id":{"State":"Generated"}},{"location":{"State":"Generated","Weight":0.97}},{"transaction location":{"State":"Generated","Weight":0.97}},{"transaction location identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"transaction location identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"transaction location identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"transaction locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction scene":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction venue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction location credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"inward__outward.transaction_location_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Location Name"}},"State":"Generated","Terms":[{"transaction location name":{"State":"Generated"}},{"location":{"State":"Generated","Weight":0.97}},{"transaction location":{"State":"Generated","Weight":0.97}},{"transaction locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction scene":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction venue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction location nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"transaction location title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"transaction location label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"transaction location tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"inward__outward.party_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Party Name"}},"State":"Generated","Terms":[{"party name":{"State":"Generated"}},{"party":{"State":"Generated","Weight":0.97}},{"party nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"party title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"party label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"party tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"festivity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"revelry":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"merrymaking":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"celebration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"bee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"shindig":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"inward__outward.party_city":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Party City"}},"State":"Generated","Terms":[{"party city":{"State":"Generated"}},{"city":{"State":"Generated","Weight":0.97}},{"party location":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"party metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"party municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"metropolis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"municipality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"party town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"party metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"town":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"metropolitan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"inward__outward.brand_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Brand Name"}},"State":"Generated","Terms":[{"brand name":{"State":"Generated"}},{"brand nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"inward__outward.section_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Section Name"}},"State":"Generated","Terms":[{"section name":{"State":"Generated"}},{"section":{"State":"Generated","Weight":0.97}},{"section nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"unit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"segment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"slice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"inward__outward.article_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Article Name"}},"State":"Generated","Terms":[{"article name":{"State":"Generated"}},{"article":{"State":"Generated","Weight":0.97}},{"article nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"thing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"artefact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"object":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"inward__outward.style_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Style Name"}},"State":"Generated","Terms":[{"style name":{"State":"Generated"}},{"style":{"State":"Generated","Weight":0.97}},{"style nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"style title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"style label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"style tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"panache":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"elegance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"stylishness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"flair":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"smartness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"chic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"inward__outward.article_no":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Article No"}},"State":"Generated","Terms":[{"article no":{"State":"Generated"}},{"article number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"inward__outward.weather":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Weather"}},"State":"Generated","Terms":[{"weather":{"State":"Generated"}},{"climate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"inward__outward.item_class":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Item Class"}},"State":"Generated","Terms":[{"item class":{"State":"Generated"}},{"class":{"State":"Generated","Weight":0.97}},{"item classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"item category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"item genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"item course":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"item grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"item lecture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"item lesson":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"item period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"inward__outward.gender":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Gender"}},"State":"Generated","Terms":[{"gender":{"State":"Generated"}},{"sexuality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"sex":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"inward__outward.category":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Category"}},"State":"Generated","Terms":[{"category":{"State":"Generated"}},{"classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"grouping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"inward__outward.HSN_code":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"HSN Code"}},"State":"Generated","Terms":[{"HSN code":{"State":"Generated"}},{"hsn id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"hsn key":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"inward__outward.colour_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Colour Name"}},"State":"Generated","Terms":[{"colour name":{"State":"Generated"}},{"colour":{"State":"Generated","Weight":0.97}},{"colour nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"colour title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"colour label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"colour tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"inward__outward.sku_rsp":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"SKU RSP"}},"State":"Generated","Terms":[{"sku rsp":{"State":"Generated"}}]},"inward__outward.transaction_RSP":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction RSP"}},"State":"Generated","Terms":[{"transaction RSP":{"State":"Generated"}},{"RSP":{"State":"Generated","Weight":0.97}}]},"inward__outward.bin_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Bin Name"}},"State":"Generated","Terms":[{"bin name":{"State":"Generated"}},{"bin":{"State":"Generated","Weight":0.97}},{"bin nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"bin title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"bin label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"bin tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"basket":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"container":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"holder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"box":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"silo":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"tub":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"inward__outward.transaction_quantity":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Quantity"}},"State":"Generated","Terms":[{"transaction quantity":{"State":"Generated"}},{"transaction extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"transaction magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"transaction amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"transaction number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"transaction measure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"transaction size":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"transaction capacity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"transaction mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"inward__outward.transaction_taxable_value":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Taxable Value"}},"State":"Generated","Terms":[{"transaction taxable value":{"State":"Generated"}},{"transaction taxable assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"transaction taxable worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"transaction taxable price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"transaction taxable cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"transaction taxable charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"transaction taxable rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"transaction taxable importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"transaction taxable significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"transaction taxable usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"transaction taxable consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"inward__outward.transaction_total_GST_amt":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Total GST Amt"}},"State":"Generated","Terms":[{"transaction total GST amt":{"State":"Generated"}},{"transaction aggregate gst amt":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"transaction overall gst amt":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}]},"inward__outward.transaction_value_at_MRP":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Value at MRP"}},"State":"Generated","Terms":[{"transaction value at MRP":{"State":"Generated"}},{"transaction assessment at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"transaction worth at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction price at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction cost at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction charge at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction rate at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction importance at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"transaction significance at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"transaction usefulness at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"transaction consequence at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}}]},"inward__outward.transaction_value_with_GST":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Transaction Value with GST"}},"State":"Generated","Terms":[{"transaction value with GST":{"State":"Generated"}},{"value":{"State":"Generated","Weight":0.97}},{"transaction value":{"State":"Generated","Weight":0.97}},{"transaction assessment with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"transaction assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"transaction worth with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction price with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction cost with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction charge with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"transaction rate with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"transaction importance with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"transaction significance with gst":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}}]},"inward__outward.upc":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"UPC"}},"State":"Generated","Terms":[{"upc":{"State":"Generated"}}]},"inward__outward.uid":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Uid"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"uid":{"State":"Generated"}}]},"OBS_sheet":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet"}},"State":"Generated","Terms":[{"OBS sheet":{"State":"Generated"}},{"OB sheet":{"Type":"Noun","State":"Generated","Weight":0.78}},{"OBS_sheet":{"Type":"Noun","State":"Generated","Weight":0.99}},{"sheet":{"State":"Generated","Weight":0.97}},{"ob pane":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"pane":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"ob piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ob page":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ob leaf":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ob slip":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"page":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"leaf":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"slip":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"OBS_sheet.location_id":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Location Id"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"location id":{"State":"Generated"}},{"location":{"State":"Generated","Weight":0.97}},{"location identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"location identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"location identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"scene":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"venue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"address":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"place":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"OBS_sheet.location_alias":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Location Alias"}},"State":"Generated","Terms":[{"location alias":{"State":"Generated"}},{"alias":{"State":"Generated","Weight":0.97}},{"locality alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"placement alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"scene alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"venue alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"address alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"place alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"position alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"setting alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"site alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"spot alias":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"OBS_sheet.location_name":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Location Name"}},"State":"Generated","Terms":[{"location name":{"State":"Generated"}},{"location":{"State":"Generated","Weight":0.97}},{"locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"scene":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"venue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"location title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"location label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"location tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"address":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"place":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"OBS_sheet.item_code":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Item Code"}},"State":"Generated","Terms":[{"item code":{"State":"Generated"}},{"item id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"item key":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"product code":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"element code":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"entry code":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"article code":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"object code":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"piece code":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"token code":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"OBS_sheet.upc":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"UPC"}},"State":"Generated","Terms":[{"upc":{"State":"Generated"}}]},"OBS_sheet.article_no":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Article No"}},"State":"Generated","Terms":[{"article no":{"State":"Generated"}},{"article number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"OBS_sheet.section_name":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Section Name"}},"State":"Generated","Terms":[{"section name":{"State":"Generated"}},{"section":{"State":"Generated","Weight":0.97}},{"section nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"unit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"segment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"slice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"OBS_sheet.sub_section_name":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Sub Section Name"}},"State":"Generated","Terms":[{"sub section name":{"State":"Generated"}},{"section":{"State":"Generated","Weight":0.97}},{"sub section":{"State":"Generated","Weight":0.97}},{"sub section nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"sub section title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"sub section label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"sub section tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"sub unit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"sub subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"sub division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"unit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"OBS_sheet.article_name":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Article Name"}},"State":"Generated","Terms":[{"article name":{"State":"Generated"}},{"article":{"State":"Generated","Weight":0.97}},{"article nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"thing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"artefact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"object":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"OBS_sheet.gender":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Gender"}},"State":"Generated","Terms":[{"gender":{"State":"Generated"}},{"sexuality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"sex":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"OBS_sheet.brand_name":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Brand Name"}},"State":"Generated","Terms":[{"brand name":{"State":"Generated"}},{"brand nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"OBS_sheet.size_name":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Size Name"}},"State":"Generated","Terms":[{"size name":{"State":"Generated"}},{"size nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"OBS_sheet.sku_rsp":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"SKU RSP"}},"State":"Generated","Terms":[{"sku rsp":{"State":"Generated"}}]},"OBS_sheet.wholesale_price":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Wholesale Price"}},"State":"Generated","Terms":[{"wholesale price":{"State":"Generated"}},{"price":{"State":"Generated","Weight":0.97}},{"wholesale value":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale fee":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale bill":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale expense":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"wholesale outlay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"OBS_sheet.OBS_qty":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"OBS Qty"}},"State":"Generated","Terms":[{"OBS qty":{"State":"Generated"}},{"OB qty":{"Type":"Noun","State":"Generated","Weight":0.78}}]},"OBS_sheet.OBS_value_at_MRP":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"OBS Value at MRP"}},"State":"Generated","Terms":[{"OBS value at MRP":{"State":"Generated"}},{"OB value at MRP":{"Type":"Noun","State":"Generated","Weight":0.78}},{"ob assessment at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"ob worth at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"ob price at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"ob cost at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"ob charge at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"ob rate at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"ob importance at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"ob significance at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"ob usefulness at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"ob consequence at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}}]},"OBS_sheet.CBS_qty":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"CBS Qty"}},"State":"Generated","Terms":[{"CBS qty":{"State":"Generated"}}]},"OBS_sheet.CBS_value_at_MRP":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"CBS Value at MRP"}},"State":"Generated","Terms":[{"CBS value at MRP":{"State":"Generated"}},{"cbs assessment at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cbs worth at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs price at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs cost at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs charge at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs rate at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs importance at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"cbs significance at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"cbs usefulness at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"cbs consequence at mrp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}}]},"OBS_sheet.CBS_value_at_WSP":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"CBS Value at WSP"}},"State":"Generated","Terms":[{"CBS value at WSP":{"State":"Generated"}},{"cbs assessment at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cbs worth at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs price at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs cost at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs charge at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs rate at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cbs importance at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"cbs significance at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"cbs usefulness at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"cbs consequence at wsp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}}]},"OBS_sheet.net_SLS_qty":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Net SLS Qty"}},"State":"Generated","Terms":[{"net SLS qty":{"State":"Generated"}},{"net SL qty":{"Type":"Noun","State":"Generated","Weight":0.78}}]},"OBS_sheet.uid":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Uid"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"uid":{"State":"Generated"}}]},"location_master":{"Definition":{"Binding":{"ConceptualEntity":"LocationMaster"}},"State":"Generated","Terms":[{"location master":{"State":"Generated"}},{"LocationMaster":{"Type":"Noun","State":"Generated","Weight":0.99}},{"master":{"State":"Generated","Weight":0.97}},{"locality master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"placement master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"scene master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"venue master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"address master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"place master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"position master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"setting master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"site master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"spot master":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"location_master.location_ID":{"Definition":{"Binding":{"ConceptualEntity":"LocationMaster","ConceptualProperty":"LocationID"}},"State":"Generated","Terms":[{"location ID":{"State":"Generated"}},{"LocationID":{"Type":"Noun","State":"Generated","Weight":0.99}},{"location":{"State":"Generated","Weight":0.97}},{"location identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"location identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"location identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"scene":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"venue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"address":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"place":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"location_master.code":{"Definition":{"Binding":{"ConceptualEntity":"LocationMaster","ConceptualProperty":"Code"}},"State":"Generated","Terms":[{"code":{"State":"Generated"}},{"Refill To":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Reshuffle from":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Recall from":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"location_master.location_name":{"Definition":{"Binding":{"ConceptualEntity":"LocationMaster","ConceptualProperty":"LocationName"}},"State":"Generated","Terms":[{"location name":{"State":"Generated"}},{"LocationName":{"Type":"Noun","State":"Generated","Weight":0.99}},{"location":{"State":"Generated","Weight":0.97}},{"locality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"placement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"scene":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"venue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"location nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"location title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"location label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"location tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"address":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"place":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"calendar":{"Definition":{"Binding":{"ConceptualEntity":"Calendar"}},"State":"Generated","Terms":[{"calendar":{"State":"Generated"}},{"almanac":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"datebook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"agenda":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"logbook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"diary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"schedule":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"timetable":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"calendar.date":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}],"SemanticType":"Time"},"calendar.date.date_hierarchy":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","VariationSource":"Date","VariationSet":"Variation","Hierarchy":"Date Hierarchy"}},"State":"Generated","Terms":[{"date hierarchy":{"State":"Generated","Weight":0.97}}],"SemanticType":"Time"},"calendar.date.year":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","VariationSource":"Date","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Year"}},"State":"Generated","Terms":[{"year":{"State":"Generated"}},{"date year":{"State":"Generated"}},{"date yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"moment year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"period year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}],"SemanticType":"Time"},"calendar.date.quarter":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","VariationSource":"Date","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Quarter"}},"State":"Generated","Terms":[{"quarter":{"State":"Generated"}},{"date quarter":{"State":"Generated"}},{"date qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.833}},{"qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}},{"moment quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"period quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}],"SemanticType":"Time"},"calendar.date.month":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","VariationSource":"Date","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Month"}},"State":"Generated","Terms":[{"month":{"State":"Generated"}},{"date month":{"State":"Generated"}},{"date mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"moment month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"period month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}],"SemanticType":"Time"},"calendar.date.day":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","VariationSource":"Date","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Day"}},"State":"Generated","Terms":[{"day":{"State":"Generated"}},{"date day":{"State":"Generated"}},{"moment day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"period day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}],"SemanticType":"Time"},"calendar.date_key":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"DateKey"}},"State":"Generated","Terms":[{"date key":{"State":"Generated"}},{"DateKey":{"Type":"Noun","State":"Generated","Weight":0.99}},{"key":{"State":"Generated","Weight":0.97}},{"moment key":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"period key":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"main":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"basic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"fundamental":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"central":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"major":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"keynote":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"essential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"date solution":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"calendar.sequential_day_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Sequential Day Number"}},"State":"Generated","Terms":[{"sequential day number":{"State":"Generated"}},{"day number":{"State":"Generated","Weight":0.97}},{"sequential day no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"day no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"calendar.year_month":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Year Month"}},"State":"Generated","Terms":[{"year month":{"State":"Generated"}},{"year mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"yr month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"calendar.year_month_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Year Month Number"}},"State":"Generated","Terms":[{"year month number":{"State":"Generated"}},{"month number":{"State":"Generated","Weight":0.97}},{"year month no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"month no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"yr month number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"year mth number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"mth number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"calendar.fiscal_year":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Fiscal Year"}},"State":"Generated","Terms":[{"fiscal year":{"State":"Generated"}},{"fiscal yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"fisc year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"accounting year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"budget year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"fiscal date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"fiscal day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"tax year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"calendar.fiscal_year_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Fiscal Year Number"}},"State":"Generated","Terms":[{"fiscal year number":{"State":"Generated"}},{"year":{"State":"Generated","Weight":0.7}},{"year number":{"State":"Generated","Weight":0.97}},{"fiscal year no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"year no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"fisc year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.615}},{"fiscal yr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"yr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"accounting year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"budget year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"fiscal date number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"fiscal day number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"tax year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}}],"SemanticType":"Time"},"calendar.fiscal_year_quarter":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Fiscal Year Quarter"}},"State":"Generated","Terms":[{"fiscal year quarter":{"State":"Generated"}},{"year quarter":{"State":"Generated","Weight":0.97}},{"fiscal year qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.846}},{"year qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.833}},{"fisc year quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.615}},{"fiscal yr quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"yr quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"accounting year quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"budget year quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"fiscal date quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"fiscal day quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}},{"tax year quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.597}}]},"calendar.fiscal_year_quarter_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Fiscal Year Quarter Number"}},"State":"Generated","Terms":[{"fiscal year quarter number":{"State":"Generated"}},{"quarter number":{"State":"Generated","Weight":0.97}},{"year quarter number":{"State":"Generated","Weight":0.97}},{"fiscal year quarter no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"year quarter no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"quarter no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"fiscal year qtr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.686}},{"year qtr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.677}},{"qtr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.667}},{"fisc year quarter number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.629}},{"fiscal yr quarter number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"accounting year quarter number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.61}},{"budget year quarter number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.61}}]},"calendar.fiscal_quarter":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Fiscal Quarter"}},"State":"Generated","Terms":[{"fiscal quarter":{"State":"Generated"}},{"fiscal qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.833}},{"fisc quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"fiscal qrt":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"fiscal qrtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"calendar.month":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Month"}},"State":"Generated","Terms":[{"month":{"State":"Generated"}},{"mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}]},"calendar.fiscal_month_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Fiscal Month Number"}},"State":"Generated","Terms":[{"fiscal month number":{"State":"Generated"}},{"month number":{"State":"Generated","Weight":0.97}},{"fiscal month no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"month no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"fisc month number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.615}},{"fiscal mth number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"mth number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"calendar.fiscal_month_in_quarter_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Fiscal Month in Quarter Number"}},"State":"Generated","Terms":[{"fiscal month in quarter number":{"State":"Generated"}},{"quarter number":{"State":"Generated","Weight":0.97}},{"in quarter number":{"State":"Generated","Weight":0.97}},{"month in quarter number":{"State":"Generated","Weight":0.97}},{"in qtr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.846}},{"fiscal mth in quarter number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.78}},{"mth in quarter number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"in quarter no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"quarter no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"fiscal month in qtr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.693}},{"month in qtr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.686}},{"qtr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.667}},{"fisc month in quarter number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.64}},{"fiscal month in quarter no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}}]},"calendar.day_of_week":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Day of Week"}},"State":"Generated","Terms":[{"day of week":{"State":"Generated"}}]},"calendar.day_of_week_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Day of Week Number"}},"State":"Generated","Terms":[{"day of week number":{"State":"Generated"}},{"day of week no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}]},"calendar.day_of_month_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Day of Month Number"}},"State":"Generated","Terms":[{"day of month number":{"State":"Generated"}},{"day of mth number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"day of month no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}}]},"calendar.day_of_fiscal_year_number":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Day of Fiscal Year Number"}},"State":"Generated","Terms":[{"day of fiscal year number":{"State":"Generated"}},{"day of fisc year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.64}},{"day of fiscal yr number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.624}},{"day of accounting year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.621}},{"day of budget year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.621}},{"day of fiscal date number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.621}},{"day of fiscal day number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.621}},{"day of tax year number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.621}},{"day of fiscal year no":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.605}}]},"calendar.working_day":{"Definition":{"Binding":{"ConceptualEntity":"Calendar","ConceptualProperty":"Working Day"}},"State":"Generated","Terms":[{"working day":{"State":"Generated"}}]},"article_master":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster"}},"State":"Generated","Terms":[{"article master":{"State":"Generated"}},{"ArticleMaster":{"Type":"Noun","State":"Generated","Weight":0.99}},{"master":{"State":"Generated","Weight":0.97}},{"chief":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"principal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"main":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"leading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"dominant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"controlling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"directing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"major":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"article controller":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"article ruler":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"article_master.article_no":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Article No"}},"State":"Generated","Terms":[{"article no":{"State":"Generated"}},{"article number":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"article_master.section_name":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Section Name"}},"State":"Generated","Terms":[{"section name":{"State":"Generated"}},{"section":{"State":"Generated","Weight":0.97}},{"section nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"section tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"unit":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"subdivision":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"division":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"segment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"slice":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"article_master.article_name":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Article Name"}},"State":"Generated","Terms":[{"article name":{"State":"Generated"}},{"article":{"State":"Generated","Weight":0.97}},{"article nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"article tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"thing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"artefact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"object":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"piece":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"article_master.gender":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Gender"}},"State":"Generated","Terms":[{"gender":{"State":"Generated"}},{"sexuality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"sex":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"article_master.brand_name":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Brand Name"}},"State":"Generated","Terms":[{"brand name":{"State":"Generated"}},{"brand nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"brand tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"article_master.sku_rsp":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"SKU RSP"}},"State":"Generated","Terms":[{"sku rsp":{"State":"Generated"}}]},"article_master.uid":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Uid"}},"State":"Generated","Terms":[{"uid":{"State":"Generated"}}]},"all_measure":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures"}},"State":"Generated","Terms":[{"all measure":{"State":"Generated"}},{"All_Measures":{"Type":"Noun","State":"Generated","Weight":0.99}},{"measure":{"State":"Generated","Weight":0.97}},{"all degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"all quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"all quota":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"all extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quota":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"all amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"all portion":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"all ration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"inward__outward.sum_product":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"sum_product"}},"State":"Generated","Terms":[{"sum product":{"State":"Generated"}},{"sum_product":{"Type":"Noun","State":"Generated","Weight":0.99}},{"product":{"State":"Generated","Weight":0.97}},{"sum artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"artifact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"sum item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sum merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"sum produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"item":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"merchandise":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"produce":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"summation product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"aggregation product":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}}]},"inward__outward.max_sale_date":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"MaxSaleDate"}},"State":"Generated","Terms":[{"max sale date":{"State":"Generated"}},{"MaxSaleDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"sale date":{"State":"Generated","Weight":0.97}},{"max sale moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"sale moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"max sale period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"sale period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"maximum sale date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}],"SemanticType":"Time"},"inward__outward.max_sale_date.date_hierarchy":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","VariationSource":"MaxSaleDate","VariationSet":"Variation","Hierarchy":"Date Hierarchy"}},"State":"Generated","Terms":[{"max sale date hierarchy":{"State":"Generated"}},{"date hierarchy":{"State":"Generated","Weight":0.97}},{"sale date hierarchy":{"State":"Generated","Weight":0.97}}],"SemanticType":"Time"},"inward__outward.max_sale_date.year":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","VariationSource":"MaxSaleDate","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Year"}},"State":"Generated","Terms":[{"max sale year":{"State":"Generated"}},{"year":{"State":"Generated"}},{"max sale date year":{"State":"Generated"}},{"sale year":{"State":"Generated","Weight":0.97}},{"sale date year":{"State":"Generated","Weight":0.97}},{"max sale date yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"max sale yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"sale date yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"sale yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"yr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"max sale moment year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"sale moment year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"maximum sale date year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"max sale period year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"maximum sale year":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}],"SemanticType":"Time"},"inward__outward.max_sale_date.quarter":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","VariationSource":"MaxSaleDate","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Quarter"}},"State":"Generated","Terms":[{"max sale quarter":{"State":"Generated"}},{"quarter":{"State":"Generated"}},{"max sale date quarter":{"State":"Generated"}},{"sale quarter":{"State":"Generated","Weight":0.97}},{"sale date quarter":{"State":"Generated","Weight":0.97}},{"max sale date qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.857}},{"max sale qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.846}},{"sale date qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.846}},{"sale qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.833}},{"qtr":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.818}},{"max sale moment quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"sale moment quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"maximum sale date quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"max sale period quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"maximum sale quarter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}],"SemanticType":"Time"},"inward__outward.max_sale_date.month":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","VariationSource":"MaxSaleDate","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Month"}},"State":"Generated","Terms":[{"max sale month":{"State":"Generated"}},{"month":{"State":"Generated"}},{"max sale date month":{"State":"Generated"}},{"sale month":{"State":"Generated","Weight":0.97}},{"sale date month":{"State":"Generated","Weight":0.97}},{"max sale date mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"max sale mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"sale date mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"sale mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"mth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"max sale moment month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"sale moment month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"maximum sale date month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"max sale period month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"maximum sale month":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}],"SemanticType":"Time"},"inward__outward.max_sale_date.day":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","VariationSource":"MaxSaleDate","VariationSet":"Variation","Hierarchy":"Date Hierarchy","HierarchyLevel":"Day"}},"State":"Generated","Terms":[{"max sale day":{"State":"Generated"}},{"day":{"State":"Generated"}},{"max sale date day":{"State":"Generated"}},{"sale day":{"State":"Generated","Weight":0.97}},{"sale date day":{"State":"Generated","Weight":0.97}},{"max sale moment day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"sale moment day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"maximum sale date day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"max sale period day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"maximum sale day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"sale period day":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}],"SemanticType":"Time"},"inward__outward.size_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Size Name"}},"State":"Generated","Terms":[{"size name":{"State":"Generated"}},{"size nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"OBS_sheet.opening_date":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"OpeningDate"}},"State":"Generated","Terms":[{"opening date":{"State":"Generated"}},{"OpeningDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"opening moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"opening period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"OBS_sheet.closing_date":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"ClosingDate"}},"State":"Generated","Terms":[{"closing date":{"State":"Generated"}},{"ClosingDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"closing moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"closing period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"article_master.upc":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"UPC"}},"State":"Generated","Terms":[{"upc":{"State":"Generated"}}]},"article_master.size_name":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Size Name"}},"State":"Generated","Terms":[{"size name":{"State":"Generated"}},{"size nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.age":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Age"}},"State":"Generated","Terms":[{"age":{"State":"Generated"}},{"oldness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"stage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.opening":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Opening"}},"State":"Generated","Terms":[{"opening":{"State":"Generated"}},{"inaugural":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"initial":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"maiden":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"original":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"primary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"introduction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"intro":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"preamble":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"prolog":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"start":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.purchase":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Purchase"}},"State":"Generated","Terms":[{"purchase":{"State":"Generated"}},{"procurement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"consumption":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"acquisition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"buying":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"obtaining":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"securing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"foothold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"toehold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"grip":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"grasp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.ageslicer":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Ageslicer"}},"State":"Generated","Terms":[{"ageslicer":{"State":"Generated"}}]},"all_measure.sale":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Sale"}},"State":"Generated","Terms":[{"sale":{"State":"Generated"}},{"auction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"transaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"deal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"trade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"vending":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"retailing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"selling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.outward":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Outward"}},"State":"Generated","Terms":[{"outward":{"State":"Generated"}},{"external":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"all_measure.closing":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Closing"}},"State":"Generated","Terms":[{"closing":{"State":"Generated"}},{"final":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"concluding":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"finishing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"ultimate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"dying":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"terminating":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"departing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"all_measure.purchasefor_WA":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"PurchaseforWA"}},"State":"Generated","Terms":[{"purchasefor WA":{"State":"Generated"}},{"PurchaseforWA":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"all_measure.expected_sale":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"ExpectedSale"}},"State":"Generated","Terms":[{"expected sale":{"State":"Generated"}},{"ExpectedSale":{"Type":"Noun","State":"Generated","Weight":0.99}},{"expected auction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"expected transaction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"expected deal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"expected trade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"expected vending":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"expected retailing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"expected selling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"Exp Sale":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.movement_trend":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"MovementTrend"}},"State":"Generated","Terms":[{"movement trend":{"State":"Generated"}},{"MovementTrend":{"Type":"Noun","State":"Generated","Weight":0.99}},{"trend":{"State":"Generated","Weight":0.97}},{"movement tendency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement inclination":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement movement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement development":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"tendency":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"inclination":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"movement":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"development":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"movement drift":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"movement leaning":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"M Trend":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.status":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Status"}},"State":"Generated","Terms":[{"status":{"State":"Generated"}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"condition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"position":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"all_measure.salethrough":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Salethrough"}},"State":"Generated","Terms":[{"salethrough":{"State":"Generated"}}]},"all_measure.max_sale_date":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"MaxSaleDate"}},"State":"Generated","Terms":[{"max sale date":{"State":"Generated"}},{"MaxSaleDate":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"sale date":{"State":"Generated","Weight":0.97}},{"max sale moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"sale moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"max sale period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"sale period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"maximum sale date":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}],"SemanticType":"Time"},"all_measure.salevelocity_slicer":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Salevelocity_slicer"}},"State":"Generated","Terms":[{"salevelocity slicer":{"State":"Generated"}},{"Salevelocity_slicer":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"all_measure.sale_thorughslicer":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"SaleThorughslicer"}},"State":"Generated","Terms":[{"sale thorughslicer":{"State":"Generated"}},{"SaleThorughslicer":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"all_measure.movementslicer":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"movementslicer"}},"State":"Generated","Terms":[{"movementslicer":{"State":"Generated"}}]},"all_measure.closingwithGT":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"closingwithGT%"}},"State":"Generated","Terms":[{"closingwithGT%":{"State":"Generated"}},{"closingwithgt percentage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"closingwithgt pct":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"shelf_life_parameter":{"Definition":{"Binding":{"ConceptualEntity":"ShelfLifeParameter"}},"State":"Generated","Terms":[{"shelf life parameter":{"State":"Generated"}},{"ShelfLifeParameter":{"Type":"Noun","State":"Generated","Weight":0.99}},{"parameter":{"State":"Generated","Weight":0.97}},{"life parameter":{"State":"Generated","Weight":0.97}},{"shelf life stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"shelf life limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"shelf life restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"shelf life constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"shelf life consideration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"shelf life boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"life stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"life limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"life restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"life constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}}]},"shelf_life_parameter.shelf_life":{"Definition":{"Binding":{"ConceptualEntity":"ShelfLifeParameter","ConceptualProperty":"Shelf Life"}},"State":"Generated","Terms":[{"shelf life":{"State":"Generated"}},{"life":{"State":"Generated","Weight":0.97}},{"shelf lifespan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"shelf lifecycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"lifespan":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"lifecycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"shelf lifetime":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lifetime":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"shelf existence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"existence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"shelf being":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"shelf living":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"shelf_life_parameter.shelf_life_value":{"Definition":{"Binding":{"ConceptualEntity":"ShelfLifeParameter","ConceptualProperty":"Shelf Life Value"}},"State":"Generated","Terms":[{"shelf life value":{"State":"Generated"}},{"value":{"State":"Generated","Weight":0.97}},{"life value":{"State":"Generated","Weight":0.97}},{"shelf life assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"life assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"shelf life worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"shelf life price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"shelf life cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"shelf life charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"shelf life rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"life worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"life price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"transaction_type":{"Definition":{"Binding":{"ConceptualEntity":"TransactionType"}},"State":"Generated","Terms":[{"transaction type":{"State":"Generated"}},{"TransactionType":{"Type":"Noun","State":"Generated","Weight":0.99}},{"transaction category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"transaction brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction style":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction form":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"transaction grouping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"transaction_type.type":{"Definition":{"Binding":{"ConceptualEntity":"TransactionType","ConceptualProperty":"type"}},"State":"Generated","Terms":[{"type":{"State":"Generated"}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"form":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"grouping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"transaction_type.id":{"Definition":{"Binding":{"ConceptualEntity":"TransactionType","ConceptualProperty":"id"}},"State":"Generated","Terms":[{"id":{"State":"Generated"}},{"identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}],"NameType":"Identifier"},"transaction_type.group":{"Definition":{"Binding":{"ConceptualEntity":"TransactionType","ConceptualProperty":"Group"}},"State":"Generated","Terms":[{"group":{"State":"Generated"}},{"organization":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"bracket":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"crew":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"team":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"transaction_type.id_group":{"Definition":{"Binding":{"ConceptualEntity":"TransactionType","ConceptualProperty":"idGroup"}},"State":"Generated","Terms":[{"id group":{"State":"Generated"}},{"idGroup":{"Type":"Noun","State":"Generated","Weight":0.99}},{"id category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id organization":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"id bracket":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id crew":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"id team":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"identification group":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identity group":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"identifier group":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"credential group":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"age_parameter":{"Definition":{"Binding":{"ConceptualEntity":"AgeParameter"}},"State":"Generated","Terms":[{"age parameter":{"State":"Generated","Weight":0.87}},{"AgeParameter":{"Type":"Noun","State":"Generated","Weight":0.8613}},{"parameter":{"State":"Generated","Weight":0.8439}},{"age stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age consideration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"age_parameter.age_parameter":{"Definition":{"Binding":{"ConceptualEntity":"AgeParameter","ConceptualProperty":"AgeParameter"}},"State":"Generated","Terms":[{"age parameter":{"State":"Generated"}},{"AgeParameter":{"Type":"Noun","State":"Generated","Weight":0.99}},{"parameter":{"State":"Generated","Weight":0.97}},{"age stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age consideration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"age boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"age_parameter.AgeParameter_value":{"Definition":{"Binding":{"ConceptualEntity":"AgeParameter","ConceptualProperty":"AgeParameter Value"}},"State":"Generated","Terms":[{"AgeParameter value":{"State":"Generated"}},{"ageparameter assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ageparameter worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ageparameter price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ageparameter cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ageparameter charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ageparameter rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ageparameter importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"ageparameter significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"ageparameter usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"ageparameter consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"sale_velocityparameter":{"Definition":{"Binding":{"ConceptualEntity":"SaleVelocityparameter"}},"State":"Generated","Terms":[{"sale velocityparameter":{"State":"Generated","Weight":0.87}},{"SaleVelocityparameter":{"Type":"Noun","State":"Generated","Weight":0.8613}}]},"sale_velocityparameter.sale_velocityparameter":{"Definition":{"Binding":{"ConceptualEntity":"SaleVelocityparameter","ConceptualProperty":"SaleVelocityparameter"}},"State":"Generated","Terms":[{"sale velocityparameter":{"State":"Generated"}},{"SaleVelocityparameter":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"sale_velocityparameter.SaleVelocityparameter_value":{"Definition":{"Binding":{"ConceptualEntity":"SaleVelocityparameter","ConceptualProperty":"SaleVelocityparameter Value"}},"State":"Generated","Terms":[{"SaleVelocityparameter value":{"State":"Generated"}},{"salevelocityparameter assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"salevelocityparameter worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salevelocityparameter price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salevelocityparameter cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salevelocityparameter charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salevelocityparameter rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salevelocityparameter importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"salevelocityparameter significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"salevelocityparameter usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"salevelocityparameter consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"sale_through_parameter":{"Definition":{"Binding":{"ConceptualEntity":"SaleThroughParameter"}},"State":"Generated","Terms":[{"sale through parameter":{"State":"Generated","Weight":0.87}},{"SaleThroughParameter":{"Type":"Noun","State":"Generated","Weight":0.8613}},{"auction through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"transaction through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"deal through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"trade through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"vending through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"retailing through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"selling through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}}]},"sale_through_parameter.sale_through_parameter":{"Definition":{"Binding":{"ConceptualEntity":"SaleThroughParameter","ConceptualProperty":"SaleThroughParameter"}},"State":"Generated","Terms":[{"sale through parameter":{"State":"Generated"}},{"SaleThroughParameter":{"Type":"Noun","State":"Generated","Weight":0.99}},{"auction through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"transaction through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"deal through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"trade through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"vending through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"retailing through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"selling through parameter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}}]},"sale_through_parameter.SaleThroughParameter_value":{"Definition":{"Binding":{"ConceptualEntity":"SaleThroughParameter","ConceptualProperty":"SaleThroughParameter Value"}},"State":"Generated","Terms":[{"SaleThroughParameter value":{"State":"Generated"}},{"salethroughparameter assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"salethroughparameter worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salethroughparameter price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salethroughparameter cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salethroughparameter charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salethroughparameter rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"salethroughparameter importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"salethroughparameter significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"salethroughparameter usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"salethroughparameter consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"movement_parameter":{"Definition":{"Binding":{"ConceptualEntity":"MovementParameter"}},"State":"Generated","Terms":[{"movement parameter":{"State":"Generated","Weight":0.87}},{"MovementParameter":{"Type":"Noun","State":"Generated","Weight":0.8613}},{"parameter":{"State":"Generated","Weight":0.8439}},{"movement stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement consideration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"movement_parameter.movement_parameter":{"Definition":{"Binding":{"ConceptualEntity":"MovementParameter","ConceptualProperty":"MovementParameter"}},"State":"Generated","Terms":[{"movement parameter":{"State":"Generated"}},{"MovementParameter":{"Type":"Noun","State":"Generated","Weight":0.99}},{"parameter":{"State":"Generated","Weight":0.97}},{"movement stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement consideration":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movement boundary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"stricture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"limitation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"restriction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"constraint":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"movement_parameter.MovementParameter_value":{"Definition":{"Binding":{"ConceptualEntity":"MovementParameter","ConceptualProperty":"MovementParameter Value"}},"State":"Generated","Terms":[{"MovementParameter value":{"State":"Generated"}},{"movementparameter assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"movementparameter worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"movementparameter price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"movementparameter cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"movementparameter charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"movementparameter rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"movementparameter importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"movementparameter significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"movementparameter usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"movementparameter consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"row_controller":{"Definition":{"Binding":{"ConceptualEntity":"RowController"}},"State":"Generated","Terms":[{"row controller":{"State":"Generated"}},{"RowController":{"Type":"Noun","State":"Generated","Weight":0.99}},{"controller":{"State":"Generated","Weight":0.97}},{"line controller":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"row supervisor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row manager":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row organizer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row regulator":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row director":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"supervisor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"manager":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"organizer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"regulator":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"row_controller.row_controller":{"Definition":{"Binding":{"ConceptualEntity":"RowController","ConceptualProperty":"RowController"}},"State":"Generated","Terms":[{"row controller":{"State":"Generated"}},{"row controller name":{"State":"Generated"}},{"RowController":{"Type":"Noun","State":"Generated","Weight":0.99}},{"controller":{"State":"Generated","Weight":0.97}},{"line controller":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"row supervisor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row manager":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row organizer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row regulator":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"row director":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"supervisor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"manager":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"organizer":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"regulator":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}],"NameType":"Name"},"row_controller.RowController_field":{"Definition":{"Binding":{"ConceptualEntity":"RowController","ConceptualProperty":"RowController Fields"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"RowController field":{"State":"Generated"}},{"rowcontroller arena":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"rowcontroller turf":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller ground":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller pitch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller park":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller meadow":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"rowcontroller grassland":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"rowcontroller lea":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"rowcontroller pasture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}},{"rowcontroller countryside":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"row_controller.RowController_order":{"Definition":{"Binding":{"ConceptualEntity":"RowController","ConceptualProperty":"RowController Order"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"RowController order":{"State":"Generated"}},{"rowcontroller instruction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"rowcontroller direction":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"rowcontroller edict":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"rowcontroller command":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller directive":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller demand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller mandate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller imperative":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"rowcontroller stability":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"rowcontroller harmony":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"OBS_sheet.MRP_value":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"MRPValue"}},"State":"Generated","Terms":[{"MRP value":{"State":"Generated"}},{"MRPValue":{"Type":"Noun","State":"Generated","Weight":0.99}},{"value":{"State":"Generated","Weight":0.97}},{"mrp assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"mrp worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"article_master.article_with_name":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Article with Name"}},"State":"Generated","Terms":[{"article with name":{"State":"Generated"}},{"article":{"State":"Generated","Weight":0.97}},{"article with nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"article with title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"article with label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"article with tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"thing with name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"artefact with name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"artifact with name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"object with name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"item with name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"piece with name":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"all_measure.mrp_value":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Mrp Value"}},"State":"Generated","Terms":[{"mrp value":{"State":"Generated"}},{"mrp assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"mrp worth":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp price":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp cost":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp charge":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp rate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"mrp importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"mrp significance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"mrp usefulness":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"mrp consequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"MrpValue":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"article_master.sizewithlabel":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"sizewithlabel"}},"State":"Generated","Terms":[{"sizewithlabel":{"State":"Generated"}}]},"all_measure.closingwithpercent":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"closingwithpercent"}},"State":"Generated","Terms":[{"closingwithpercent":{"State":"Generated"}}]},"inward__outward.season_2":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Season2"}},"State":"Generated","Terms":[{"season 2":{"State":"Generated"}},{"Season2":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"inward__outward.season_name":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Season Name"}},"State":"Generated","Terms":[{"season name":{"State":"Generated"}},{"season":{"State":"Generated","Weight":0.97}},{"season nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"term":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"spell":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"inward__outward.runnintotal":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"runnintotal"}},"State":"Generated","Terms":[{"runnintotal":{"State":"Generated"}}]},"inward__outward.closing":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"closing"}},"State":"Generated","Terms":[{"closing":{"State":"Generated"}},{"final":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"concluding":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"finishing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"ultimate":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"dying":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"terminating":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"departing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"inward__outward.diff":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"diff"}},"State":"Generated","Terms":[{"diff":{"State":"Generated"}}]},"inward__outward.islatestdate":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"Islatestdate"}},"State":"Generated","Terms":[{"islatestdate":{"State":"Generated"}}]},"OBS_sheet.season_2":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Season2"}},"State":"Generated","Terms":[{"season 2":{"State":"Generated"}},{"Season2":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"OBS_sheet.season_name":{"Definition":{"Binding":{"ConceptualEntity":"OBS_sheet","ConceptualProperty":"Season Name"}},"State":"Generated","Terms":[{"season name":{"State":"Generated"}},{"season":{"State":"Generated","Weight":0.97}},{"season nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"term":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"spell":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"article_master.season_name":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Season Name"}},"State":"Generated","Terms":[{"season name":{"State":"Generated"}},{"season":{"State":"Generated","Weight":0.97}},{"season nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"season tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"term":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"spell":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"article_master.season_2":{"Definition":{"Binding":{"ConceptualEntity":"ArticleMaster","ConceptualProperty":"Season2"}},"State":"Generated","Terms":[{"season 2":{"State":"Generated"}},{"Season2":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"all_measure.titlewithtotal_inventory":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"TitlewithtotalInventory"}},"State":"Generated","Terms":[{"titlewithtotal inventory":{"State":"Generated"}},{"TitlewithtotalInventory":{"Type":"Noun","State":"Generated","Weight":0.99}},{"titlewithtotal portfolio":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"titlewithtotal list":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal record":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal account":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal register":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal catalogue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal catalog":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal roster":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal roll":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"titlewithtotal stock":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.461}}]},"all_measure.latest_OBS":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"latestOBS"}},"State":"Generated","Terms":[{"latest OBS":{"State":"Generated"}},{"latestOBS":{"Type":"Noun","State":"Generated","Weight":0.99}},{"OBS":{"State":"Generated","Weight":0.97}}]},"all_measure.latest_in_out":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"LatestInOut"}},"State":"Generated","Terms":[{"latest in out":{"State":"Generated"}},{"LatestInOut":{"Type":"Noun","State":"Generated","Weight":0.99}},{"out":{"Type":"Noun","State":"Generated"}},{"in out":{"State":"Generated","Weight":0.97}},{"ready":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"contraband":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"all_measure.openingconfirmation":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Openingconfirmation"}},"State":"Generated","Terms":[{"openingconfirmation":{"State":"Generated"}}]},"all_measure.salewithwa":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"salewithwa"}},"State":"Generated","Terms":[{"salewithwa":{"State":"Generated"}}]},"all_measure.statusslicer":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"statusslicer"}},"State":"Generated","Terms":[{"statusslicer":{"State":"Generated"}}]},"all_measure.size_values":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Size_values"}},"State":"Generated","Terms":[{"size values":{"State":"Generated"}},{"Size_values":{"Type":"Noun","State":"Generated","Weight":0.99}},{"values":{"State":"Generated","Weight":0.97}},{"size ethic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"size principle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"size tenet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"size belief":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"ethic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"principle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"tenet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"belief":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"size standard":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"size moral":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"all_measure.salethroughcolor":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"salethroughcolor"}},"State":"Generated","Terms":[{"salethroughcolor":{"State":"Generated"}}]},"all_measure.firstin_date":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Firstin_Date"}},"State":"Generated","Terms":[{"firstin date":{"State":"Generated"}},{"Firstin_Date":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"firstin moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"firstin period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"FirstInDate":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}],"SemanticType":"Time"},"status_filter":{"Definition":{"Binding":{"ConceptualEntity":"Status filter"}},"State":"Generated","Terms":[{"status filter":{"State":"Generated"}},{"filter":{"State":"Generated","Weight":0.97}},{"category filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"importance filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"prestige filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"prominence filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"condition filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"class filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"grade filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"level filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"position filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"rank filter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"status_filter.status":{"Definition":{"Binding":{"ConceptualEntity":"Status filter","ConceptualProperty":"Status"}},"State":"Generated","Terms":[{"status":{"State":"Generated"}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"condition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"position":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"size_master":{"Definition":{"Binding":{"ConceptualEntity":"SizeMaster"}},"State":"Generated","Terms":[{"size master":{"State":"Generated"}},{"SizeMaster":{"Type":"Noun","State":"Generated","Weight":0.99}},{"master":{"State":"Generated","Weight":0.97}},{"chief":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"principal":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"main":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"leading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"dominant":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"controlling":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"directing":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"major":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"size controller":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}},{"size ruler":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.475}}]},"size_master.size_name":{"Definition":{"Binding":{"ConceptualEntity":"SizeMaster","ConceptualProperty":"Size Name"}},"State":"Generated","Terms":[{"size name":{"State":"Generated"}},{"size nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"size_master.size_ID":{"Definition":{"Binding":{"ConceptualEntity":"SizeMaster","ConceptualProperty":"Size ID"}},"State":"Generated","Terms":[{"size ID":{"State":"Generated"}},{"size identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"size identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"size identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"size credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"sizemerger":{"Definition":{"Binding":{"ConceptualEntity":"Sizemerger"}},"State":"Generated","Terms":[{"sizemerger":{"State":"Generated"}}]},"sizemerger.size_name":{"Definition":{"Binding":{"ConceptualEntity":"Sizemerger","ConceptualProperty":"Size Name"}},"State":"Generated","Terms":[{"size name":{"State":"Generated"}},{"size nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.lastin_date":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Lastin_Date"}},"State":"Generated","Terms":[{"lastin date":{"State":"Generated"}},{"Lastin_Date":{"Type":"Noun","State":"Generated","Weight":0.99}},{"date":{"State":"Generated","Weight":0.7}},{"lastin moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"lastin period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"LastInDate":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}],"SemanticType":"Time"},"all_measure.sale_avg":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"Sale Avg"}},"State":"Generated","Terms":[{"sale avg":{"State":"Generated"}},{"sale average":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"all_measure.selectedcode":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"selectedcode"}},"State":"Generated","Terms":[{"selectedcode":{"State":"Generated"}}]},"all_measure.suggestion_refill":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"suggestionRefill"}},"State":"Generated","Terms":[{"suggestion refill":{"State":"Generated"}},{"suggestionRefill":{"Type":"Noun","State":"Generated","Weight":0.99}},{"refill":{"State":"Generated","Weight":0.97}},{"suggestion replenishment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"replenishment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"suggestion top-up":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"suggestion fill-up":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"suggestion more":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"top-up":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"fill-up":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"Suggestion":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.suggestion_resuffle":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"suggestionResuffle"}},"State":"Generated","Terms":[{"suggestion resuffle":{"State":"Generated"}},{"suggestionResuffle":{"Type":"Noun","State":"Generated","Weight":0.99}},{"Suggestion":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.suggestionrecal":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"suggestionrecal"}},"State":"Generated","Terms":[{"suggestionrecal":{"State":"Generated"}},{"Suggetion":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"all_measure.status_conditional":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"statusConditional"}},"State":"Generated","Terms":[{"status conditional":{"State":"Generated"}},{"statusConditional":{"Type":"Noun","State":"Generated","Weight":0.99}},{"conditional":{"State":"Generated","Weight":0.97}},{"category conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"importance conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"prestige conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"prominence conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"condition conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"class conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"grade conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"level conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"position conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"rank conditional":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"size_set":{"Definition":{"Binding":{"ConceptualEntity":"Size Set"}},"State":"Generated","Terms":[{"size set":{"State":"Generated"}},{"set":{"State":"Generated","Weight":0.97}},{"usual":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"regular":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"firm":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"solid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"size_set.brand":{"Definition":{"Binding":{"ConceptualEntity":"Size Set","ConceptualProperty":"Brand"}},"State":"Generated","Terms":[{"brand":{"State":"Generated"}},{"variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"marque":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"make":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"trademark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"strain":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"cast":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"marker":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"size_set.gender":{"Definition":{"Binding":{"ConceptualEntity":"Size Set","ConceptualProperty":"Gender"}},"State":"Generated","Terms":[{"gender":{"State":"Generated"}},{"sexuality":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"sex":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"size_set.size_type":{"Definition":{"Binding":{"ConceptualEntity":"Size Set","ConceptualProperty":"Size Type"}},"State":"Generated","Terms":[{"size type":{"State":"Generated"}},{"size category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"size genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"size manner":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"size variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"size brand":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size style":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size form":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"size grouping":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"size_set.size":{"Definition":{"Binding":{"ConceptualEntity":"Size Set","ConceptualProperty":"Size"}},"State":"Generated","Terms":[{"size":{"State":"Generated"}},{"extent":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"magnitude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"scope":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"volume":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"dimension":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"mass":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"bulk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"size_set.status":{"Definition":{"Binding":{"ConceptualEntity":"Size Set","ConceptualProperty":"Status"}},"State":"Generated","Terms":[{"status":{"State":"Generated"}},{"importance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prestige":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"prominence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"condition":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"position":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"all_measure.refil_from_suggetion":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"RefilFromSuggetion"}},"State":"Generated","Terms":[{"refil from suggetion":{"State":"Generated"}},{"RefilFromSuggetion":{"Type":"Noun","State":"Generated","Weight":0.99}},{"Refill From Suggestion":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"inward__outward.I_sfresh":{"Definition":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD","ConceptualProperty":"ISfresh"}},"State":"Generated","Terms":[{"I sfresh":{"State":"Generated"}},{"ISfresh":{"Type":"Noun","State":"Generated","Weight":0.99}}]},"all_measure.reshuffleto_suggetion":{"Definition":{"Binding":{"ConceptualEntity":"All_Measures","ConceptualProperty":"ReshuffletoSuggetion"}},"State":"Generated","Terms":[{"reshuffleto suggetion":{"State":"Generated"}},{"ReshuffletoSuggetion":{"Type":"Noun","State":"Generated","Weight":0.99}},{"Reshuffle to Suggestion":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]}},"Relationships":{"calendar_date_has_date_hierarchy":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar.date":{"Target":{"Entity":"calendar.date"}},"calendar.date.date_hierarchy":{"Target":{"Entity":"calendar.date.date_hierarchy"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar.date"},"Object":{"Role":"calendar.date.date_hierarchy"}},"State":"Generated","Weight":0.99,"ID":"dates_have_date_hierarchies"}]},"OBS_sheet_has_calendar":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"calendar":{"Target":{"Entity":"calendar"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"calendar"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_calendars"},{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"OBS_sheet"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_OBS_sheets"}]},"OBS_sheet_has_article_master":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"article_master":{"Target":{"Entity":"article_master"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"article_master"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_article_masters"},{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"OBS_sheet"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_OBS_sheets"}]},"OBS_sheet_has_location_master":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"location_master":{"Target":{"Entity":"location_master"},"Nouns":[{"location":{"State":"Generated"}}]}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"location_master"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_location_masters"},{"Attribute":{"Subject":{"Role":"location_master"},"Object":{"Role":"OBS_sheet"}},"State":"Generated","Weight":0.99,"ID":"location_masters_have_OBS_sheets"}]},"inward__outward_has_transaction_type":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"transaction_type":{"Target":{"Entity":"transaction_type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"transaction_type"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_types"},{"Attribute":{"Subject":{"Role":"transaction_type"},"Object":{"Role":"inward__outward"}},"State":"Generated","Weight":0.99,"ID":"transaction_types_have_inward__outwards"}]},"inward__outward_has_article_master":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"article_master":{"Target":{"Entity":"article_master"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"article_master"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_article_masters"},{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"inward__outward"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_inward__outwards"}]},"inward__outward_has_calendar":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"calendar":{"Target":{"Entity":"calendar"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"calendar"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_calendars"},{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"inward__outward"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_inward__outwards"}]},"inward__outward_has_location_master":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"location_master":{"Target":{"Entity":"location_master"},"Nouns":[{"location":{"State":"Generated"}},{"transaction location":{"State":"Generated"}}]}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"location_master"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_location_masters"},{"Attribute":{"Subject":{"Role":"location_master"},"Object":{"Role":"inward__outward"}},"State":"Generated","Weight":0.99,"ID":"location_masters_have_inward__outwards"}]},"all_measure_has_reshuffleto_suggetion":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.reshuffleto_suggetion":{"Target":{"Entity":"all_measure.reshuffleto_suggetion"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.reshuffleto_suggetion"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_reshuffleto_suggetion"},{"Verb":{"Subject":{"Role":"all_measure"},"Verbs":[{"Reshuffle":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"to":{"State":"Generated"}}],"Object":{"Role":"all_measure.reshuffleto_suggetion"}}]},"State":"Generated","Weight":0.95,"ID":"all_measures_Reshuffle_to_reshuffleto_suggetion"}]},"inward__outward_has_I_sfresh":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.I_sfresh":{"Target":{"Entity":"inward__outward.I_sfresh"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.I_sfresh"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_I_sfreshes"}]},"all_measure_has_refil_from_suggetion":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.refil_from_suggetion":{"Target":{"Entity":"all_measure.refil_from_suggetion"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.refil_from_suggetion"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_refil_from_suggetion"},{"Verb":{"Subject":{"Role":"all_measure"},"Verbs":[{"Refill":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"From":{"State":"Generated"}}],"Object":{"Role":"all_measure.refil_from_suggetion"}}]},"State":"Generated","Weight":0.95,"ID":"all_measures_Refill_From_refil_from_suggetion"}]},"size_set_has_status":{"Binding":{"ConceptualEntity":"Size Set"},"State":"Generated","Roles":{"size_set":{"Target":{"Entity":"size_set"}},"size_set.status":{"Target":{"Entity":"size_set.status"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"size_set"},"Object":{"Role":"size_set.status"}},"State":"Generated","Weight":0.99,"ID":"size_sets_have_statuses"}]},"size_set_has_size":{"Binding":{"ConceptualEntity":"Size Set"},"State":"Generated","Roles":{"size_set":{"Target":{"Entity":"size_set"}},"size_set.size":{"Target":{"Entity":"size_set.size"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"size_set"},"Object":{"Role":"size_set.size"}},"State":"Generated","Weight":0.99,"ID":"size_sets_have_sizes"}]},"size_set_has_size_type":{"Binding":{"ConceptualEntity":"Size Set"},"State":"Generated","Roles":{"size_set":{"Target":{"Entity":"size_set"}},"size_set.size_type":{"Target":{"Entity":"size_set.size_type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"size_set"},"Object":{"Role":"size_set.size_type"}},"State":"Generated","Weight":0.99,"ID":"size_sets_have_size_types"}]},"size_set_has_gender":{"Binding":{"ConceptualEntity":"Size Set"},"State":"Generated","Roles":{"size_set":{"Target":{"Entity":"size_set"}},"size_set.gender":{"Target":{"Entity":"size_set.gender"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"size_set"},"Object":{"Role":"size_set.gender"}},"State":"Generated","Weight":0.99,"ID":"size_sets_have_genders"}]},"size_set_has_brand":{"Binding":{"ConceptualEntity":"Size Set"},"State":"Generated","Roles":{"size_set":{"Target":{"Entity":"size_set"}},"size_set.brand":{"Target":{"Entity":"size_set.brand"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"size_set"},"Object":{"Role":"size_set.brand"}},"State":"Generated","Weight":0.99,"ID":"size_sets_have_brands"}]},"all_measure_has_status_conditional":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.status_conditional":{"Target":{"Entity":"all_measure.status_conditional"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.status_conditional"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_status_conditional"}]},"OBS_sheet_has_all_measure_suggestionrecal":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.suggestionrecal":{"Target":{"Entity":"all_measure.suggestionrecal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.suggestionrecal"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_suggestionrecal"}]},"all_measure_has_suggestion_resuffle":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.suggestion_resuffle":{"Target":{"Entity":"all_measure.suggestion_resuffle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.suggestion_resuffle"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_suggestion_resuffle"}]},"all_measure_has_suggestion_refill":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.suggestion_refill":{"Target":{"Entity":"all_measure.suggestion_refill"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.suggestion_refill"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_suggestion_refill"}]},"location_master_has_all_measure_selectedcode":{"Binding":{"ConceptualEntity":"LocationMaster"},"State":"Generated","Roles":{"location_master":{"Target":{"Entity":"location_master"}},"all_measure.selectedcode":{"Target":{"Entity":"all_measure.selectedcode"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"location_master"},"Object":{"Role":"all_measure.selectedcode"}},"State":"Generated","Weight":0.99,"ID":"location_masters_have_selectedcode"}]},"all_measure_has_sale_avg":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.sale_avg":{"Target":{"Entity":"all_measure.sale_avg"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.sale_avg"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_sale_avg"}]},"all_measure_has_lastin_date":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.lastin_date":{"Target":{"Entity":"all_measure.lastin_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.lastin_date"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_lastin_date"}]},"sizemerger_has_size_name":{"Binding":{"ConceptualEntity":"Sizemerger"},"State":"Generated","Roles":{"sizemerger":{"Target":{"Entity":"sizemerger"}},"sizemerger.size_name":{"Target":{"Entity":"sizemerger.size_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sizemerger"},"Object":{"Role":"sizemerger.size_name"}},"State":"Generated","Weight":0.99,"ID":"sizemergers_have_size_names"}]},"size_master_has_size_ID":{"Binding":{"ConceptualEntity":"SizeMaster"},"State":"Generated","Roles":{"size_master":{"Target":{"Entity":"size_master"}},"size_master.size_ID":{"Target":{"Entity":"size_master.size_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"size_master"},"Object":{"Role":"size_master.size_ID"}},"State":"Generated","Weight":0.99,"ID":"size_masters_have_size_ID"}]},"size_master_has_size_name":{"Binding":{"ConceptualEntity":"SizeMaster"},"State":"Generated","Roles":{"size_master":{"Target":{"Entity":"size_master"}},"size_master.size_name":{"Target":{"Entity":"size_master.size_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"size_master"},"Object":{"Role":"size_master.size_name"}},"State":"Generated","Weight":0.99,"ID":"size_masters_have_size_names"}]},"status_filter_has_status":{"Binding":{"ConceptualEntity":"Status filter"},"State":"Generated","Roles":{"status_filter":{"Target":{"Entity":"status_filter"}},"status_filter.status":{"Target":{"Entity":"status_filter.status"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"status_filter"},"Object":{"Role":"status_filter.status"}},"State":"Generated","Weight":0.99,"ID":"status_filters_have_statuses"}]},"all_measure_has_firstin_date":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.firstin_date":{"Target":{"Entity":"all_measure.firstin_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.firstin_date"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_firstin_date"}]},"all_measure_has_salethroughcolor":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.salethroughcolor":{"Target":{"Entity":"all_measure.salethroughcolor"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.salethroughcolor"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_salethroughcolor"}]},"all_measure_has_size_values":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.size_values":{"Target":{"Entity":"all_measure.size_values"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.size_values"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_size_values"}]},"all_measure_has_statusslicer":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.statusslicer":{"Target":{"Entity":"all_measure.statusslicer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.statusslicer"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_statusslicer"}]},"all_measure_has_salewithwa":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.salewithwa":{"Target":{"Entity":"all_measure.salewithwa"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.salewithwa"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_salewithwa"}]},"all_measure_has_openingconfirmation":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.openingconfirmation":{"Target":{"Entity":"all_measure.openingconfirmation"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.openingconfirmation"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_openingconfirmation"}]},"inward__outward_has_all_measure_latest_in_out":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"all_measure.latest_in_out":{"Target":{"Entity":"all_measure.latest_in_out"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"all_measure.latest_in_out"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_latest_in_out"},{"Preposition":{"Subject":{"Role":"inward__outward"},"Prepositions":[{"out":{"State":"Generated"}},{"in":{"State":"Generated"}}],"Object":{"Role":"all_measure.latest_in_out"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_are_out_latest_in_out"}]},"OBS_sheet_has_all_measure_latest_OBS":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.latest_OBS":{"Target":{"Entity":"all_measure.latest_OBS"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.latest_OBS"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_latest_OBS"}]},"inward__outward_has_all_measure_latest_OBS":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"all_measure.latest_OBS":{"Target":{"Entity":"all_measure.latest_OBS"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"all_measure.latest_OBS"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_latest_OBS"}]},"OBS_sheet_has_all_measure_titlewithtotal_inventory":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.titlewithtotal_inventory":{"Target":{"Entity":"all_measure.titlewithtotal_inventory"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.titlewithtotal_inventory"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_titlewithtotal_inventory"}]},"article_master_has_season_2":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.season_2":{"Target":{"Entity":"article_master.season_2"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.season_2"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_season_2"}]},"article_master_has_season_name":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.season_name":{"Target":{"Entity":"article_master.season_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.season_name"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_season_names"}]},"OBS_sheet_has_season_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.season_name":{"Target":{"Entity":"OBS_sheet.season_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.season_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_season_names"}]},"OBS_sheet_has_season_2":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.season_2":{"Target":{"Entity":"OBS_sheet.season_2"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.season_2"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_season_2"}]},"inward__outward_has_islatestdate":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.islatestdate":{"Target":{"Entity":"inward__outward.islatestdate"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.islatestdate"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_islatestdates"}]},"inward__outward_has_diff":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.diff":{"Target":{"Entity":"inward__outward.diff"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.diff"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_diffs"}]},"inward__outward_has_closing":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.closing":{"Target":{"Entity":"inward__outward.closing"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.closing"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_closing"}]},"inward__outward_has_runnintotal":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.runnintotal":{"Target":{"Entity":"inward__outward.runnintotal"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.runnintotal"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_runnintotals"}]},"inward__outward_has_season_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.season_name":{"Target":{"Entity":"inward__outward.season_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.season_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_season_names"}]},"inward__outward_has_season_2":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.season_2":{"Target":{"Entity":"inward__outward.season_2"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.season_2"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_season_2"}]},"OBS_sheet_has_all_measure_closingwithpercent":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.closingwithpercent":{"Target":{"Entity":"all_measure.closingwithpercent"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.closingwithpercent"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_closingwithpercent"}]},"article_master_has_sizewithlabel":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.sizewithlabel":{"Target":{"Entity":"article_master.sizewithlabel"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.sizewithlabel"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_sizewithlabels"}]},"OBS_sheet_has_all_measure_mrp_value":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.mrp_value":{"Target":{"Entity":"all_measure.mrp_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.mrp_value"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_mrp_value"}]},"article_master_has_article_with_name":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.article_with_name":{"Target":{"Entity":"article_master.article_with_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.article_with_name"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_article_with_name"},{"Verb":{"Subject":{"Role":"article_master"},"Verbs":[{"article":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"with":{"State":"Generated"}}],"Object":{"Role":"article_master.article_with_name"}}]},"State":"Generated","Weight":0.95,"ID":"article_masters_article_with_article_with_name"}]},"OBS_sheet_has_MRP_value":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.MRP_value":{"Target":{"Entity":"OBS_sheet.MRP_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.MRP_value"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_MRP_values"}]},"row_controller_has_row_controller":{"Binding":{"ConceptualEntity":"RowController"},"State":"Generated","Roles":{"row_controller":{"Target":{"Entity":"row_controller"}},"row_controller.row_controller":{"Target":{"Entity":"row_controller.row_controller"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"row_controller"},"Object":{"Role":"row_controller.row_controller"}},"State":"Generated","Weight":0.99,"ID":"row_controllers_have_row_controllers"},{"Name":{"Subject":{"Role":"row_controller"},"Name":{"Role":"row_controller.row_controller"}},"State":"Generated","Weight":0.99,"ID":"row_controllers_are_names_IDs_of_row_controllers"}]},"movement_parameter_has_MovementParameter_value":{"Binding":{"ConceptualEntity":"MovementParameter"},"State":"Generated","Roles":{"movement_parameter":{"Target":{"Entity":"movement_parameter"}},"movement_parameter.MovementParameter_value":{"Target":{"Entity":"movement_parameter.MovementParameter_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"movement_parameter"},"Object":{"Role":"movement_parameter.MovementParameter_value"}},"State":"Generated","Weight":0.99,"ID":"movement_parameters_have_MovementParameter_value"}]},"movement_parameter_has_movement_parameter":{"Binding":{"ConceptualEntity":"MovementParameter"},"State":"Generated","Roles":{"movement_parameter":{"Target":{"Entity":"movement_parameter"}},"movement_parameter.movement_parameter":{"Target":{"Entity":"movement_parameter.movement_parameter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"movement_parameter"},"Object":{"Role":"movement_parameter.movement_parameter"}},"State":"Generated","Weight":0.99,"ID":"movement_parameters_have_movement_parameters"}]},"sale_through_parameter_has_SaleThroughParameter_value":{"Binding":{"ConceptualEntity":"SaleThroughParameter"},"State":"Generated","Roles":{"sale_through_parameter":{"Target":{"Entity":"sale_through_parameter"}},"sale_through_parameter.SaleThroughParameter_value":{"Target":{"Entity":"sale_through_parameter.SaleThroughParameter_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale_through_parameter"},"Object":{"Role":"sale_through_parameter.SaleThroughParameter_value"}},"State":"Generated","Weight":0.99,"ID":"sale_through_parameter_have_SaleThroughParameter_value"}]},"sale_through_parameter_has_sale_through_parameter":{"Binding":{"ConceptualEntity":"SaleThroughParameter"},"State":"Generated","Roles":{"sale_through_parameter":{"Target":{"Entity":"sale_through_parameter"}},"sale_through_parameter.sale_through_parameter":{"Target":{"Entity":"sale_through_parameter.sale_through_parameter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale_through_parameter"},"Object":{"Role":"sale_through_parameter.sale_through_parameter"}},"State":"Generated","Weight":0.99,"ID":"sale_through_parameter_have_sale_through_parameter"}]},"sale_velocityparameter_has_SaleVelocityparameter_value":{"Binding":{"ConceptualEntity":"SaleVelocityparameter"},"State":"Generated","Roles":{"sale_velocityparameter":{"Target":{"Entity":"sale_velocityparameter"}},"sale_velocityparameter.SaleVelocityparameter_value":{"Target":{"Entity":"sale_velocityparameter.SaleVelocityparameter_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale_velocityparameter"},"Object":{"Role":"sale_velocityparameter.SaleVelocityparameter_value"}},"State":"Generated","Weight":0.99,"ID":"sale_velocityparameters_have_SaleVelocityparameter_value"}]},"sale_velocityparameter_has_sale_velocityparameter":{"Binding":{"ConceptualEntity":"SaleVelocityparameter"},"State":"Generated","Roles":{"sale_velocityparameter":{"Target":{"Entity":"sale_velocityparameter"}},"sale_velocityparameter.sale_velocityparameter":{"Target":{"Entity":"sale_velocityparameter.sale_velocityparameter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"sale_velocityparameter"},"Object":{"Role":"sale_velocityparameter.sale_velocityparameter"}},"State":"Generated","Weight":0.99,"ID":"sale_velocityparameters_have_sale_velocityparameters"}]},"age_parameter_has_AgeParameter_value":{"Binding":{"ConceptualEntity":"AgeParameter"},"State":"Generated","Roles":{"age_parameter":{"Target":{"Entity":"age_parameter"}},"age_parameter.AgeParameter_value":{"Target":{"Entity":"age_parameter.AgeParameter_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"age_parameter"},"Object":{"Role":"age_parameter.AgeParameter_value"}},"State":"Generated","Weight":0.99,"ID":"age_parameters_have_AgeParameter_value"}]},"age_parameter_has_age_parameter":{"Binding":{"ConceptualEntity":"AgeParameter"},"State":"Generated","Roles":{"age_parameter":{"Target":{"Entity":"age_parameter"}},"age_parameter.age_parameter":{"Target":{"Entity":"age_parameter.age_parameter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"age_parameter"},"Object":{"Role":"age_parameter.age_parameter"}},"State":"Generated","Weight":0.99,"ID":"age_parameters_have_age_parameters"}]},"transaction_type_has_id_group":{"Binding":{"ConceptualEntity":"TransactionType"},"State":"Generated","Roles":{"transaction_type":{"Target":{"Entity":"transaction_type"}},"transaction_type.id_group":{"Target":{"Entity":"transaction_type.id_group"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"transaction_type"},"Object":{"Role":"transaction_type.id_group"}},"State":"Generated","Weight":0.99,"ID":"transaction_types_have_id_groups"}]},"transaction_type_has_group":{"Binding":{"ConceptualEntity":"TransactionType"},"State":"Generated","Roles":{"transaction_type":{"Target":{"Entity":"transaction_type"}},"transaction_type.group":{"Target":{"Entity":"transaction_type.group"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"transaction_type"},"Object":{"Role":"transaction_type.group"}},"State":"Generated","Weight":0.99,"ID":"transaction_types_have_groups"}]},"transaction_type_has_id":{"Binding":{"ConceptualEntity":"TransactionType"},"State":"Generated","Roles":{"transaction_type":{"Target":{"Entity":"transaction_type"}},"transaction_type.id":{"Target":{"Entity":"transaction_type.id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"transaction_type"},"Object":{"Role":"transaction_type.id"}},"State":"Generated","Weight":0.99,"ID":"transaction_types_have_ids"},{"Name":{"Subject":{"Role":"transaction_type"},"Name":{"Role":"transaction_type.id"}},"State":"Generated","Weight":0.99,"ID":"ids_are_names_IDs_of_transaction_types"}]},"transaction_type_has_type":{"Binding":{"ConceptualEntity":"TransactionType"},"State":"Generated","Roles":{"transaction_type":{"Target":{"Entity":"transaction_type"}},"transaction_type.type":{"Target":{"Entity":"transaction_type.type"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"transaction_type"},"Object":{"Role":"transaction_type.type"}},"State":"Generated","Weight":0.99,"ID":"transaction_types_have_types"}]},"shelf_life_parameter_has_shelf_life_value":{"Binding":{"ConceptualEntity":"ShelfLifeParameter"},"State":"Generated","Roles":{"shelf_life_parameter":{"Target":{"Entity":"shelf_life_parameter"}},"shelf_life_parameter.shelf_life_value":{"Target":{"Entity":"shelf_life_parameter.shelf_life_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"shelf_life_parameter"},"Object":{"Role":"shelf_life_parameter.shelf_life_value"}},"State":"Generated","Weight":0.99,"ID":"shelf_life_parameters_have_shelf_life_value"}]},"shelf_life_parameter_has_shelf_life":{"Binding":{"ConceptualEntity":"ShelfLifeParameter"},"State":"Generated","Roles":{"shelf_life_parameter":{"Target":{"Entity":"shelf_life_parameter"}},"shelf_life_parameter.shelf_life":{"Target":{"Entity":"shelf_life_parameter.shelf_life"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"shelf_life_parameter"},"Object":{"Role":"shelf_life_parameter.shelf_life"}},"State":"Generated","Weight":0.99,"ID":"shelf_life_parameters_have_shelf_lives"}]},"OBS_sheet_has_all_measure_closingwithGT":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.closingwithGT":{"Target":{"Entity":"all_measure.closingwithGT"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.closingwithGT"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_closingwithGT"}]},"all_measure_has_movementslicer":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.movementslicer":{"Target":{"Entity":"all_measure.movementslicer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.movementslicer"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_movementslicer"}]},"all_measure_has_sale_thorughslicer":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.sale_thorughslicer":{"Target":{"Entity":"all_measure.sale_thorughslicer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.sale_thorughslicer"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_sale_thorughslicer"}]},"all_measure_has_salevelocity_slicer":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.salevelocity_slicer":{"Target":{"Entity":"all_measure.salevelocity_slicer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.salevelocity_slicer"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_salevelocity_slicer"}]},"inward__outward_has_all_measure_max_sale_date":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"all_measure.max_sale_date":{"Target":{"Entity":"all_measure.max_sale_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"all_measure.max_sale_date"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_max_sale_date"}]},"all_measure_has_salethrough":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.salethrough":{"Target":{"Entity":"all_measure.salethrough"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.salethrough"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_salethrough"}]},"all_measure_has_status":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.status":{"Target":{"Entity":"all_measure.status"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.status"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_status"}]},"all_measure_has_movement_trend":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.movement_trend":{"Target":{"Entity":"all_measure.movement_trend"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.movement_trend"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_movement_trend"}]},"all_measure_has_expected_sale":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.expected_sale":{"Target":{"Entity":"all_measure.expected_sale"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.expected_sale"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_expected_sale"}]},"all_measure_has_purchasefor_WA":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.purchasefor_WA":{"Target":{"Entity":"all_measure.purchasefor_WA"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.purchasefor_WA"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_purchasefor_WA"}]},"OBS_sheet_has_all_measure_closing":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.closing":{"Target":{"Entity":"all_measure.closing"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.closing"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_closing"}]},"all_measure_has_outward":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.outward":{"Target":{"Entity":"all_measure.outward"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.outward"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_outward"}]},"all_measure_has_sale":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.sale":{"Target":{"Entity":"all_measure.sale"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.sale"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_sale"}]},"all_measure_has_ageslicer":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.ageslicer":{"Target":{"Entity":"all_measure.ageslicer"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.ageslicer"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_ageslicer"}]},"all_measure_has_purchase":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.purchase":{"Target":{"Entity":"all_measure.purchase"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.purchase"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_purchase"}]},"OBS_sheet_has_all_measure_opening":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"all_measure.opening":{"Target":{"Entity":"all_measure.opening"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"all_measure.opening"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_opening"}]},"all_measure_has_age":{"Binding":{"ConceptualEntity":"All_Measures"},"State":"Generated","Roles":{"all_measure":{"Target":{"Entity":"all_measure"}},"all_measure.age":{"Target":{"Entity":"all_measure.age"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"all_measure"},"Object":{"Role":"all_measure.age"}},"State":"Generated","Weight":0.99,"ID":"all_measures_have_age"},{"Adjective":{"Subject":{"Role":"all_measure"},"Adjectives":[{"old":{"State":"Generated"}}],"Antonyms":[{"young":{"State":"Generated"}}],"Measurement":{"Role":"all_measure.age"}},"State":"Generated","Weight":0.99,"ID":"age_indicates_how_old_all_measures_are"}]},"article_master_has_size_name":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.size_name":{"Target":{"Entity":"article_master.size_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.size_name"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_size_names"}]},"article_master_has_upc":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.upc":{"Target":{"Entity":"article_master.upc"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.upc"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_upcs"}]},"OBS_sheet_has_closing_date":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.closing_date":{"Target":{"Entity":"OBS_sheet.closing_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.closing_date"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_closing_dates"}]},"OBS_sheet_has_opening_date":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.opening_date":{"Target":{"Entity":"OBS_sheet.opening_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.opening_date"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_opening_dates"}]},"inward__outward_has_size_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.size_name":{"Target":{"Entity":"inward__outward.size_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.size_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_size_names"}]},"inward__outward_has_max_sale_date":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.max_sale_date":{"Target":{"Entity":"inward__outward.max_sale_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.max_sale_date"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_max_sale_dates"}]},"inward__outward_has_sum_product":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.sum_product":{"Target":{"Entity":"inward__outward.sum_product"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.sum_product"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_sum_products"}]},"article_master_has_uid":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.uid":{"Target":{"Entity":"article_master.uid"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.uid"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_uids"}]},"article_master_has_sku_rsp":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.sku_rsp":{"Target":{"Entity":"article_master.sku_rsp"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.sku_rsp"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_sku_rsps"}]},"article_master_has_brand_name":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.brand_name":{"Target":{"Entity":"article_master.brand_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.brand_name"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_brand_names"}]},"article_master_has_gender":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.gender":{"Target":{"Entity":"article_master.gender"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.gender"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_genders"}]},"article_master_has_article_name":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.article_name":{"Target":{"Entity":"article_master.article_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.article_name"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_article_names"}]},"article_master_has_section_name":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.section_name":{"Target":{"Entity":"article_master.section_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.section_name"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_section_names"}]},"article_master_has_article_no":{"Binding":{"ConceptualEntity":"ArticleMaster"},"State":"Generated","Roles":{"article_master":{"Target":{"Entity":"article_master"}},"article_master.article_no":{"Target":{"Entity":"article_master.article_no"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"article_master"},"Object":{"Role":"article_master.article_no"}},"State":"Generated","Weight":0.99,"ID":"article_masters_have_article_noes"}]},"calendar_has_working_day":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.working_day":{"Target":{"Entity":"calendar.working_day"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.working_day"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_working_days"}]},"calendar_has_day_of_fiscal_year_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.day_of_fiscal_year_number":{"Target":{"Entity":"calendar.day_of_fiscal_year_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.day_of_fiscal_year_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_day_of_fiscal_year_number"}]},"calendar_has_day_of_month_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.day_of_month_number":{"Target":{"Entity":"calendar.day_of_month_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.day_of_month_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_day_of_month_number"}]},"calendar_has_day_of_week_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.day_of_week_number":{"Target":{"Entity":"calendar.day_of_week_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.day_of_week_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_day_of_week_number"}]},"calendar_has_day_of_week":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.day_of_week":{"Target":{"Entity":"calendar.day_of_week"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.day_of_week"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_day_of_week"}]},"calendar_has_fiscal_month_in_quarter_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.fiscal_month_in_quarter_number":{"Target":{"Entity":"calendar.fiscal_month_in_quarter_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.fiscal_month_in_quarter_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fiscal_month_in_quarter_number"}]},"calendar_has_fiscal_month_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.fiscal_month_number":{"Target":{"Entity":"calendar.fiscal_month_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.fiscal_month_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fiscal_month_numbers"}]},"calendar_has_month":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.month":{"Target":{"Entity":"calendar.month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.month"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_months"}]},"calendar_has_fiscal_quarter":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.fiscal_quarter":{"Target":{"Entity":"calendar.fiscal_quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.fiscal_quarter"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fiscal_quarters"}]},"calendar_has_fiscal_year_quarter_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.fiscal_year_quarter_number":{"Target":{"Entity":"calendar.fiscal_year_quarter_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.fiscal_year_quarter_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fiscal_year_quarter_numbers"}]},"calendar_has_fiscal_year_quarter":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.fiscal_year_quarter":{"Target":{"Entity":"calendar.fiscal_year_quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.fiscal_year_quarter"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fiscal_year_quarters"}]},"calendar_has_fiscal_year_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.fiscal_year_number":{"Target":{"Entity":"calendar.fiscal_year_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.fiscal_year_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fiscal_year_numbers"}]},"calendar_has_fiscal_year":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.fiscal_year":{"Target":{"Entity":"calendar.fiscal_year"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.fiscal_year"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_fiscal_years"}]},"calendar_has_year_month_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.year_month_number":{"Target":{"Entity":"calendar.year_month_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.year_month_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_year_month_numbers"}]},"calendar_has_year_month":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.year_month":{"Target":{"Entity":"calendar.year_month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.year_month"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_year_months"}]},"calendar_has_sequential_day_number":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.sequential_day_number":{"Target":{"Entity":"calendar.sequential_day_number"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.sequential_day_number"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_sequential_day_numbers"}]},"calendar_has_date_key":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.date_key":{"Target":{"Entity":"calendar.date_key"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.date_key"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_date_keys"}]},"calendar_has_date":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar":{"Target":{"Entity":"calendar"}},"calendar.date":{"Target":{"Entity":"calendar.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar"},"Object":{"Role":"calendar.date"}},"State":"Generated","Weight":0.99,"ID":"calendars_have_dates"}]},"location_master_has_location_name":{"Binding":{"ConceptualEntity":"LocationMaster"},"State":"Generated","Roles":{"location_master":{"Target":{"Entity":"location_master"}},"location_master.location_name":{"Target":{"Entity":"location_master.location_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"location_master"},"Object":{"Role":"location_master.location_name"}},"State":"Generated","Weight":0.99,"ID":"location_masters_have_location_names"}]},"location_master_has_code":{"Binding":{"ConceptualEntity":"LocationMaster"},"State":"Generated","Roles":{"location_master":{"Target":{"Entity":"location_master"}},"location_master.code":{"Target":{"Entity":"location_master.code"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"location_master"},"Object":{"Role":"location_master.code"}},"State":"Generated","Weight":0.99,"ID":"location_masters_have_codes"},{"Verb":{"Subject":{"Role":"location_master"},"Verbs":[{"Reshuffle":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"from":{"State":"Generated"}}],"Object":{"Role":"location_master.code"}}]},"State":"Generated","Weight":0.95,"ID":"location_masters_Reshuffle_from_codes"},{"Verb":{"Subject":{"Role":"location_master"},"Verbs":[{"Refill":{"State":"Generated"}}],"PrepositionalPhrases":[{"Prepositions":[{"To":{"State":"Generated"}}],"Object":{"Role":"location_master.code"}}]},"State":"Generated","Weight":0.95,"ID":"location_masters_Refill_To_codes"}]},"location_master_has_location_ID":{"Binding":{"ConceptualEntity":"LocationMaster"},"State":"Generated","Roles":{"location_master":{"Target":{"Entity":"location_master"}},"location_master.location_ID":{"Target":{"Entity":"location_master.location_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"location_master"},"Object":{"Role":"location_master.location_ID"}},"State":"Generated","Weight":0.99,"ID":"location_masters_have_location_ID"}]},"OBS_sheet_has_net_SLS_qty":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.net_SLS_qty":{"Target":{"Entity":"OBS_sheet.net_SLS_qty"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.net_SLS_qty"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_net_SLS_qties"}]},"OBS_sheet_has_CBS_value_at_WSP":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.CBS_value_at_WSP":{"Target":{"Entity":"OBS_sheet.CBS_value_at_WSP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.CBS_value_at_WSP"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_CBS_value_at_WSP"}]},"OBS_sheet_has_CBS_value_at_MRP":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.CBS_value_at_MRP":{"Target":{"Entity":"OBS_sheet.CBS_value_at_MRP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.CBS_value_at_MRP"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_CBS_value_at_MRP"}]},"OBS_sheet_has_CBS_qty":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.CBS_qty":{"Target":{"Entity":"OBS_sheet.CBS_qty"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.CBS_qty"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_CBS_qties"}]},"OBS_sheet_has_OBS_value_at_MRP":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.OBS_value_at_MRP":{"Target":{"Entity":"OBS_sheet.OBS_value_at_MRP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.OBS_value_at_MRP"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_OBS_value_at_MRP"}]},"OBS_sheet_has_OBS_qty":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.OBS_qty":{"Target":{"Entity":"OBS_sheet.OBS_qty"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.OBS_qty"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_OBS_qties"}]},"OBS_sheet_has_wholesale_price":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.wholesale_price":{"Target":{"Entity":"OBS_sheet.wholesale_price"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.wholesale_price"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_wholesale_prices"},{"Adjective":{"Subject":{"Role":"OBS_sheet"},"Adjectives":[{"expensive":{"State":"Generated"}}],"Antonyms":[{"cheap":{"State":"Generated"}}],"Measurement":{"Role":"OBS_sheet.wholesale_price"}},"State":"Generated","Weight":0.99,"ID":"wholesale_price_indicates_how_expensive_OBS_sheets_are"}]},"OBS_sheet_has_sku_rsp":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.sku_rsp":{"Target":{"Entity":"OBS_sheet.sku_rsp"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.sku_rsp"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_sku_rsps"}]},"OBS_sheet_has_size_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.size_name":{"Target":{"Entity":"OBS_sheet.size_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.size_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_size_names"}]},"OBS_sheet_has_brand_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.brand_name":{"Target":{"Entity":"OBS_sheet.brand_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.brand_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_brand_names"}]},"OBS_sheet_has_gender":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.gender":{"Target":{"Entity":"OBS_sheet.gender"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.gender"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_genders"}]},"OBS_sheet_has_article_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.article_name":{"Target":{"Entity":"OBS_sheet.article_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.article_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_article_names"}]},"OBS_sheet_has_sub_section_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.sub_section_name":{"Target":{"Entity":"OBS_sheet.sub_section_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.sub_section_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_sub_section_names"}]},"OBS_sheet_has_section_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.section_name":{"Target":{"Entity":"OBS_sheet.section_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.section_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_section_names"}]},"OBS_sheet_has_article_no":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.article_no":{"Target":{"Entity":"OBS_sheet.article_no"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.article_no"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_article_noes"}]},"OBS_sheet_has_upc":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.upc":{"Target":{"Entity":"OBS_sheet.upc"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.upc"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_upcs"}]},"OBS_sheet_has_item_code":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.item_code":{"Target":{"Entity":"OBS_sheet.item_code"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.item_code"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_item_codes"}]},"OBS_sheet_has_location_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.location_name":{"Target":{"Entity":"OBS_sheet.location_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.location_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_location_names"}]},"OBS_sheet_has_location_alias":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.location_alias":{"Target":{"Entity":"OBS_sheet.location_alias"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"OBS_sheet"},"Object":{"Role":"OBS_sheet.location_alias"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_have_location_aliases"}]},"inward__outward_has_upc":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.upc":{"Target":{"Entity":"inward__outward.upc"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.upc"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_upcs"}]},"inward__outward_has_transaction_value_with_GST":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_value_with_GST":{"Target":{"Entity":"inward__outward.transaction_value_with_GST"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_value_with_GST"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_value_with_GST"}]},"inward__outward_has_transaction_value_at_MRP":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_value_at_MRP":{"Target":{"Entity":"inward__outward.transaction_value_at_MRP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_value_at_MRP"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_value_at_MRP"}]},"inward__outward_has_transaction_total_GST_amt":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_total_GST_amt":{"Target":{"Entity":"inward__outward.transaction_total_GST_amt"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_total_GST_amt"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_total_GST_amts"}]},"inward__outward_has_transaction_taxable_value":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_taxable_value":{"Target":{"Entity":"inward__outward.transaction_taxable_value"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_taxable_value"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_taxable_values"}]},"inward__outward_has_transaction_quantity":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_quantity":{"Target":{"Entity":"inward__outward.transaction_quantity"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_quantity"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_quantities"}]},"inward__outward_has_bin_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.bin_name":{"Target":{"Entity":"inward__outward.bin_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.bin_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_bin_names"}]},"inward__outward_has_transaction_RSP":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_RSP":{"Target":{"Entity":"inward__outward.transaction_RSP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_RSP"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_RSPs"}]},"inward__outward_has_sku_rsp":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.sku_rsp":{"Target":{"Entity":"inward__outward.sku_rsp"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.sku_rsp"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_sku_rsps"}]},"inward__outward_has_colour_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.colour_name":{"Target":{"Entity":"inward__outward.colour_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.colour_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_colour_names"}]},"inward__outward_has_HSN_code":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.HSN_code":{"Target":{"Entity":"inward__outward.HSN_code"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.HSN_code"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_HSN_codes"}]},"inward__outward_has_category":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.category":{"Target":{"Entity":"inward__outward.category"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.category"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_categories"}]},"inward__outward_has_gender":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.gender":{"Target":{"Entity":"inward__outward.gender"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.gender"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_genders"}]},"inward__outward_has_item_class":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.item_class":{"Target":{"Entity":"inward__outward.item_class"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.item_class"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_item_classes"}]},"inward__outward_has_weather":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.weather":{"Target":{"Entity":"inward__outward.weather"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.weather"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_weathers"}]},"inward__outward_has_article_no":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.article_no":{"Target":{"Entity":"inward__outward.article_no"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.article_no"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_article_noes"}]},"inward__outward_has_style_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.style_name":{"Target":{"Entity":"inward__outward.style_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.style_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_style_names"}]},"inward__outward_has_article_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.article_name":{"Target":{"Entity":"inward__outward.article_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.article_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_article_names"}]},"inward__outward_has_section_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.section_name":{"Target":{"Entity":"inward__outward.section_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.section_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_section_names"}]},"inward__outward_has_brand_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.brand_name":{"Target":{"Entity":"inward__outward.brand_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.brand_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_brand_names"}]},"inward__outward_has_party_city":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.party_city":{"Target":{"Entity":"inward__outward.party_city"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.party_city"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_party_cities"}]},"inward__outward_has_party_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.party_name":{"Target":{"Entity":"inward__outward.party_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.party_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_party_names"}]},"inward__outward_has_transaction_location_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_location_name":{"Target":{"Entity":"inward__outward.transaction_location_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_location_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_location_names"}]},"inward__outward_has_transaction_no":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_no":{"Target":{"Entity":"inward__outward.transaction_no"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_no"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_noes"}]},"inward__outward_has_transaction_date":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_date":{"Target":{"Entity":"inward__outward.transaction_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward"},"Object":{"Role":"inward__outward.transaction_date"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_have_transaction_dates"}]},"OBS_sheet_in_location_master":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"location_master":{"Target":{"Entity":"location_master"}}},"SemanticSlots":{"Where":{"Role":"location_master"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"OBS_sheet"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"location_master"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_are_in_location_masters"}]},"inward__outward_in_location_master":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"location_master":{"Target":{"Entity":"location_master"}}},"SemanticSlots":{"Where":{"Role":"location_master"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"inward__outward"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"location_master"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_are_in_location_masters"}]},"location_master_in_location_name":{"Binding":{"ConceptualEntity":"LocationMaster"},"State":"Generated","Roles":{"location_master":{"Target":{"Entity":"location_master"}},"location_master.location_name":{"Target":{"Entity":"location_master.location_name"}}},"SemanticSlots":{"Where":{"Role":"location_master.location_name"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"location_master"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"location_master.location_name"}},"State":"Generated","Weight":0.99,"ID":"location_masters_are_in_location_names"}]},"location_master_in_location_ID":{"Binding":{"ConceptualEntity":"LocationMaster"},"State":"Generated","Roles":{"location_master":{"Target":{"Entity":"location_master"}},"location_master.location_ID":{"Target":{"Entity":"location_master.location_ID"}}},"SemanticSlots":{"Where":{"Role":"location_master.location_ID"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"location_master"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"location_master.location_ID"}},"State":"Generated","Weight":0.99,"ID":"location_masters_are_in_location_ID"}]},"OBS_sheet_in_location_name":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.location_name":{"Target":{"Entity":"OBS_sheet.location_name"}}},"SemanticSlots":{"Where":{"Role":"OBS_sheet.location_name"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"OBS_sheet"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"OBS_sheet.location_name"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_are_in_location_names"}]},"OBS_sheet_in_location_alias":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.location_alias":{"Target":{"Entity":"OBS_sheet.location_alias"}}},"SemanticSlots":{"Where":{"Role":"OBS_sheet.location_alias"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"OBS_sheet"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"OBS_sheet.location_alias"}},"State":"Generated","Weight":0.99,"ID":"OBS_sheets_are_in_location_aliases"}]},"inward__outward_in_party_city":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.party_city":{"Target":{"Entity":"inward__outward.party_city"}}},"SemanticSlots":{"Where":{"Role":"inward__outward.party_city"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"inward__outward"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"inward__outward.party_city"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_are_in_party_cities"}]},"inward__outward_in_transaction_location_name":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward":{"Target":{"Entity":"inward__outward"}},"inward__outward.transaction_location_name":{"Target":{"Entity":"inward__outward.transaction_location_name"}}},"SemanticSlots":{"Where":{"Role":"inward__outward.transaction_location_name"}},"Phrasings":[{"Preposition":{"Subject":{"Role":"inward__outward"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"inward__outward.transaction_location_name"}},"State":"Generated","Weight":0.99,"ID":"inward__outwards_are_in_transaction_location_names"}]},"OBS_sheet_is_closed_on_closing_date":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.closing_date":{"Target":{"Entity":"OBS_sheet.closing_date"}}},"SemanticSlots":{"When":{"Role":"OBS_sheet.closing_date"}},"Phrasings":[{"Verb":{"Verbs":[{"close":{"State":"Generated"}}],"Object":{"Role":"OBS_sheet"}},"State":"Generated","Weight":0.9,"ID":"OBS_sheets_are_closed_on_closing_dates"}]},"OBS_sheet_is_opened_on_opening_date":{"Binding":{"ConceptualEntity":"OBS_sheet"},"State":"Generated","Roles":{"OBS_sheet":{"Target":{"Entity":"OBS_sheet"}},"OBS_sheet.opening_date":{"Target":{"Entity":"OBS_sheet.opening_date"}}},"SemanticSlots":{"When":{"Role":"OBS_sheet.opening_date"}},"Phrasings":[{"Verb":{"Verbs":[{"open":{"State":"Generated"}}],"Object":{"Role":"OBS_sheet"}},"State":"Generated","Weight":0.9,"ID":"OBS_sheets_are_opened_on_opening_dates"}]},"row_controller_control":{"Binding":{"ConceptualEntity":"RowController"},"State":"Generated","Roles":{"row_controller":{"Target":{"Entity":"row_controller"}}},"Phrasings":[{"Verb":{"Subject":{"Role":"row_controller"},"Verbs":[{"control":{"State":"Generated"}}]},"State":"Generated","Weight":0.75,"ID":"row_controllers_control"}]},"calendar_date_date_hierarchy_has_calendar_date_year":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar.date.date_hierarchy":{"Target":{"Entity":"calendar.date.date_hierarchy"}},"calendar.date.year":{"Target":{"Entity":"calendar.date.year"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar.date.date_hierarchy"},"Object":{"Role":"calendar.date.year"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_years"}]},"calendar_date_date_hierarchy_has_calendar_date_quarter":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar.date.date_hierarchy":{"Target":{"Entity":"calendar.date.date_hierarchy"}},"calendar.date.quarter":{"Target":{"Entity":"calendar.date.quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar.date.date_hierarchy"},"Object":{"Role":"calendar.date.quarter"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_quarters"}]},"calendar_date_date_hierarchy_has_calendar_date_month":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar.date.date_hierarchy":{"Target":{"Entity":"calendar.date.date_hierarchy"}},"calendar.date.month":{"Target":{"Entity":"calendar.date.month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar.date.date_hierarchy"},"Object":{"Role":"calendar.date.month"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_months"}]},"calendar_date_date_hierarchy_has_calendar_date_day":{"Binding":{"ConceptualEntity":"Calendar"},"State":"Generated","Roles":{"calendar.date.date_hierarchy":{"Target":{"Entity":"calendar.date.date_hierarchy"}},"calendar.date.day":{"Target":{"Entity":"calendar.date.day"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"calendar.date.date_hierarchy"},"Object":{"Role":"calendar.date.day"}},"State":"Generated","Weight":0.99,"ID":"date_hierarchies_have_days"}]},"inward__outward_max_sale_date_has_date_hierarchy":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward.max_sale_date":{"Target":{"Entity":"inward__outward.max_sale_date"}},"inward__outward.max_sale_date.date_hierarchy":{"Target":{"Entity":"inward__outward.max_sale_date.date_hierarchy"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward.max_sale_date"},"Object":{"Role":"inward__outward.max_sale_date.date_hierarchy"}},"State":"Generated","Weight":0.99,"ID":"max_sale_dates_have_max_sale_date_hierarchies"}]},"inward__outward_max_sale_date_date_hierarchy_has_inward__outward_max_sale_date_year":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward.max_sale_date.date_hierarchy":{"Target":{"Entity":"inward__outward.max_sale_date.date_hierarchy"}},"inward__outward.max_sale_date.year":{"Target":{"Entity":"inward__outward.max_sale_date.year"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward.max_sale_date.date_hierarchy"},"Object":{"Role":"inward__outward.max_sale_date.year"}},"State":"Generated","Weight":0.99,"ID":"max_sale_date_hierarchies_have_max_sale_years"}]},"inward__outward_max_sale_date_date_hierarchy_has_inward__outward_max_sale_date_quarter":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward.max_sale_date.date_hierarchy":{"Target":{"Entity":"inward__outward.max_sale_date.date_hierarchy"}},"inward__outward.max_sale_date.quarter":{"Target":{"Entity":"inward__outward.max_sale_date.quarter"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward.max_sale_date.date_hierarchy"},"Object":{"Role":"inward__outward.max_sale_date.quarter"}},"State":"Generated","Weight":0.99,"ID":"max_sale_date_hierarchies_have_max_sale_quarters"}]},"inward__outward_max_sale_date_date_hierarchy_has_inward__outward_max_sale_date_month":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward.max_sale_date.date_hierarchy":{"Target":{"Entity":"inward__outward.max_sale_date.date_hierarchy"}},"inward__outward.max_sale_date.month":{"Target":{"Entity":"inward__outward.max_sale_date.month"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward.max_sale_date.date_hierarchy"},"Object":{"Role":"inward__outward.max_sale_date.month"}},"State":"Generated","Weight":0.99,"ID":"max_sale_date_hierarchies_have_max_sale_months"}]},"inward__outward_max_sale_date_date_hierarchy_has_inward__outward_max_sale_date_day":{"Binding":{"ConceptualEntity":"INWARD & OUTWARD"},"State":"Generated","Roles":{"inward__outward.max_sale_date.date_hierarchy":{"Target":{"Entity":"inward__outward.max_sale_date.date_hierarchy"}},"inward__outward.max_sale_date.day":{"Target":{"Entity":"inward__outward.max_sale_date.day"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"inward__outward.max_sale_date.date_hierarchy"},"Object":{"Role":"inward__outward.max_sale_date.day"}},"State":"Generated","Weight":0.99,"ID":"max_sale_date_hierarchies_have_max_sale_days"}]}},"Agents":{"Internal":{"Version":"1.1.0"}}}
				contentType: json

		expression UniqueARticleInOut =
				let
				    Source = #"INWARD & OUTWARD",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Brand Name", "Section Name", "Article Name", "Article No", "Gender", "Transaction RSP", "UPC", "Size Name","Season Name","Season2"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates",{"Article No", "Section Name", "Article Name", "Gender", "Brand Name", "Transaction RSP"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Transaction RSP", "SKU RSP"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns",{"UPC", "Article No", "Section Name", "Article Name", "Gender", "Brand Name", "SKU RSP"})
				in
				    #"Reordered Columns1"
			lineageTag: 13b98426-b924-4a9e-81e7-4159c197aef1

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression UniqueARticleOBS =
				let
				    Source = OBS_sheet,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"UPC", "Article No", "Section Name", "Sub Section Name", "Article Name", "Gender", "Brand Name", "Size Name", "SKU RSP","Season Name","Season2"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Removed Duplicates",{"UPC", "Article No", "Section Name", "Article Name", "Gender", "Brand Name", "Size Name", "SKU RSP","Season Name","Season2"})
				in
				    #"Removed Other Columns1"
			lineageTag: 2be506f2-3568-491a-9afc-71d5cf007411

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		annotation PBI_QueryOrder = ["INWARD & OUTWARD","OBS_sheet","LocationMaster","UniqueARticleOBS","UniqueARticleInOut","ArticleMaster","All_Measures","TransactionType","Status filter","SizeMaster","Sizemerger","Size Set","SizeSetFilter"]

		annotation __PBI_TimeIntelligenceEnabled = 1

		annotation PBI_ProTooling = ["DaxQueryView_Desktop"]

		annotation PBIDesktopVersion = 2.146.1254.0 (25.08)+791a7518fadc83da883d79322a2658aff57c8db3

